/* Copyright 2026 Spice Labs, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License. */

package io.spicelabs.annatto.testutil;

import com.google.gson.Gson;
import com.google.gson.JsonObject;

import java.io.IOException;
import java.io.Reader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Utility for loading and matching source of truth JSON files with test corpus packages.
 *
 * <p>Theory: Tests should validate that Annatto's extraction produces output matching
 * native tool extraction. The JSON files in src/test/resources/<ecosystem>/ are
 * generated by Docker-based native extractors and committed to git. This loader
 * dynamically discovers package/JSON pairs to ensure:
 * <ul>
 *   <li>Every package file has a corresponding JSON source of truth</li>
 *   <li>Every JSON file has a corresponding package file</li>
 *   <li>No baked-in constants in tests</li>
 * </ul>
 *
 * <p>Matching Rules:
 * <ul>
 *   <li>Package file: test-corpus/&lt;ecosystem&gt;/&lt;name&gt;-&lt;version&gt;.&lt;ext&gt;</li>
 *   <li>JSON file: src/test/resources/&lt;ecosystem&gt;/&lt;name&gt;-&lt;version&gt;-expected.json</li>
 *   <li>For .tar.gz extensions, the full extension is stripped before matching</li>
 * </ul>
 */
public final class SourceOfTruthLoader {

    private static final Gson GSON = new Gson();
    private static final Path TEST_CORPUS = Path.of("test-corpus");
    private static final Path RESOURCES = Path.of("src", "test", "resources");

    private SourceOfTruthLoader() {
    }

    /**
     * Represents a matched package and its source of truth JSON file.
     */
    public record PackageTestCase(
        String ecosystem,
        String packageFilename,
        Path packagePath,
        Path expectedJsonPath
    ) {
        /**
         * Loads and returns the expected JSON content.
         */
        public JsonObject loadExpectedJson() throws IOException {
            try (Reader reader = Files.newBufferedReader(expectedJsonPath)) {
                return GSON.fromJson(reader, JsonObject.class);
            }
        }

        @Override
        public String toString() {
            return ecosystem + "/" + packageFilename;
        }
    }

    /**
     * Discovers all package/JSON pairs for the given ecosystem.
     *
     * <p>Verifies that every package file has a corresponding JSON file and vice versa.
     * Throws AssertionError if any mismatches are found.
     *
     * @param ecosystem the ecosystem directory name (e.g., "npm", "pypi")
     * @return list of matched package test cases
     * @throws AssertionError if any package lacks a JSON file or any JSON lacks a package
     */
    public static List<PackageTestCase> discoverTestCases(String ecosystem) {
        Path corpusDir = TEST_CORPUS.resolve(ecosystem);
        Path expectedDir = RESOURCES.resolve(ecosystem);

        if (!Files.isDirectory(corpusDir)) {
            throw new AssertionError(
                "Test corpus directory does not exist: " + corpusDir +
                "\nRun TestCorpusDownloader.ensureCorpusAvailable() first"
            );
        }

        if (!Files.isDirectory(expectedDir)) {
            throw new AssertionError(
                "Expected JSON directory does not exist: " + expectedDir
            );
        }

        // Discover all package files in corpus
        Map<String, Path> packages = new HashMap<>();
        try (Stream<Path> files = Files.list(corpusDir)) {
            files.filter(Files::isRegularFile)
                .forEach(path -> {
                    String baseName = extractBaseName(path.getFileName().toString());
                    packages.put(baseName, path);
                });
        } catch (IOException e) {
            throw new AssertionError("Failed to list corpus directory: " + corpusDir, e);
        }

        // Discover all JSON files in resources
        Map<String, Path> jsonFiles = new HashMap<>();
        try (Stream<Path> files = Files.list(expectedDir)) {
            files.filter(Files::isRegularFile)
                .filter(path -> path.toString().endsWith("-expected.json"))
                .forEach(path -> {
                    String baseName = extractJsonBaseName(path.getFileName().toString());
                    jsonFiles.put(baseName, path);
                });
        } catch (IOException e) {
            throw new AssertionError("Failed to list expected directory: " + expectedDir, e);
        }

        // Verify every package has a JSON file
        List<String> packagesWithoutJson = new ArrayList<>();
        for (Map.Entry<String, Path> entry : packages.entrySet()) {
            if (!jsonFiles.containsKey(entry.getKey())) {
                packagesWithoutJson.add(entry.getValue().getFileName().toString());
            }
        }

        if (!packagesWithoutJson.isEmpty()) {
            throw new AssertionError(
                "The following packages in " + ecosystem + " lack JSON source of truth files:\n" +
                packagesWithoutJson.stream()
                    .map(f -> "  - " + f + " (expected: " + extractBaseName(f) + "-expected.json)")
                    .collect(Collectors.joining("\n")) +
                "\nGenerate the JSON files using the native extractors and commit them."
            );
        }

        // Verify every JSON file has a package
        List<String> jsonWithoutPackages = new ArrayList<>();
        for (Map.Entry<String, Path> entry : jsonFiles.entrySet()) {
            if (!packages.containsKey(entry.getKey())) {
                jsonWithoutPackages.add(entry.getValue().getFileName().toString());
            }
        }

        if (!jsonWithoutPackages.isEmpty()) {
            throw new AssertionError(
                "The following JSON files in " + ecosystem + " lack corresponding packages:\n" +
                jsonWithoutPackages.stream()
                    .map(f -> "  - " + f)
                    .collect(Collectors.joining("\n")) +
                "\nEither add the package to test-corpus or remove the stale JSON file."
            );
        }

        // Build test cases
        List<PackageTestCase> testCases = new ArrayList<>();
        for (Map.Entry<String, Path> entry : packages.entrySet()) {
            String baseName = entry.getKey();
            Path packagePath = entry.getValue();
            Path jsonPath = jsonFiles.get(baseName);

            testCases.add(new PackageTestCase(
                ecosystem,
                packagePath.getFileName().toString(),
                packagePath,
                jsonPath
            ));
        }

        return testCases;
    }

    /**
     * Extracts the base name from a package filename by removing the extension.
     * Handles special cases like .tar.gz, .tar.bz2, and .podspec.json
     */
    static String extractBaseName(String filename) {
        if (filename.endsWith(".tar.gz")) {
            return filename.substring(0, filename.length() - ".tar.gz".length());
        }
        if (filename.endsWith(".tar.bz2")) {
            return filename.substring(0, filename.length() - ".tar.bz2".length());
        }
        if (filename.endsWith(".podspec.json")) {
            return filename.substring(0, filename.length() - ".podspec.json".length());
        }
        int lastDot = filename.lastIndexOf('.');
        return lastDot > 0 ? filename.substring(0, lastDot) : filename;
    }

    /**
     * Extracts the base name from a JSON filename by removing the -expected.json suffix.
     */
    static String extractJsonBaseName(String filename) {
        if (filename.endsWith("-expected.json")) {
            return filename.substring(0, filename.length() - "-expected.json".length());
        }
        return filename;
    }
}
