/* Copyright 2026 Spice Labs, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License. */

package io.spicelabs.annatto.rubygems;

import com.google.gson.JsonObject;
import io.spicelabs.annatto.common.MetadataResult;
import io.spicelabs.annatto.common.ParsedDependency;
import io.spicelabs.annatto.testutil.SourceOfTruth;
import io.spicelabs.annatto.testutil.TestCorpusDownloader;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.assertj.core.api.Assumptions.assumeThat;

/**
 * Tests for {@link RubygemsMetadataExtractor} comparing extraction results against
 * source-of-truth expected values produced by native Ruby tools in Docker.
 *
 * <p>All test packages are real gems downloaded from rubygems.org.
 * Expected values were generated by running Docker containers with Ruby's
 * {@code Gem::Package} that parse the actual metadata.gz from each archive.</p>
 *
 * <p>Package files (.gem) are in {@code test-corpus/rubygems/} (gitignored).
 * Source-of-truth expected JSON files are in {@code src/test/resources/rubygems/} (git-tracked).</p>
 *
 * <p>Covers {@link RubygemsQuirks} Q1 (Ruby YAML tags), Q2 (description fallback),
 * Q3 (runtime vs dev deps), Q4 (version constraints), Q5 (platform field),
 * Q6 (license join).</p>
 */
class RubygemsMetadataExtractorTest {

    /** Directory containing real .gem files (gitignored). */
    private static final Path GEMS_CORPUS = TestCorpusDownloader.corpusDir("rubygems");

    /** Directory containing source-of-truth expected JSON files (git-tracked). */
    private static final Path GEMS_EXPECTED = TestCorpusDownloader.expectedDir("rubygems");

    @BeforeAll
    static void ensureTestPackagesExist() {
        assumeThat(Files.isDirectory(GEMS_CORPUS))
                .as("rubygems test corpus directory must exist with real packages")
                .isTrue();
    }

    // --- Parameterized source-of-truth comparison ---

    static Stream<Arguments> realPackages() throws IOException {
        if (!Files.isDirectory(GEMS_CORPUS)) {
            return Stream.empty();
        }
        return Files.list(GEMS_CORPUS)
                .filter(p -> p.toString().endsWith(".gem"))
                .sorted()
                .map(pkg -> {
                    Path expected = SourceOfTruth.expectedPathFor(pkg, GEMS_EXPECTED);
                    String label = pkg.getFileName().toString();
                    return Arguments.of(label, pkg, expected);
                });
    }

    /**
     * Goal: Verify that the extracted name matches the source-of-truth for every real gem.
     * Rationale: Name is the most fundamental metadata field; must be exact for all packages (Q1).
     */
    @ParameterizedTest(name = "name: {0}")
    @MethodSource("realPackages")
    void extractName_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.name())
                .isEqualTo(SourceOfTruth.getString(expected, "name"));
    }

    /**
     * Goal: Verify that the extracted simple name matches the source-of-truth.
     * Rationale: For gems, simpleName equals name (no namespace concept).
     */
    @ParameterizedTest(name = "simpleName: {0}")
    @MethodSource("realPackages")
    void extractSimpleName_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.simpleName())
                .isEqualTo(SourceOfTruth.getString(expected, "simpleName"));
    }

    /**
     * Goal: Verify that the extracted version matches the source-of-truth.
     * Rationale: Version must match exactly from the gemspec metadata.
     */
    @ParameterizedTest(name = "version: {0}")
    @MethodSource("realPackages")
    void extractVersion_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.version())
                .isEqualTo(SourceOfTruth.getString(expected, "version"));
    }

    /**
     * Goal: Verify that the extracted description matches the source-of-truth.
     * Rationale: Q2 - description uses summary-first fallback; must match native Ruby output.
     */
    @ParameterizedTest(name = "description: {0}")
    @MethodSource("realPackages")
    void extractDescription_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.description())
                .isEqualTo(SourceOfTruth.getString(expected, "description"));
    }

    /**
     * Goal: Verify that the extracted license matches the source-of-truth.
     * Rationale: Q6 - licenses joined with " OR "; null if empty.
     */
    @ParameterizedTest(name = "license: {0}")
    @MethodSource("realPackages")
    void extractLicense_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.license())
                .isEqualTo(SourceOfTruth.getString(expected, "license"));
    }

    /**
     * Goal: Verify that the extracted publisher matches the source-of-truth.
     * Rationale: Publisher is first author from the authors list.
     */
    @ParameterizedTest(name = "publisher: {0}")
    @MethodSource("realPackages")
    void extractPublisher_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.publisher())
                .isEqualTo(SourceOfTruth.getString(expected, "publisher"));
    }

    /**
     * Goal: Verify that the extracted dependency count matches the source-of-truth.
     * Rationale: All dependencies (runtime + dev) must be parsed correctly.
     */
    @ParameterizedTest(name = "dependencyCount: {0}")
    @MethodSource("realPackages")
    void extractDependencies_countMatchesSourceOfTruth(String label, Path pkgPath, Path expectedPath)
            throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        int expectedCount = expected.getAsJsonArray("dependencies").size();

        assertThat(result.dependencies())
                .as("dependency count for %s", label)
                .hasSize(expectedCount);
    }

    /**
     * Goal: Verify that all extracted dependency names, versions, and scopes match the source-of-truth.
     * Rationale: Q3, Q4 - dependency extraction must correctly parse all YAML dep formats, scopes, and constraints.
     */
    @ParameterizedTest(name = "dependencies: {0}")
    @MethodSource("realPackages")
    void extractDependencies_matchSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        var expectedDeps = expected.getAsJsonArray("dependencies");
        List<DepTuple> expectedTuples = new java.util.ArrayList<>();
        for (var elem : expectedDeps) {
            JsonObject depObj = elem.getAsJsonObject();
            String name = depObj.get("name").getAsString();
            String vc = depObj.get("versionConstraint").isJsonNull() ? null
                    : depObj.get("versionConstraint").getAsString();
            String scope = depObj.get("scope").getAsString();
            expectedTuples.add(new DepTuple(name, vc, scope));
        }

        List<DepTuple> actualTuples = result.dependencies().stream()
                .map(d -> new DepTuple(d.name(), d.versionConstraint().orElse(null), d.scope().orElse(null)))
                .toList();

        assertThat(actualTuples)
                .as("dependencies for %s", label)
                .containsExactlyInAnyOrderElementsOf(expectedTuples);
    }

    record DepTuple(String name, String versionConstraint, String scope) {
    }

    // --- Named package tests ---

    /**
     * Goal: Verify extraction for rake (zero dependencies).
     * Rationale: Boundary case — simplest possible gem with no deps.
     */
    @Test
    void gem_rake_zeroDeps() throws Exception {
        Path gem = GEMS_CORPUS.resolve("rake-13.1.0.gem");
        assumeThat(Files.exists(gem)).isTrue();

        MetadataResult result = extractFromPackage(gem);

        assertThat(result.name()).hasValue("rake");
        assertThat(result.simpleName()).hasValue("rake");
        assertThat(result.version()).hasValue("13.1.0");
        assertThat(result.license()).hasValue("MIT");
        assertThat(result.publisher()).hasValue("Hiroshi SHIBATA");
        assertThat(result.dependencies()).isEmpty();
    }

    /**
     * Goal: Verify extraction for rails (many deps, exact version pinning).
     * Rationale: Q4 — Rails pins sub-gems with "= 7.1.3" exact constraints.
     */
    @Test
    void gem_rails_exactVersionPinning() throws Exception {
        Path gem = GEMS_CORPUS.resolve("rails-7.1.3.gem");
        assumeThat(Files.exists(gem)).isTrue();

        MetadataResult result = extractFromPackage(gem);

        assertThat(result.name()).hasValue("rails");
        assertThat(result.version()).hasValue("7.1.3");
        assertThat(result.publisher()).hasValue("David Heinemeier Hansson");
        assertThat(result.dependencies()).isNotEmpty();
        // Rails pins activesupport with exact version
        assertThat(result.dependencies().stream()
                .filter(d -> d.name().equals("activesupport")
                        && d.versionConstraint().orElse("").equals("= 7.1.3"))
                .findAny()).isPresent();
    }

    /**
     * Goal: Verify extraction for rspec-core (Q3 mixed runtime + dev scopes).
     * Rationale: Q3 — rspec-core has both runtime and development dependencies.
     */
    @Test
    void gem_rspec_core_mixedDependencyScopes() throws Exception {
        Path gem = GEMS_CORPUS.resolve("rspec-core-3.13.0.gem");
        assumeThat(Files.exists(gem)).isTrue();

        MetadataResult result = extractFromPackage(gem);

        assertThat(result.name()).hasValue("rspec-core");
        // Has runtime dep: rspec-support
        assertThat(result.dependencies().stream()
                .filter(d -> d.name().equals("rspec-support") && d.scope().orElse("").equals("runtime"))
                .findAny()).isPresent();
        // Has dev dep: cucumber
        assertThat(result.dependencies().stream()
                .filter(d -> d.name().equals("cucumber") && d.scope().orElse("").equals("dev"))
                .findAny()).isPresent();
    }

    /**
     * Goal: Verify extraction for nokogiri (multiple authors).
     * Rationale: Publisher should be the first author only ("Mike Dalessio").
     */
    @Test
    void gem_nokogiri_multipleAuthors() throws Exception {
        Path gem = GEMS_CORPUS.resolve("nokogiri-1.16.2.gem");
        assumeThat(Files.exists(gem)).isTrue();

        MetadataResult result = extractFromPackage(gem);

        assertThat(result.name()).hasValue("nokogiri");
        assertThat(result.publisher()).hasValue("Mike Dalessio");
    }

    /**
     * Goal: Verify extraction for sinatra (long description, summary preferred).
     * Rationale: Q2 — sinatra has both summary and description; summary should be used.
     */
    @Test
    void gem_sinatra_summaryPreferred() throws Exception {
        Path gem = GEMS_CORPUS.resolve("sinatra-4.0.0.gem");
        assumeThat(Files.exists(gem)).isTrue();

        MetadataResult result = extractFromPackage(gem);

        assertThat(result.name()).hasValue("sinatra");
        assertThat(result.description()).isPresent();
    }

    /**
     * Goal: Verify extraction for faraday (Q4 compound version constraints).
     * Rationale: Q4 — faraday-net_http has ">= 2.0, < 3.2" compound constraint.
     */
    @Test
    void gem_faraday_compoundConstraints() throws Exception {
        Path gem = GEMS_CORPUS.resolve("faraday-2.9.0.gem");
        assumeThat(Files.exists(gem)).isTrue();

        MetadataResult result = extractFromPackage(gem);

        assertThat(result.name()).hasValue("faraday");
        assertThat(result.version()).hasValue("2.9.0");
        // faraday-net_http has compound constraint ">= 2.0, < 3.2"
        assertThat(result.dependencies().stream()
                .filter(d -> d.name().equals("faraday-net_http")
                        && d.versionConstraint().isPresent()
                        && d.versionConstraint().get().contains(">=")
                        && d.versionConstraint().get().contains("<"))
                .findAny()).isPresent();
    }

    /**
     * Goal: Verify extraction for json (minimal metadata, native extension).
     * Rationale: json gem is a stdlib extraction with minimal fields.
     */
    @Test
    void gem_json_minimal() throws Exception {
        Path gem = GEMS_CORPUS.resolve("json-2.7.1.gem");
        assumeThat(Files.exists(gem)).isTrue();

        MetadataResult result = extractFromPackage(gem);

        assertThat(result.name()).hasValue("json");
        assertThat(result.version()).hasValue("2.7.1");
    }

    /**
     * Goal: Verify extraction for devise (runtime + dev deps).
     * Rationale: devise has both runtime (warden, bcrypt) and dev deps.
     */
    @Test
    void gem_devise_runtimeAndDevDeps() throws Exception {
        Path gem = GEMS_CORPUS.resolve("devise-4.9.3.gem");
        assumeThat(Files.exists(gem)).isTrue();

        MetadataResult result = extractFromPackage(gem);

        assertThat(result.name()).hasValue("devise");
        // Has runtime dep: warden
        assertThat(result.dependencies().stream()
                .filter(d -> d.name().equals("warden") && d.scope().orElse("").equals("runtime"))
                .findAny()).isPresent();
    }

    /**
     * Goal: Verify extraction for zeitwerk (Q2 summary used as description).
     * Rationale: Q2 — zeitwerk has a clean summary that should be used.
     */
    @Test
    void gem_zeitwerk_summaryAsDescription() throws Exception {
        Path gem = GEMS_CORPUS.resolve("zeitwerk-2.6.13.gem");
        assumeThat(Files.exists(gem)).isTrue();

        MetadataResult result = extractFromPackage(gem);

        assertThat(result.name()).hasValue("zeitwerk");
        assertThat(result.description()).hasValue("Efficient and thread-safe constant autoloader");
        assertThat(result.dependencies()).isEmpty();
    }

    /**
     * Goal: Verify extraction for activesupport (exact version deps).
     * Rationale: activesupport has many pinned dependencies.
     */
    @Test
    void gem_activesupport_manyDeps() throws Exception {
        Path gem = GEMS_CORPUS.resolve("activesupport-7.1.3.gem");
        assumeThat(Files.exists(gem)).isTrue();

        MetadataResult result = extractFromPackage(gem);

        assertThat(result.name()).hasValue("activesupport");
        assertThat(result.version()).hasValue("7.1.3");
        assertThat(result.dependencies()).isNotEmpty();
    }

    // --- Unit tests for isMetadataGz ---

    /**
     * Goal: Verify standard metadata.gz entry is recognized.
     * Rationale: All gems have a root-level metadata.gz entry.
     */
    @Test
    void isMetadataGz_standardEntry() {
        assertThat(RubygemsMetadataExtractor.isMetadataGz("metadata.gz")).isTrue();
    }

    /**
     * Goal: Verify non-metadata.gz entries are rejected.
     * Rationale: Only metadata.gz should match, not data.tar.gz or checksums.yaml.gz.
     */
    @Test
    void isMetadataGz_otherEntries_notMatched() {
        assertThat(RubygemsMetadataExtractor.isMetadataGz("data.tar.gz")).isFalse();
        assertThat(RubygemsMetadataExtractor.isMetadataGz("checksums.yaml.gz")).isFalse();
    }

    /**
     * Goal: Verify subdirectory metadata.gz is rejected.
     * Rationale: metadata.gz should be at root, not nested.
     */
    @Test
    void isMetadataGz_nested_notMatched() {
        assertThat(RubygemsMetadataExtractor.isMetadataGz("subdir/metadata.gz")).isFalse();
    }

    /**
     * Goal: Verify path traversal entries are rejected.
     * Rationale: Security — entries with ".." must be rejected.
     */
    @Test
    void isMetadataGz_pathTraversal_rejected() {
        assertThat(RubygemsMetadataExtractor.isMetadataGz("../metadata.gz")).isFalse();
    }

    // --- Unit tests for stripRubyYamlTags ---

    /**
     * Goal: Verify Ruby YAML tags are stripped from gemspec.
     * Rationale: Q1 — SnakeYAML SafeConstructor cannot handle !ruby/object tags.
     */
    @Test
    void stripRubyYamlTags_removesAllGemTags() {
        String input = "--- !ruby/object:Gem::Specification\nname: test\nversion: !ruby/object:Gem::Version\n  version: 1.0";
        String result = RubygemsMetadataExtractor.stripRubyYamlTags(input);

        assertThat(result).doesNotContain("!ruby/");
        assertThat(result).contains("name: test");
        assertThat(result).contains("version: 1.0");
    }

    /**
     * Goal: Verify stripRubyYamlTags is idempotent.
     * Rationale: Applying the strip twice should produce the same result.
     */
    @Test
    void stripRubyYamlTags_idempotent() {
        String input = "--- !ruby/object:Gem::Specification\nname: test";
        String once = RubygemsMetadataExtractor.stripRubyYamlTags(input);
        String twice = RubygemsMetadataExtractor.stripRubyYamlTags(once);

        assertThat(twice).isEqualTo(once);
    }

    /**
     * Goal: Verify stripRubyYamlTags preserves non-Ruby YAML.
     * Rationale: Plain YAML without Ruby tags should be unchanged.
     */
    @Test
    void stripRubyYamlTags_preservesPlainYaml() {
        String input = "---\nname: test\nversion: 1.0\ndescription: a test gem";
        String result = RubygemsMetadataExtractor.stripRubyYamlTags(input);

        assertThat(result).isEqualTo(input);
    }

    /**
     * Goal: Verify stripRubyYamlTags handles various Ruby tag formats.
     * Rationale: Q1 — tags include Gem::Dependency, Gem::Requirement, etc.
     */
    @Test
    void stripRubyYamlTags_handlesMultipleTagTypes() {
        String input = "dep: !ruby/object:Gem::Dependency\n  req: !ruby/object:Gem::Requirement\n    ver: !ruby/hash:Gem::StubSpecification";
        String result = RubygemsMetadataExtractor.stripRubyYamlTags(input);

        assertThat(result).doesNotContain("!ruby/");
    }

    /**
     * Goal: Verify stripRubyYamlTags handles empty string.
     * Rationale: Boundary case — empty input should return empty output.
     */
    @Test
    void stripRubyYamlTags_emptyString() {
        assertThat(RubygemsMetadataExtractor.stripRubyYamlTags("")).isEmpty();
    }

    // --- Unit tests for reconstructVersionConstraint ---

    /**
     * Goal: Verify tilde-arrow constraint reconstruction.
     * Rationale: Q4 — "~> 3.13.0" is the most common gem constraint format.
     */
    @Test
    void reconstructVersionConstraint_tildeArrow() {
        Map<String, Object> req = makeRequirement("~>", "3.13.0");
        String result = RubygemsMetadataExtractor.reconstructVersionConstraint(req);

        assertThat(result).isEqualTo("~> 3.13.0");
    }

    /**
     * Goal: Verify compound constraint reconstruction.
     * Rationale: Q4 — ">= 2.0, < 3.2" for version range constraints.
     */
    @Test
    void reconstructVersionConstraint_compound() {
        Map<String, Object> req = makeCompoundRequirement(
                List.of(">=", "2.0"),
                List.of("<", "3.2"));
        String result = RubygemsMetadataExtractor.reconstructVersionConstraint(req);

        assertThat(result).isEqualTo(">= 2.0, < 3.2");
    }

    /**
     * Goal: Verify default constraint ">= 0" maps to null.
     * Rationale: Q4 — the default Ruby requirement means "no constraint".
     */
    @Test
    void reconstructVersionConstraint_defaultIsNull() {
        Map<String, Object> req = makeRequirement(">=", "0");
        String result = RubygemsMetadataExtractor.reconstructVersionConstraint(req);

        assertThat(result).isNull();
    }

    /**
     * Goal: Verify exact version constraint reconstruction.
     * Rationale: Q4 — "= 7.1.3" for pinned dependencies like Rails sub-gems.
     */
    @Test
    void reconstructVersionConstraint_exact() {
        Map<String, Object> req = makeRequirement("=", "7.1.3");
        String result = RubygemsMetadataExtractor.reconstructVersionConstraint(req);

        assertThat(result).isEqualTo("= 7.1.3");
    }

    /**
     * Goal: Verify null requirement returns null.
     * Rationale: Boundary case — null input should safely return null.
     */
    @Test
    void reconstructVersionConstraint_null() {
        assertThat(RubygemsMetadataExtractor.reconstructVersionConstraint(null)).isNull();
    }

    // --- Unit tests for mapDependencyType ---

    /**
     * Goal: Verify :runtime maps to "runtime".
     * Rationale: Q3 — Ruby symbol :runtime is the runtime scope.
     */
    @Test
    void mapDependencyType_runtime() {
        assertThat(RubygemsMetadataExtractor.mapDependencyType(":runtime")).isEqualTo("runtime");
    }

    /**
     * Goal: Verify :development maps to "dev".
     * Rationale: Q3 — Ruby symbol :development is the dev scope.
     */
    @Test
    void mapDependencyType_development() {
        assertThat(RubygemsMetadataExtractor.mapDependencyType(":development")).isEqualTo("dev");
    }

    /**
     * Goal: Verify null type defaults to "runtime".
     * Rationale: Q3 — absent type should default to runtime.
     */
    @Test
    void mapDependencyType_nullDefaultsToRuntime() {
        assertThat(RubygemsMetadataExtractor.mapDependencyType(null)).isEqualTo("runtime");
    }

    // --- Unit tests for extractDescription ---

    /**
     * Goal: Verify summary is preferred over description.
     * Rationale: Q2 — summary (short) is preferred, matching PyPI pattern.
     */
    @Test
    void extractDescription_prefersSummary() {
        Map<String, Object> data = Map.of("summary", "Short summary", "description", "Long description text");
        String result = RubygemsMetadataExtractor.extractDescription(data);

        assertThat(result).isEqualTo("Short summary");
    }

    /**
     * Goal: Verify description is used when summary is empty.
     * Rationale: Q2 — fallback to description when summary is nil/empty.
     */
    @Test
    void extractDescription_fallsBackToDescription() {
        Map<String, Object> data = Map.of("description", "Long description text");
        String result = RubygemsMetadataExtractor.extractDescription(data);

        assertThat(result).isEqualTo("Long description text");
    }

    /**
     * Goal: Verify null when both summary and description are absent.
     * Rationale: Q2 — both fields absent means no description.
     */
    @Test
    void extractDescription_bothAbsent_returnsNull() {
        Map<String, Object> data = Map.of("name", "test");
        String result = RubygemsMetadataExtractor.extractDescription(data);

        assertThat(result).isNull();
    }

    /**
     * Goal: Verify empty summary triggers fallback.
     * Rationale: Q2 — empty string summary should fall through to description.
     */
    @Test
    void extractDescription_emptySummary_fallsBack() {
        Map<String, Object> data = Map.of("summary", "  ", "description", "Fallback desc");
        String result = RubygemsMetadataExtractor.extractDescription(data);

        assertThat(result).isEqualTo("Fallback desc");
    }

    // --- Unit tests for joinLicenses ---

    /**
     * Goal: Verify single license returns as-is.
     * Rationale: Q6 — single license should not have separator.
     */
    @Test
    void joinLicenses_single() {
        assertThat(RubygemsMetadataExtractor.joinLicenses(List.of("MIT"))).isEqualTo("MIT");
    }

    /**
     * Goal: Verify multiple licenses joined with " OR ".
     * Rationale: Q6 — multiple licenses form SPDX-like expression.
     */
    @Test
    void joinLicenses_multiple() {
        assertThat(RubygemsMetadataExtractor.joinLicenses(List.of("MIT", "Apache-2.0")))
                .isEqualTo("MIT OR Apache-2.0");
    }

    /**
     * Goal: Verify empty list returns null.
     * Rationale: Q6 — no licenses means null, not empty string.
     */
    @Test
    void joinLicenses_empty_returnsNull() {
        assertThat(RubygemsMetadataExtractor.joinLicenses(List.of())).isNull();
    }

    /**
     * Goal: Verify null input returns null.
     * Rationale: Q6 — null licenses list means null.
     */
    @Test
    void joinLicenses_null_returnsNull() {
        assertThat(RubygemsMetadataExtractor.joinLicenses(null)).isNull();
    }

    // --- Unit tests for extractVersion ---

    /**
     * Goal: Verify direct string version extraction.
     * Rationale: Some YAML may have version as a plain string after tag stripping.
     */
    @Test
    void extractVersion_directString() {
        assertThat(RubygemsMetadataExtractor.extractVersion("1.0.0")).isEqualTo("1.0.0");
    }

    /**
     * Goal: Verify Gem::Version wrapper map extraction.
     * Rationale: Stripped YAML typically has {version: "1.0.0"} maps.
     */
    @Test
    void extractVersion_mapWrapper() {
        Map<String, Object> wrapper = Map.of("version", "2.5.1");
        assertThat(RubygemsMetadataExtractor.extractVersion(wrapper)).isEqualTo("2.5.1");
    }

    /**
     * Goal: Verify null version input returns null.
     * Rationale: Boundary case — missing version field.
     */
    @Test
    void extractVersion_null() {
        assertThat(RubygemsMetadataExtractor.extractVersion(null)).isNull();
    }

    // --- Malformed/edge case tests ---

    /**
     * Goal: Verify malformed stream throws MetadataExtractionException.
     * Rationale: Corrupt archives should fail gracefully.
     */
    @Test
    void extractMetadataGz_malformedStream_throws() {
        ByteArrayInputStream badStream = new ByteArrayInputStream(new byte[]{0, 1, 2, 3});
        assertThatThrownBy(() ->
                RubygemsMetadataExtractor.extractMetadataGzFromGem(badStream, "bad.gem"))
                .isInstanceOf(Exception.class);
    }

    /**
     * Goal: Verify buildMetadataResult with minimal valid YAML.
     * Rationale: Minimal YAML with just name/version should parse successfully.
     */
    @Test
    void buildMetadataResult_minimalYaml() throws Exception {
        String yaml = "---\nname: test-gem\nversion:\n  version: 0.1.0\n";
        RubygemsMetadataExtractor.GemMetadataData data =
                new RubygemsMetadataExtractor.GemMetadataData(yaml);
        MetadataResult result = RubygemsMetadataExtractor.buildMetadataResult(data);

        assertThat(result.name()).hasValue("test-gem");
        assertThat(result.version()).hasValue("0.1.0");
        assertThat(result.dependencies()).isEmpty();
    }

    /**
     * Goal: Verify buildMetadataResult with empty YAML throws.
     * Rationale: Empty YAML should fail to parse.
     */
    @Test
    void buildMetadataResult_emptyYaml_throws() {
        RubygemsMetadataExtractor.GemMetadataData data =
                new RubygemsMetadataExtractor.GemMetadataData("");
        assertThatThrownBy(() -> RubygemsMetadataExtractor.buildMetadataResult(data))
                .isInstanceOf(Exception.class);
    }

    // --- Helpers ---

    private MetadataResult extractFromPackage(Path pkgPath) throws Exception {
        try (FileInputStream fis = new FileInputStream(pkgPath.toFile())) {
            RubygemsMetadataExtractor.GemMetadataData data =
                    RubygemsMetadataExtractor.extractMetadataGzFromGem(fis, pkgPath.getFileName().toString());
            return RubygemsMetadataExtractor.buildMetadataResult(data);
        }
    }

    @SuppressWarnings("unchecked")
    private static Map<String, Object> makeRequirement(String op, String version) {
        Map<String, Object> versionMap = Map.of("version", version);
        List<Object> pair = List.of(op, versionMap);
        return Map.of("requirements", List.of(pair));
    }

    @SuppressWarnings("unchecked")
    private static Map<String, Object> makeCompoundRequirement(List<String>... pairs) {
        List<Object> requirements = new java.util.ArrayList<>();
        for (List<String> pair : pairs) {
            Map<String, Object> versionMap = Map.of("version", pair.get(1));
            requirements.add(List.of(pair.get(0), versionMap));
        }
        return Map.of("requirements", requirements);
    }
}
