/* Copyright 2026 Spice Labs, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License. */

package io.spicelabs.annatto.luarocks;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import io.spicelabs.annatto.AnnattoException.MalformedPackageException;
import io.spicelabs.annatto.common.MetadataResult;
import io.spicelabs.annatto.common.ParsedDependency;
import io.spicelabs.annatto.testutil.SourceOfTruth;
import io.spicelabs.annatto.testutil.TestCorpusDownloader;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.stream.Stream;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.assertj.core.api.Assumptions.assumeThat;

/**
 * Tests for {@link LuarocksMetadataExtractor} comparing extraction results against
 * source-of-truth expected values produced by native Lua tools in Docker.
 *
 * <p>All test packages are real LuaRocks packages downloaded from luarocks.org.
 * Expected values were generated by running Docker containers with Lua that
 * execute rockspec files in a sandbox and extract metadata.</p>
 *
 * <p>Package files (.src.rock, .rockspec) are in {@code test-corpus/luarocks/} (gitignored).
 * Source-of-truth expected JSON files are in {@code src/test/resources/luarocks/} (git-tracked).</p>
 *
 * <p>Covers {@link LuarocksQuirks} Q1 (Lua code parsing), Q2 (version revision),
 * Q3 (external deps filtered), Q4 (dependency string format), Q5 (description fallback),
 * Q6 (publisher from maintainer), Q7 (no publishedAt), Q8 (PURL lowercasing).</p>
 */
class LuarocksMetadataExtractorTest {

    private static final Path LUAROCKS_CORPUS = TestCorpusDownloader.corpusDir("luarocks");
    private static final Path LUAROCKS_EXPECTED = TestCorpusDownloader.expectedDir("luarocks");

    @BeforeAll
    static void ensureTestPackagesExist() {
        assumeThat(Files.isDirectory(LUAROCKS_CORPUS))
                .as("luarocks test corpus directory must exist with real packages")
                .isTrue();
    }

    // --- Parameterized source-of-truth comparison ---

    static Stream<Arguments> realPackages() throws IOException {
        if (!Files.isDirectory(LUAROCKS_CORPUS)) {
            return Stream.empty();
        }
        return Files.list(LUAROCKS_CORPUS)
                .filter(p -> {
                    String name = p.toString();
                    return name.endsWith(".src.rock") || name.endsWith(".all.rock")
                            || name.endsWith(".rockspec");
                })
                .sorted()
                .map(pkg -> {
                    Path expected = SourceOfTruth.expectedPathFor(pkg, LUAROCKS_EXPECTED);
                    String label = pkg.getFileName().toString();
                    return Arguments.of(label, pkg, expected);
                });
    }

    /**
     * Goal: Verify extracted name matches source-of-truth for every real package.
     * Rationale: Name is the most fundamental field; must match native Lua extraction (Q1).
     */
    @ParameterizedTest(name = "name: {0}")
    @MethodSource("realPackages")
    void extractName_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath)
            throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        assertThat(result.name()).isEqualTo(SourceOfTruth.getString(expected, "name"));
    }

    /**
     * Goal: Verify extracted simpleName matches source-of-truth for every real package.
     * Rationale: For LuaRocks, simpleName == name (no vendor concept).
     */
    @ParameterizedTest(name = "simpleName: {0}")
    @MethodSource("realPackages")
    void extractSimpleName_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath)
            throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        assertThat(result.simpleName()).isEqualTo(SourceOfTruth.getString(expected, "simpleName"));
    }

    /**
     * Goal: Verify extracted version matches source-of-truth for every real package (Q2).
     * Rationale: Version includes revision suffix; must be exact match with native tools.
     */
    @ParameterizedTest(name = "version: {0}")
    @MethodSource("realPackages")
    void extractVersion_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath)
            throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        assertThat(result.version()).isEqualTo(SourceOfTruth.getString(expected, "version"));
    }

    /**
     * Goal: Verify extracted description matches source-of-truth for every real package (Q5).
     * Rationale: Description uses summary preferred, detailed fallback.
     */
    @ParameterizedTest(name = "description: {0}")
    @MethodSource("realPackages")
    void extractDescription_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath)
            throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        // Floor test
        Optional<String> expectedDesc = SourceOfTruth.getString(expected, "description");
        if (expectedDesc.isPresent() && !expectedDesc.get().isEmpty() && !"unknown".equalsIgnoreCase(expectedDesc.get())) {
            assertThat(result.description()).as("description for %s", label).isEqualTo(expectedDesc);
        }
    }

    /**
     * Goal: Verify extracted license matches source-of-truth for every real package.
     * Rationale: License from description table must match native extraction.
     */
    @ParameterizedTest(name = "license: {0}")
    @MethodSource("realPackages")
    void extractLicense_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath)
            throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        // Floor test
        Optional<String> expectedLicense = SourceOfTruth.getString(expected, "license");
        if (expectedLicense.isPresent() && !expectedLicense.get().isEmpty() && !"unknown".equalsIgnoreCase(expectedLicense.get())) {
            assertThat(result.license()).as("license for %s", label).isEqualTo(expectedLicense);
        }
    }

    /**
     * Goal: Verify extracted publisher matches source-of-truth for every real package (Q6).
     * Rationale: Publisher from description.maintainer; null if absent.
     */
    @ParameterizedTest(name = "publisher: {0}")
    @MethodSource("realPackages")
    void extractPublisher_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath)
            throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        // Floor test
        Optional<String> expectedPublisher = SourceOfTruth.getString(expected, "publisher");
        if (expectedPublisher.isPresent() && !expectedPublisher.get().isEmpty() && !"unknown".equalsIgnoreCase(expectedPublisher.get())) {
            assertThat(result.publisher()).as("publisher for %s", label).isEqualTo(expectedPublisher);
        }
    }

    /**
     * Goal: Verify publishedAt is always null for every real package (Q7).
     * Rationale: Rockspec files have no timestamp field.
     */
    @ParameterizedTest(name = "publishedAt: {0}")
    @MethodSource("realPackages")
    void extractPublishedAt_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath)
            throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        assertThat(result.publishedAt()).isEmpty();
    }

    /**
     * Goal: Verify extracted dependency count matches source-of-truth for every real package.
     * Rationale: Dependency count validates scope-based extraction (Q3, Q4).
     */
    @ParameterizedTest(name = "depCount: {0}")
    @MethodSource("realPackages")
    void extractDependencyCount_matchesSourceOfTruth(String label, Path pkgPath,
            Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        List<DepTuple> expectedDeps = loadExpectedDeps(expected);
        assertThat(result.dependencies()).hasSize(expectedDeps.size());
    }

    /**
     * Goal: Verify extracted dependencies match source-of-truth for every real package (Q4).
     * Rationale: Dependencies are parsed from Lua string format; must match native extraction.
     */
    @ParameterizedTest(name = "deps: {0}")
    @MethodSource("realPackages")
    void extractDependencies_matchSourceOfTruth(String label, Path pkgPath, Path expectedPath)
            throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        List<DepTuple> expectedDeps = loadExpectedDeps(expected);
        List<DepTuple> actualDeps = result.dependencies().stream()
                .map(d -> new DepTuple(d.name(),
                        d.versionConstraint().orElse(null),
                        d.scope().orElse(null)))
                .toList();
        assertThat(actualDeps).isEqualTo(expectedDeps);
    }

    // --- Named package tests ---

    /**
     * Goal: Verify luasocket (popular, C binding) extracts correctly.
     * Rationale: LuaSocket is a widely-used package; platform dependency on lua is filtered.
     */
    @Test
    void package_luasocket_basicExtraction() throws Exception {
        MetadataResult result = extractByName("luasocket-3.1.0-1.src.rock");
        assertThat(result.name()).hasValue("LuaSocket");
        assertThat(result.version()).hasValue("3.1.0-1");
        assertThat(result.license()).hasValue("MIT");
        // Platform dependency on "lua" is filtered out (not a real package dependency)
    }

    /**
     * Goal: Verify luafilesystem (C binding) extracts correctly.
     * Rationale: LuaFileSystem has a mixed-case package name.
     */
    @Test
    void package_luafilesystem_cBinding() throws Exception {
        MetadataResult result = extractByName("luafilesystem-1.8.0-1.src.rock");
        assertThat(result.name()).hasValue("LuaFileSystem");
        assertThat(result.version()).hasValue("1.8.0-1");
    }

    /**
     * Goal: Verify penlight (many deps) extracts correctly.
     * Rationale: Penlight has multiple dependencies and a publisher.
     */
    @Test
    void package_penlight_manyDeps() throws Exception {
        MetadataResult result = extractByName("penlight-1.14.0-2.src.rock");
        assertThat(result.name()).hasValue("penlight");
        assertThat(result.publisher()).isPresent();
        assertThat(result.dependencies()).isNotEmpty();
    }

    /**
     * Goal: Verify busted (test framework, many deps) extracts correctly.
     * Rationale: Busted has many runtime dependencies, testing broad parsing.
     */
    @Test
    void package_busted_testFramework() throws Exception {
        MetadataResult result = extractByName("busted-2.2.0-1.src.rock");
        assertThat(result.name()).hasValue("busted");
        assertThat(result.dependencies().size()).isGreaterThanOrEqualTo(5);
    }

    /**
     * Goal: Verify inspect (zero external deps) extracts correctly.
     * Rationale: A minimal package with few or no dependencies.
     */
    @Test
    void package_inspect_zeroDeps() throws Exception {
        MetadataResult result = extractByName("inspect-3.1.1-0.src.rock");
        assertThat(result.name()).hasValue("inspect");
    }

    /**
     * Goal: Verify middleclass (OOP, zero deps) extracts correctly.
     * Rationale: A simple package with no LuaRocks dependencies.
     */
    @Test
    void package_middleclass_zeroDeps() throws Exception {
        MetadataResult result = extractByName("middleclass-3.0-1.src.rock");
        assertThat(result.name()).hasValue("middleclass");
    }

    /**
     * Goal: Verify luasec has external dependencies filtered out (Q3).
     * Rationale: LuaSec requires OpenSSL (external C library); these must not appear in deps.
     */
    @Test
    void package_luasec_externalDeps() throws Exception {
        MetadataResult result = extractByName("luasec-1.3.2-1.src.rock");
        assertThat(result.name()).hasValue("LuaSec");
        // external_dependencies (OPENSSL) should not be in the dependency list
        assertThat(result.dependencies().stream().map(ParsedDependency::name))
                .doesNotContain("OPENSSL", "openssl");
    }

    /**
     * Goal: Verify dkjson (pure Lua JSON) extracts correctly.
     * Rationale: Pure Lua package with no C bindings.
     */
    @Test
    void package_dkjson_pureLua() throws Exception {
        MetadataResult result = extractByName("dkjson-2.8-1.src.rock");
        assertThat(result.name()).hasValue("dkjson");
        assertThat(result.license()).isPresent();
    }

    /**
     * Goal: Verify lapis (web framework, many deps) extracts correctly.
     * Rationale: Lapis has complex dependencies including version constraints.
     */
    @Test
    void package_lapis_manyDeps() throws Exception {
        MetadataResult result = extractByName("lapis-1.16.0-1.src.rock");
        assertThat(result.name()).hasValue("lapis");
        assertThat(result.dependencies()).isNotEmpty();
    }

    /**
     * Goal: Verify luacheck (linter, mixed deps) extracts correctly.
     * Rationale: Luacheck has multiple runtime dependencies.
     */
    @Test
    void package_luacheck_mixedDeps() throws Exception {
        MetadataResult result = extractByName("luacheck-1.2.0-1.src.rock");
        assertThat(result.name()).hasValue("luacheck");
        assertThat(result.dependencies()).isNotEmpty();
    }

    // --- Unit tests ---

    /**
     * Goal: Verify extractFromRock finds rockspec in ZIP archive.
     * Rationale: Q1 - .src.rock is a ZIP; rockspec must be found at root level.
     */
    @Test
    void extractFromRock_findsRockspec() throws Exception {
        byte[] zip = createTestRock("test-1.0-1.rockspec",
                "package = \"test\"\nversion = \"1.0-1\"");
        var data = LuarocksMetadataExtractor.extractFromRock(
                new ByteArrayInputStream(zip), "test-1.0-1.src.rock");
        assertThat(data.rawText()).contains("package = \"test\"");
    }

    /**
     * Goal: Verify extractFromRock throws when no rockspec in archive.
     * Rationale: A .rock without a .rockspec is malformed.
     */
    @Test
    void extractFromRock_noRockspec_throws() {
        byte[] zip = createTestZipWithEntry("readme.txt", "hello");
        assertThatThrownBy(() -> LuarocksMetadataExtractor.extractFromRock(
                new ByteArrayInputStream(zip), "bad.src.rock"))
                .isInstanceOf(MalformedPackageException.class);
    }

    /**
     * Goal: Verify extractFromRockspec reads Lua text directly.
     * Rationale: Standalone .rockspec files are read as plain text.
     */
    @Test
    void extractFromRockspec_directLua() throws Exception {
        String lua = "package = \"test\"\nversion = \"1.0-1\"";
        MetadataResult result = LuarocksMetadataExtractor.extract(
                new ByteArrayInputStream(lua.getBytes(StandardCharsets.UTF_8)),
                "test-1.0-1.rockspec");
        assertThat(result.name()).hasValue("test");
        assertThat(result.version()).hasValue("1.0-1");
    }

    // --- parseDependencyString tests ---

    /**
     * Goal: Verify dependency with name only (no version constraint).
     * Rationale: Q4 - Some dependencies have no version constraint.
     */
    @Test
    void parseDependencyString_nameOnly() {
        ParsedDependency dep = LuarocksMetadataExtractor.parseDependencyString(
                "luasocket", "runtime");
        assertThat(dep.name()).isEqualTo("luasocket");
        assertThat(dep.versionConstraint()).isEmpty();
        assertThat(dep.scope()).hasValue("runtime");
    }

    /**
     * Goal: Verify dependency with name and version constraint.
     * Rationale: Q4 - Standard format: "name op version".
     */
    @Test
    void parseDependencyString_nameAndVersion() {
        ParsedDependency dep = LuarocksMetadataExtractor.parseDependencyString(
                "lua >= 5.1", "runtime");
        assertThat(dep.name()).isEqualTo("lua");
        assertThat(dep.versionConstraint()).hasValue(">= 5.1");
    }

    /**
     * Goal: Verify dependency with multiple version constraints.
     * Rationale: Q4 - Some deps have compound constraints like ">= 5.1, < 5.4".
     */
    @Test
    void parseDependencyString_multipleConstraints() {
        ParsedDependency dep = LuarocksMetadataExtractor.parseDependencyString(
                "lua >= 5.1, < 5.4", "runtime");
        assertThat(dep.name()).isEqualTo("lua");
        assertThat(dep.versionConstraint()).hasValue(">= 5.1, < 5.4");
    }

    /**
     * Goal: Verify dependency with pessimistic version operator.
     * Rationale: Q4 - LuaRocks supports ~> (pessimistic) operator.
     */
    @Test
    void parseDependencyString_pessimisticOp() {
        ParsedDependency dep = LuarocksMetadataExtractor.parseDependencyString(
                "penlight ~> 1.3", "runtime");
        assertThat(dep.name()).isEqualTo("penlight");
        assertThat(dep.versionConstraint()).hasValue("~> 1.3");
    }

    /**
     * Goal: Verify dependency with exact version.
     * Rationale: Q4 - Exact versions use = operator.
     */
    @Test
    void parseDependencyString_exactVersion() {
        ParsedDependency dep = LuarocksMetadataExtractor.parseDependencyString(
                "lua_cliargs = 3.0", "runtime");
        assertThat(dep.name()).isEqualTo("lua_cliargs");
        assertThat(dep.versionConstraint()).hasValue("= 3.0");
    }

    // --- Description extraction tests ---

    /**
     * Goal: Verify description prefers summary field (Q5).
     * Rationale: When both summary and detailed are present, summary takes precedence.
     */
    @Test
    void extractDescription_summaryPreferred() throws Exception {
        String lua = "package = \"test\"\nversion = \"1.0-1\"\n"
                + "description = {summary = \"Short\", detailed = \"Long detailed text\"}";
        MetadataResult result = LuarocksMetadataExtractor.extract(
                new ByteArrayInputStream(lua.getBytes(StandardCharsets.UTF_8)),
                "test-1.0-1.rockspec");
        assertThat(result.description()).hasValue("Short");
    }

    /**
     * Goal: Verify description falls back to detailed field (Q5).
     * Rationale: When only detailed is present, it's used as description.
     */
    @Test
    void extractDescription_detailedFallback() throws Exception {
        String lua = "package = \"test\"\nversion = \"1.0-1\"\n"
                + "description = {detailed = \"Long text\"}";
        MetadataResult result = LuarocksMetadataExtractor.extract(
                new ByteArrayInputStream(lua.getBytes(StandardCharsets.UTF_8)),
                "test-1.0-1.rockspec");
        assertThat(result.description()).hasValue("Long text");
    }

    /**
     * Goal: Verify description is empty when both fields are absent (Q5).
     * Rationale: No description data means empty Optional.
     */
    @Test
    void extractDescription_bothAbsent() throws Exception {
        String lua = "package = \"test\"\nversion = \"1.0-1\"\n"
                + "description = {homepage = \"https://example.com\"}";
        MetadataResult result = LuarocksMetadataExtractor.extract(
                new ByteArrayInputStream(lua.getBytes(StandardCharsets.UTF_8)),
                "test-1.0-1.rockspec");
        assertThat(result.description()).isEmpty();
    }

    // --- Publisher extraction tests ---

    /**
     * Goal: Verify publisher comes from description.maintainer (Q6).
     * Rationale: Maintainer is the publisher source for LuaRocks.
     */
    @Test
    void extractPublisher_fromMaintainer() throws Exception {
        String lua = "package = \"test\"\nversion = \"1.0-1\"\n"
                + "description = {maintainer = \"alice@example.com\"}";
        MetadataResult result = LuarocksMetadataExtractor.extract(
                new ByteArrayInputStream(lua.getBytes(StandardCharsets.UTF_8)),
                "test-1.0-1.rockspec");
        assertThat(result.publisher()).hasValue("alice@example.com");
    }

    /**
     * Goal: Verify publisher is empty when maintainer is absent (Q6).
     * Rationale: No maintainer means no publisher.
     */
    @Test
    void extractPublisher_absent() throws Exception {
        String lua = "package = \"test\"\nversion = \"1.0-1\"\n"
                + "description = {summary = \"A lib\"}";
        MetadataResult result = LuarocksMetadataExtractor.extract(
                new ByteArrayInputStream(lua.getBytes(StandardCharsets.UTF_8)),
                "test-1.0-1.rockspec");
        assertThat(result.publisher()).isEmpty();
    }

    // --- License extraction tests ---

    /**
     * Goal: Verify license is extracted from description table.
     * Rationale: License is a common field in rockspecs.
     */
    @Test
    void extractLicense_simple() throws Exception {
        String lua = "package = \"test\"\nversion = \"1.0-1\"\n"
                + "description = {license = \"MIT\"}";
        MetadataResult result = LuarocksMetadataExtractor.extract(
                new ByteArrayInputStream(lua.getBytes(StandardCharsets.UTF_8)),
                "test-1.0-1.rockspec");
        assertThat(result.license()).hasValue("MIT");
    }

    /**
     * Goal: Verify license is empty when not present.
     * Rationale: Not all rockspecs declare a license.
     */
    @Test
    void extractLicense_absent() throws Exception {
        String lua = "package = \"test\"\nversion = \"1.0-1\"";
        MetadataResult result = LuarocksMetadataExtractor.extract(
                new ByteArrayInputStream(lua.getBytes(StandardCharsets.UTF_8)),
                "test-1.0-1.rockspec");
        assertThat(result.license()).isEmpty();
    }

    // --- Other tests ---

    /**
     * Goal: Verify publishedAt is always null (Q7).
     * Rationale: Rockspec files have no timestamp field.
     */
    @Test
    void buildMetadataResult_publishedAtAlwaysNull() throws Exception {
        String lua = "package = \"test\"\nversion = \"1.0-1\"";
        MetadataResult result = LuarocksMetadataExtractor.extract(
                new ByteArrayInputStream(lua.getBytes(StandardCharsets.UTF_8)),
                "test-1.0-1.rockspec");
        assertThat(result.publishedAt()).isEmpty();
    }

    /**
     * Goal: Verify corrupt Lua doesn't throw, returns result with empty fields.
     * Rationale: Invalid Lua should be handled gracefully by the evaluator.
     */
    @Test
    void buildMetadataResult_corruptLua() throws Exception {
        String lua = "{{{{???}}}}";
        // The evaluator may partially parse or return empty map — either way, no exception
        MetadataResult result = LuarocksMetadataExtractor.extract(
                new ByteArrayInputStream(lua.getBytes(StandardCharsets.UTF_8)),
                "corrupt.rockspec");
        assertThat(result.name()).isEmpty();
    }

    /**
     * Goal: Verify external_dependencies are not included in deps (Q3).
     * Rationale: C library dependencies are not LuaRocks packages.
     */
    @Test
    void extractDependencies_externalDepsFiltered() throws Exception {
        String lua = "package = \"test\"\nversion = \"1.0-1\"\n"
                + "dependencies = {\"luasocket >= 3.0\"}\n"
                + "external_dependencies = {OPENSSL = {library = \"ssl\"}}";
        MetadataResult result = LuarocksMetadataExtractor.extract(
                new ByteArrayInputStream(lua.getBytes(StandardCharsets.UTF_8)),
                "test-1.0-1.rockspec");
        assertThat(result.dependencies()).hasSize(1);
        assertThat(result.dependencies().get(0).name()).isEqualTo("luasocket");
    }

    /**
     * Goal: Verify build_dependencies get scope "build".
     * Rationale: Q4 - build_dependencies are scoped differently from runtime.
     */
    @Test
    void extractDependencies_buildDeps() throws Exception {
        String lua = "package = \"test\"\nversion = \"1.0-1\"\n"
                + "build_dependencies = {\"luacov\"}";
        MetadataResult result = LuarocksMetadataExtractor.extract(
                new ByteArrayInputStream(lua.getBytes(StandardCharsets.UTF_8)),
                "test-1.0-1.rockspec");
        assertThat(result.dependencies()).hasSize(1);
        assertThat(result.dependencies().get(0).scope()).hasValue("build");
    }

    /**
     * Goal: Verify test_dependencies get scope "test".
     * Rationale: Q4 - test_dependencies are scoped differently from runtime.
     */
    @Test
    void extractDependencies_testDeps() throws Exception {
        String lua = "package = \"test\"\nversion = \"1.0-1\"\n"
                + "test_dependencies = {\"busted\"}";
        MetadataResult result = LuarocksMetadataExtractor.extract(
                new ByteArrayInputStream(lua.getBytes(StandardCharsets.UTF_8)),
                "test-1.0-1.rockspec");
        assertThat(result.dependencies()).hasSize(1);
        assertThat(result.dependencies().get(0).scope()).hasValue("test");
    }

    // --- Helpers ---

    private MetadataResult extractFromPackage(Path pkgPath) throws Exception {
        try (FileInputStream fis = new FileInputStream(pkgPath.toFile())) {
            return LuarocksMetadataExtractor.extract(fis, pkgPath.getFileName().toString());
        }
    }

    private MetadataResult extractByName(String filename) throws Exception {
        Path pkg = LUAROCKS_CORPUS.resolve(filename);
        assumeThat(Files.exists(pkg)).as("Package file must exist: " + filename).isTrue();
        return extractFromPackage(pkg);
    }

    private static byte[] createTestRock(String rockspecName, String rockspecContent) {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        try (ZipOutputStream zos = new ZipOutputStream(baos)) {
            zos.putNextEntry(new ZipEntry(rockspecName));
            zos.write(rockspecContent.getBytes(StandardCharsets.UTF_8));
            zos.closeEntry();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        return baos.toByteArray();
    }

    private static byte[] createTestZipWithEntry(String entryName, String content) {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        try (ZipOutputStream zos = new ZipOutputStream(baos)) {
            zos.putNextEntry(new ZipEntry(entryName));
            zos.write(content.getBytes(StandardCharsets.UTF_8));
            zos.closeEntry();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        return baos.toByteArray();
    }

    record DepTuple(String name, String versionConstraint, String scope) {
    }

    private static List<DepTuple> loadExpectedDeps(JsonObject expected) {
        List<DepTuple> deps = new ArrayList<>();
        if (!expected.has("dependencies") || expected.get("dependencies").isJsonNull()) {
            return deps;
        }
        JsonArray depsArray = expected.getAsJsonArray("dependencies");
        for (JsonElement elem : depsArray) {
            JsonObject depObj = elem.getAsJsonObject();
            String name = depObj.get("name").getAsString();
            String vc = depObj.has("versionConstraint") && !depObj.get("versionConstraint").isJsonNull()
                    ? depObj.get("versionConstraint").getAsString() : null;
            String scope = depObj.has("scope") && !depObj.get("scope").isJsonNull()
                    ? depObj.get("scope").getAsString() : null;
            deps.add(new DepTuple(name, vc, scope));
        }
        return deps;
    }
}
