/* Copyright 2026 Spice Labs, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License. */

package io.spicelabs.annatto.conda;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import io.spicelabs.annatto.AnnattoException.MalformedPackageException;
import io.spicelabs.annatto.common.MetadataResult;
import io.spicelabs.annatto.common.ParsedDependency;
import io.spicelabs.annatto.testutil.SourceOfTruth;
import io.spicelabs.annatto.testutil.TestCorpusDownloader;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.io.ByteArrayInputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Optional;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.assertj.core.api.Assumptions.assumeThat;

/**
 * Tests for {@link CondaMetadataExtractor} comparing extraction results against
 * source-of-truth expected values produced by native Python tools in Docker.
 *
 * <p>All test packages are real conda packages downloaded from conda-forge.
 * Expected values were generated by running Docker containers with Python
 * that parse info/index.json and info/about.json from each archive.</p>
 *
 * <p>Package files (.conda, .tar.bz2) are in {@code test-corpus/conda/} (gitignored).
 * Source-of-truth expected JSON files are in {@code src/test/resources/conda/} (git-tracked).</p>
 *
 * <p>Covers {@link CondaQuirks} Q1 (two formats), Q5 (constrains ignored),
 * Q6 (match spec deps), Q7 (description from about.json), Q8 (timestamp millis).</p>
 */
class CondaMetadataExtractorTest {

    private static final Path CONDA_CORPUS = TestCorpusDownloader.corpusDir("conda");
    private static final Path CONDA_EXPECTED = TestCorpusDownloader.expectedDir("conda");
    private static final Gson GSON = new Gson();

    @BeforeAll
    static void ensureTestPackagesExist() {
        assumeThat(Files.isDirectory(CONDA_CORPUS))
                .as("conda test corpus directory must exist with real packages")
                .isTrue();
    }

    // --- Parameterized source-of-truth comparison ---

    static Stream<Arguments> realPackages() throws IOException {
        if (!Files.isDirectory(CONDA_CORPUS)) {
            return Stream.empty();
        }
        return Files.list(CONDA_CORPUS)
                .filter(p -> p.toString().endsWith(".conda") || p.toString().endsWith(".tar.bz2"))
                .sorted()
                .map(pkg -> {
                    Path expected = SourceOfTruth.expectedPathFor(pkg, CONDA_EXPECTED);
                    String label = pkg.getFileName().toString();
                    return Arguments.of(label, pkg, expected);
                });
    }

    /**
     * Goal: Verify extracted name matches source-of-truth for every real package.
     * Rationale: Name is the most fundamental field; must be exact for all packages (Q1).
     */
    @ParameterizedTest(name = "name: {0}")
    @MethodSource("realPackages")
    void extractName_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        assertThat(result.name()).isEqualTo(SourceOfTruth.getString(expected, "name"));
    }

    /**
     * Goal: Verify extracted simpleName matches source-of-truth.
     * Rationale: For conda, simpleName equals name (no vendor concept).
     */
    @ParameterizedTest(name = "simpleName: {0}")
    @MethodSource("realPackages")
    void extractSimpleName_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        assertThat(result.simpleName()).isEqualTo(SourceOfTruth.getString(expected, "simpleName"));
    }

    /**
     * Goal: Verify extracted version matches source-of-truth.
     * Rationale: Version must match exactly from index.json.
     */
    @ParameterizedTest(name = "version: {0}")
    @MethodSource("realPackages")
    void extractVersion_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        assertThat(result.version()).isEqualTo(SourceOfTruth.getString(expected, "version"));
    }

    /**
     * Goal: Verify extracted description matches source-of-truth.
     * Rationale: Q7 - Description from about.json (summary preferred), null if absent.
     */
    @ParameterizedTest(name = "description: {0}")
    @MethodSource("realPackages")
    void extractDescription_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        // Floor test
        Optional<String> expectedDesc = SourceOfTruth.getString(expected, "description");
        if (expectedDesc.isPresent() && !expectedDesc.get().isEmpty() && !"unknown".equalsIgnoreCase(expectedDesc.get())) {
            assertThat(result.description()).as("description for %s", label).isEqualTo(expectedDesc);
        }
    }

    /**
     * Goal: Verify extracted license matches source-of-truth.
     * Rationale: License comes from index.json, may be null.
     */
    @ParameterizedTest(name = "license: {0}")
    @MethodSource("realPackages")
    void extractLicense_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        // Floor test
        Optional<String> expectedLicense = SourceOfTruth.getString(expected, "license");
        if (expectedLicense.isPresent() && !expectedLicense.get().isEmpty() && !"unknown".equalsIgnoreCase(expectedLicense.get())) {
            assertThat(result.license()).as("license for %s", label).isEqualTo(expectedLicense);
        }
    }

    /**
     * Goal: Verify publisher is always null.
     * Rationale: Q2 - No author field in conda metadata; publisher always null.
     */
    @ParameterizedTest(name = "publisher: {0}")
    @MethodSource("realPackages")
    void extractPublisher_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        assertThat(result.publisher()).isEmpty();
    }

    /**
     * Goal: Verify extracted publishedAt matches source-of-truth.
     * Rationale: Q8 - Timestamp in millis converted to ISO 8601, null if absent.
     */
    @ParameterizedTest(name = "publishedAt: {0}")
    @MethodSource("realPackages")
    void extractPublishedAt_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        assertThat(result.publishedAt()).isEqualTo(SourceOfTruth.getString(expected, "publishedAt"));
    }

    /**
     * Goal: Verify extracted dependency count matches source-of-truth.
     * Rationale: Q6 - All depends match specs must be parsed.
     */
    @ParameterizedTest(name = "depCount: {0}")
    @MethodSource("realPackages")
    void extractDependencyCount_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath)
            throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        int expectedCount = expected.getAsJsonArray("dependencies").size();
        assertThat(result.dependencies()).as("dependency count for %s", label).hasSize(expectedCount);
    }

    /**
     * Goal: Verify all extracted dependency names, versions, and scopes match source-of-truth.
     * Rationale: Q6 - Match spec parsing must produce identical deps.
     */
    @ParameterizedTest(name = "deps: {0}")
    @MethodSource("realPackages")
    void extractDependencies_matchSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        JsonArray expectedDeps = expected.getAsJsonArray("dependencies");
        List<DepTuple> expectedTuples = new java.util.ArrayList<>();
        for (var elem : expectedDeps) {
            JsonObject depObj = elem.getAsJsonObject();
            String name = depObj.get("name").getAsString();
            String vc = depObj.get("versionConstraint").isJsonNull() ? null
                    : depObj.get("versionConstraint").getAsString();
            String scope = depObj.get("scope").getAsString();
            expectedTuples.add(new DepTuple(name, vc, scope));
        }

        List<DepTuple> actualTuples = result.dependencies().stream()
                .map(d -> new DepTuple(d.name(), d.versionConstraint().orElse(null), d.scope().orElse(null)))
                .toList();

        assertThat(actualTuples)
                .as("dependencies for %s (must contain all ground truth)", label)
                .containsAll(expectedTuples);
    }

    /**
     * Goal: Verify extracted build string matches source-of-truth.
     * Rationale: Q3 - Build string is a PURL qualifier.
     */
    @ParameterizedTest(name = "build: {0}")
    @MethodSource("realPackages")
    void extractBuild_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        CondaMetadataExtractor.CondaArchiveData data = extractArchiveData(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        Optional<String> actualBuild = CondaMetadataExtractor.extractBuild(data);
        assertThat(actualBuild).isEqualTo(SourceOfTruth.getString(expected, "build"));
    }

    /**
     * Goal: Verify extracted subdir matches source-of-truth.
     * Rationale: Q4 - Subdir is a PURL qualifier.
     */
    @ParameterizedTest(name = "subdir: {0}")
    @MethodSource("realPackages")
    void extractSubdir_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        CondaMetadataExtractor.CondaArchiveData data = extractArchiveData(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        Optional<String> actualSubdir = CondaMetadataExtractor.extractSubdir(data);
        assertThat(actualSubdir).isEqualTo(SourceOfTruth.getString(expected, "subdir"));
    }

    // --- Named package tests ---

    /**
     * Goal: Verify extraction for numpy .conda (many deps, scientific).
     * Rationale: Q1 - .conda format with multiple dependencies.
     */
    @Test
    void package_numpy_conda_manyDeps() throws Exception {
        Path pkg = findPackage("numpy-1.26.4-py310hb13e2d6_0.conda");
        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.name()).hasValue("numpy");
        assertThat(result.simpleName()).hasValue("numpy");
        assertThat(result.version()).hasValue("1.26.4");
        assertThat(result.license()).hasValue("BSD-3-Clause");
        assertThat(result.publisher()).isEmpty();
        assertThat(result.dependencies()).isNotEmpty();
        assertThat(result.dependencies().stream().map(ParsedDependency::name))
                .contains("python");
    }

    /**
     * Goal: Verify extraction for six .conda (zero deps).
     * Rationale: Boundary case — minimal noarch package.
     */
    @Test
    void package_six_conda_zeroDeps() throws Exception {
        Path pkg = findPackage("six-1.16.0-pyhd8ed1ab_1.conda");
        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.name()).hasValue("six");
        assertThat(result.version()).hasValue("1.16.0");
        assertThat(result.license()).hasValue("MIT");
    }

    /**
     * Goal: Verify extraction for zlib .conda (C library, no Python deps).
     * Rationale: C libraries have different dep patterns; no python dependency.
     */
    @Test
    void package_zlib_conda_cLibrary() throws Exception {
        Path pkg = findPackage("zlib-1.3.1-h4ab18f5_1.conda");
        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.name()).hasValue("zlib");
        assertThat(result.version()).hasValue("1.3.1");
        assertThat(result.dependencies().stream().map(ParsedDependency::name))
                .doesNotContain("python");
    }

    /**
     * Goal: Verify extraction for requests .tar.bz2 (moderate deps, legacy format).
     * Rationale: Q1 - .tar.bz2 format with moderate dependencies.
     */
    @Test
    void package_requests_tarBz2_moderateDeps() throws Exception {
        Path pkg = findPackage("requests-2.26.0-pyhd8ed1ab_0.tar.bz2");
        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.name()).hasValue("requests");
        assertThat(result.version()).hasValue("2.26.0");
        assertThat(result.dependencies()).isNotEmpty();
        assertThat(result.dependencies().stream().map(ParsedDependency::name))
                .contains("urllib3");
    }

    /**
     * Goal: Verify extraction for python interpreter .tar.bz2 (many deps).
     * Rationale: The python interpreter package itself, many deps, legacy format.
     */
    @Test
    void package_python_tarBz2_manyDeps() throws Exception {
        Path pkg = findPackage("python-3.9.7-h49503c6_0_cpython.tar.bz2");
        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.name()).hasValue("python");
        assertThat(result.version()).hasValue("3.9.7");
        assertThat(result.dependencies()).isNotEmpty();
    }

    /**
     * Goal: Verify extraction for certifi .tar.bz2 (zero deps, legacy).
     * Rationale: Minimal legacy package.
     */
    @Test
    void package_certifi_tarBz2_zeroDeps() throws Exception {
        Path pkg = findPackage("certifi-2021.5.30-py36h5fab9bb_0.tar.bz2");
        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.name()).hasValue("certifi");
        assertThat(result.version()).hasValue("2021.5.30");
    }

    /**
     * Goal: Verify noarch subdir is correctly extracted.
     * Rationale: Q4 - noarch packages are platform-independent.
     */
    @Test
    void package_noarch_python() throws Exception {
        Path pkg = findPackage("six-1.16.0-pyhd8ed1ab_1.conda");
        CondaMetadataExtractor.CondaArchiveData data = extractArchiveData(pkg);
        Optional<String> subdir = CondaMetadataExtractor.extractSubdir(data);
        assertThat(subdir).hasValue("noarch");
    }

    /**
     * Goal: Verify linux-64 subdir is correctly extracted.
     * Rationale: Q4 - Platform-specific packages have their subdir set.
     */
    @Test
    void package_linux64_platformSpecific() throws Exception {
        Path pkg = findPackage("numpy-1.26.4-py310hb13e2d6_0.conda");
        CondaMetadataExtractor.CondaArchiveData data = extractArchiveData(pkg);
        Optional<String> subdir = CondaMetadataExtractor.extractSubdir(data);
        assertThat(subdir).hasValue("linux-64");
    }

    /**
     * Goal: Verify timestamp conversion for a package with timestamp.
     * Rationale: Q8 - Millis to ISO 8601 conversion.
     */
    @Test
    void package_withTimestamp() throws Exception {
        Path pkg = findPackage("numpy-1.26.4-py310hb13e2d6_0.conda");
        MetadataResult result = extractFromPackage(pkg);
        assertThat(result.publishedAt()).isPresent();
        assertThat(result.publishedAt().get()).matches("\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\+00:00");
    }

    /**
     * Goal: Verify package without about.json has null description.
     * Rationale: Q7 - about.json may be absent; description should be null.
     */
    @Test
    void package_noAboutJson() throws Exception {
        // The old zlib 1.2.11 has about.json but let's test the case with no about.json
        // by checking that description is handled correctly — verify null case with synthetic data
        CondaMetadataExtractor.CondaArchiveData data =
                new CondaMetadataExtractor.CondaArchiveData(
                        "{\"name\":\"test\",\"version\":\"1.0\"}", null);
        MetadataResult result = CondaMetadataExtractor.buildMetadataResult(data);
        assertThat(result.description()).isEmpty();
    }

    /**
     * Goal: Verify constrains field is ignored (not in dependencies).
     * Rationale: Q5 - constrains are NOT deps; only depends array matters.
     */
    @Test
    void package_constrains_ignored() throws Exception {
        // Use a synthetic index.json with constrains field
        String indexJson = """
                {
                  "name": "test",
                  "version": "1.0",
                  "depends": ["dep1 >=1.0"],
                  "constrains": ["other_pkg >=2.0"]
                }
                """;
        CondaMetadataExtractor.CondaArchiveData data =
                new CondaMetadataExtractor.CondaArchiveData(indexJson, null);
        MetadataResult result = CondaMetadataExtractor.buildMetadataResult(data);

        assertThat(result.dependencies()).hasSize(1);
        assertThat(result.dependencies().get(0).name()).isEqualTo("dep1");
        // "other_pkg" from constrains should NOT appear
        assertThat(result.dependencies().stream().map(ParsedDependency::name))
                .doesNotContain("other_pkg");
    }

    // --- Unit tests for parseMatchSpec ---

    /**
     * Goal: Verify name-only match spec.
     * Rationale: Q6 - Some specs have just a name, no version constraint.
     */
    @Test
    void parseMatchSpec_nameOnly() {
        ParsedDependency dep = CondaMetadataExtractor.parseMatchSpec("python");
        assertThat(dep.name()).isEqualTo("python");
        assertThat(dep.versionConstraint()).isEmpty();
        assertThat(dep.scope()).hasValue("runtime");
    }

    /**
     * Goal: Verify name + version constraint.
     * Rationale: Q6 - Common format "name >=version".
     */
    @Test
    void parseMatchSpec_nameAndVersion() {
        ParsedDependency dep = CondaMetadataExtractor.parseMatchSpec("python >=3.8");
        assertThat(dep.name()).isEqualTo("python");
        assertThat(dep.versionConstraint()).hasValue(">=3.8");
        assertThat(dep.scope()).hasValue("runtime");
    }

    /**
     * Goal: Verify name + version + build string (build included in constraint).
     * Rationale: Q6 - Build string stays in versionConstraint per native tools.
     */
    @Test
    void parseMatchSpec_nameVersionBuild() {
        ParsedDependency dep = CondaMetadataExtractor.parseMatchSpec("_libgcc_mutex 0.1 conda_forge");
        assertThat(dep.name()).isEqualTo("_libgcc_mutex");
        assertThat(dep.versionConstraint()).hasValue("0.1 conda_forge");
        assertThat(dep.scope()).hasValue("runtime");
    }

    /**
     * Goal: Verify comma-separated constraint.
     * Rationale: Q6 - Constraints like ">=3.9.0,<4.0a0".
     */
    @Test
    void parseMatchSpec_commaConstraint() {
        ParsedDependency dep = CondaMetadataExtractor.parseMatchSpec("libblas >=3.9.0,<4.0a0");
        assertThat(dep.name()).isEqualTo("libblas");
        assertThat(dep.versionConstraint()).hasValue(">=3.9.0,<4.0a0");
    }

    /**
     * Goal: Verify equality constraint.
     * Rationale: Q6 - Some deps use exact version "==version".
     */
    @Test
    void parseMatchSpec_equalConstraint() {
        ParsedDependency dep = CondaMetadataExtractor.parseMatchSpec("python_abi 3.10.* *_cp310");
        assertThat(dep.name()).isEqualTo("python_abi");
        assertThat(dep.versionConstraint()).hasValue("3.10.* *_cp310");
    }

    // --- Unit tests for detectFormat ---

    /**
     * Goal: Verify .conda extension detected.
     * Rationale: Q1 - Modern format detection.
     */
    @Test
    void detectFormat_conda() throws Exception {
        assertThat(CondaMetadataExtractor.detectFormat("numpy-1.26.4.conda"))
                .isEqualTo(CondaMetadataExtractor.CondaFormat.CONDA);
    }

    /**
     * Goal: Verify .tar.bz2 extension detected.
     * Rationale: Q1 - Legacy format detection.
     */
    @Test
    void detectFormat_tarBz2() throws Exception {
        assertThat(CondaMetadataExtractor.detectFormat("numpy-1.21.0.tar.bz2"))
                .isEqualTo(CondaMetadataExtractor.CondaFormat.TAR_BZ2);
    }

    /**
     * Goal: Verify unknown extension throws.
     * Rationale: Only .conda and .tar.bz2 are valid; others should fail.
     */
    @Test
    void detectFormat_unknown_throws() {
        assertThatThrownBy(() -> CondaMetadataExtractor.detectFormat("package.zip"))
                .isInstanceOf(MalformedPackageException.class);
    }

    // --- Unit tests for extractDescription ---

    /**
     * Goal: Verify summary is preferred over description.
     * Rationale: Q7 - about.json summary takes priority.
     */
    @Test
    void extractDescription_summaryPreferred() {
        JsonObject about = new JsonObject();
        about.addProperty("summary", "A short summary");
        about.addProperty("description", "A long description");
        assertThat(CondaMetadataExtractor.extractDescription(about)).hasValue("A short summary");
    }

    /**
     * Goal: Verify description fallback when summary absent.
     * Rationale: Q7 - Falls back to description field.
     */
    @Test
    void extractDescription_descriptionFallback() {
        JsonObject about = new JsonObject();
        about.addProperty("description", "A long description");
        assertThat(CondaMetadataExtractor.extractDescription(about)).hasValue("A long description");
    }

    /**
     * Goal: Verify null when both absent.
     * Rationale: Q7 - No description fields → empty.
     */
    @Test
    void extractDescription_bothAbsent() {
        JsonObject about = new JsonObject();
        assertThat(CondaMetadataExtractor.extractDescription(about)).isEmpty();
    }

    /**
     * Goal: Verify empty summary falls back to description.
     * Rationale: Q7 - Empty string summary is treated as absent.
     */
    @Test
    void extractDescription_summaryEmpty() {
        JsonObject about = new JsonObject();
        about.addProperty("summary", "");
        about.addProperty("description", "Fallback");
        assertThat(CondaMetadataExtractor.extractDescription(about)).hasValue("Fallback");
    }

    // --- Unit tests for timestampConversion ---

    /**
     * Goal: Verify millis to ISO 8601 conversion.
     * Rationale: Q8 - Standard timestamp conversion.
     */
    @Test
    void timestampConversion_millisToIso() {
        JsonObject json = new JsonObject();
        json.addProperty("timestamp", 1707225917000L);
        assertThat(CondaMetadataExtractor.convertTimestamp(json))
                .hasValue("2024-02-06T13:25:17+00:00");
    }

    /**
     * Goal: Verify absent timestamp → empty.
     * Rationale: Q8 - Timestamp may be absent.
     */
    @Test
    void timestampConversion_absent() {
        JsonObject json = new JsonObject();
        assertThat(CondaMetadataExtractor.convertTimestamp(json)).isEmpty();
    }

    /**
     * Goal: Verify zero timestamp.
     * Rationale: Q8 - Edge case at epoch.
     */
    @Test
    void timestampConversion_zero() {
        JsonObject json = new JsonObject();
        json.addProperty("timestamp", 0L);
        assertThat(CondaMetadataExtractor.convertTimestamp(json))
                .hasValue("1970-01-01T00:00:00+00:00");
    }

    /**
     * Goal: Verify negative timestamp.
     * Rationale: Q8 - Pre-epoch timestamp should still work.
     */
    @Test
    void timestampConversion_negativeTimestamp() {
        JsonObject json = new JsonObject();
        json.addProperty("timestamp", -1000L);
        Optional<String> result = CondaMetadataExtractor.convertTimestamp(json);
        assertThat(result).isPresent();
        assertThat(result.get()).startsWith("1969-");
    }

    // --- Error handling tests ---

    /**
     * Goal: Verify MalformedPackageException for archive without index.json.
     * Rationale: index.json is required; its absence must be reported.
     */
    @Test
    void extractFromArchive_noIndexJson_throws() {
        assertThatThrownBy(() ->
                CondaMetadataExtractor.extractFromArchive(
                        new ByteArrayInputStream(new byte[0]), "bad.conda"))
                .isInstanceOf(Exception.class);
    }

    /**
     * Goal: Verify corrupt JSON handling.
     * Rationale: Malformed index.json should throw MetadataExtractionException.
     */
    @Test
    void buildMetadataResult_corruptJson() {
        CondaMetadataExtractor.CondaArchiveData data =
                new CondaMetadataExtractor.CondaArchiveData("{invalid json", null);
        assertThatThrownBy(() -> CondaMetadataExtractor.buildMetadataResult(data))
                .isInstanceOf(Exception.class);
    }

    // --- Miscellaneous unit tests ---

    /**
     * Goal: Verify empty depends list produces empty dependencies.
     * Rationale: Some packages have depends=[] explicitly.
     */
    @Test
    void emptyDependsList() throws Exception {
        JsonObject json = new JsonObject();
        json.add("depends", new JsonArray());
        assertThat(CondaMetadataExtractor.parseDependencies(json)).isEmpty();
    }

    /**
     * Goal: Verify null depends produces empty dependencies.
     * Rationale: Depends field may be absent.
     */
    @Test
    void nullDependsList() {
        JsonObject json = new JsonObject();
        assertThat(CondaMetadataExtractor.parseDependencies(json)).isEmpty();
    }

    /**
     * Goal: Verify unknown extra fields in index.json don't cause errors.
     * Rationale: index.json may have fields we don't use.
     */
    @Test
    void unknownExtraFields() throws Exception {
        String indexJson = """
                {"name":"test","version":"1.0","unknown_field":"value","another":42}
                """;
        CondaMetadataExtractor.CondaArchiveData data =
                new CondaMetadataExtractor.CondaArchiveData(indexJson, null);
        MetadataResult result = CondaMetadataExtractor.buildMetadataResult(data);
        assertThat(result.name()).hasValue("test");
    }

    /**
     * Goal: Verify large dependencies list.
     * Rationale: Some packages have many dependencies.
     */
    @Test
    void largeDependsList() throws Exception {
        JsonArray deps = new JsonArray();
        for (int i = 0; i < 100; i++) {
            deps.add("dep" + i + " >=" + i + ".0");
        }
        JsonObject json = new JsonObject();
        json.add("depends", deps);
        List<ParsedDependency> parsed = CondaMetadataExtractor.parseDependencies(json);
        assertThat(parsed).hasSize(100);
    }

    /**
     * Goal: Verify publisher is always null in buildMetadataResult.
     * Rationale: Q2 - Conda has no author field.
     */
    @Test
    void buildMetadataResult_publisherAlwaysNull() throws Exception {
        String indexJson = """
                {"name":"test","version":"1.0","author":"should be ignored"}
                """;
        CondaMetadataExtractor.CondaArchiveData data =
                new CondaMetadataExtractor.CondaArchiveData(indexJson, null);
        MetadataResult result = CondaMetadataExtractor.buildMetadataResult(data);
        assertThat(result.publisher()).isEmpty();
    }

    // --- Helper methods ---

    private MetadataResult extractFromPackage(Path pkgPath) throws Exception {
        try (FileInputStream fis = new FileInputStream(pkgPath.toFile())) {
            return CondaMetadataExtractor.extract(fis, pkgPath.getFileName().toString());
        }
    }

    private CondaMetadataExtractor.CondaArchiveData extractArchiveData(Path pkgPath) throws Exception {
        try (FileInputStream fis = new FileInputStream(pkgPath.toFile())) {
            return CondaMetadataExtractor.extractFromArchive(fis, pkgPath.getFileName().toString());
        }
    }

    private Path findPackage(String filename) {
        Path pkg = CONDA_CORPUS.resolve(filename);
        assumeThat(Files.exists(pkg)).isTrue();
        return pkg;
    }

    private record DepTuple(String name, String versionConstraint, String scope) {
    }
}
