/* Copyright 2026 Spice Labs, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License. */

package io.spicelabs.annatto.go;

import com.google.gson.JsonObject;
import io.spicelabs.annatto.common.MetadataResult;
import io.spicelabs.annatto.common.ParsedDependency;
import io.spicelabs.annatto.testutil.SourceOfTruth;
import io.spicelabs.annatto.testutil.TestCorpusDownloader;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Optional;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assumptions.assumeThat;

/**
 * Tests for {@link GoMetadataExtractor} comparing extraction results against
 * source-of-truth expected values produced by native Go tools in Docker.
 *
 * <p>All test packages are real Go modules downloaded from proxy.golang.org.
 * Expected values were generated by running Docker containers with Go and jq
 * that parse the actual go.mod from each archive.</p>
 *
 * <p>Package files (.zip) are in {@code test-corpus/go/} (downloaded from
 * public-test-data.spice-labs.dev, gitignored). Source-of-truth expected JSON
 * files are in {@code src/test/resources/go/} (git-tracked).</p>
 *
 * <p>Covers {@link GoQuirks} Q1 (URL-like module paths), Q2 (+incompatible),
 * Q3 (pseudo-versions), Q4 (replace/exclude ignored), Q5 (major version suffixes),
 * Q6 (retracted versions ignored).</p>
 */
class GoMetadataExtractorTest {

    /** Directory containing real Go module zip files (gitignored, downloaded from test data server). */
    private static final Path GO_CORPUS = TestCorpusDownloader.corpusDir("go");

    /** Directory containing source-of-truth expected JSON files (git-tracked). */
    private static final Path GO_EXPECTED = TestCorpusDownloader.expectedDir("go");

    @BeforeAll
    static void ensureTestPackagesExist() {
        assumeThat(Files.isDirectory(GO_CORPUS))
                .as("go test corpus directory must exist with real packages")
                .isTrue();
    }

    // --- Parameterized source-of-truth comparison ---

    /**
     * Provides all .zip files in the go corpus directory paired with their expected JSON.
     */
    static Stream<Arguments> realPackages() throws IOException {
        if (!Files.isDirectory(GO_CORPUS)) {
            return Stream.empty();
        }
        return Files.list(GO_CORPUS)
                .filter(p -> p.toString().endsWith(".zip"))
                .sorted()
                .map(pkg -> {
                    Path expected = SourceOfTruth.expectedPathFor(pkg, GO_EXPECTED);
                    String label = pkg.getFileName().toString();
                    return Arguments.of(label, pkg, expected);
                });
    }

    /**
     * Goal: Verify that the extracted name matches the source-of-truth for every real Go module.
     * Rationale: Name (module path) is the most fundamental metadata field; must be exact for all packages (Q1).
     */
    @ParameterizedTest(name = "name: {0}")
    @MethodSource("realPackages")
    void extractName_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.name())
                .isEqualTo(SourceOfTruth.getString(expected, "name"));
    }

    /**
     * Goal: Verify that the extracted simple name matches the source-of-truth.
     * Rationale: Simple name is the last path segment (Q1), handling /vN suffixes (Q5).
     */
    @ParameterizedTest(name = "simpleName: {0}")
    @MethodSource("realPackages")
    void extractSimpleName_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.simpleName())
                .isEqualTo(SourceOfTruth.getString(expected, "simpleName"));
    }

    /**
     * Goal: Verify that the extracted version matches the source-of-truth.
     * Rationale: Version must be extracted as-is from the zip entry name, including pseudo-versions (Q3).
     */
    @ParameterizedTest(name = "version: {0}")
    @MethodSource("realPackages")
    void extractVersion_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.version())
                .isEqualTo(SourceOfTruth.getString(expected, "version"));
    }

    /**
     * Goal: Verify that description is always empty for Go modules.
     * Rationale: go.mod has no description field.
     */
    @ParameterizedTest(name = "description: {0}")
    @MethodSource("realPackages")
    void extractDescription_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.description())
                .isEqualTo(SourceOfTruth.getString(expected, "description"));
    }

    /**
     * Goal: Verify that license is always empty for Go modules.
     * Rationale: go.mod has no license field.
     */
    @ParameterizedTest(name = "license: {0}")
    @MethodSource("realPackages")
    void extractLicense_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.license())
                .isEqualTo(SourceOfTruth.getString(expected, "license"));
    }

    /**
     * Goal: Verify that publisher is always empty for Go modules.
     * Rationale: go.mod has no author/publisher field.
     */
    @ParameterizedTest(name = "publisher: {0}")
    @MethodSource("realPackages")
    void extractPublisher_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.publisher())
                .isEqualTo(SourceOfTruth.getString(expected, "publisher"));
    }

    /**
     * Goal: Verify that the extracted dependency count matches the source-of-truth.
     * Rationale: All require directives must be parsed, including indirect deps.
     */
    @ParameterizedTest(name = "dependencyCount: {0}")
    @MethodSource("realPackages")
    void extractDependencies_countMatchesSourceOfTruth(String label, Path pkgPath, Path expectedPath)
            throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        int expectedCount = expected.getAsJsonArray("dependencies").size();

        assertThat(result.dependencies())
                .hasSize(expectedCount);
    }

    /**
     * Goal: Verify that all extracted dependency names, versions, and scopes match the source-of-truth.
     * Rationale: Dependency extraction must correctly parse require blocks, indirect markers, and version constraints.
     */
    @ParameterizedTest(name = "dependencies: {0}")
    @MethodSource("realPackages")
    void extractDependencies_matchSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        var expectedDeps = expected.getAsJsonArray("dependencies");
        List<DepTuple> expectedTuples = new java.util.ArrayList<>();
        for (var elem : expectedDeps) {
            JsonObject depObj = elem.getAsJsonObject();
            String name = depObj.get("name").getAsString();
            String vc = depObj.get("versionConstraint").isJsonNull() ? null
                    : depObj.get("versionConstraint").getAsString();
            String scope = depObj.get("scope").getAsString();
            expectedTuples.add(new DepTuple(name, vc, scope));
        }

        List<DepTuple> actualTuples = result.dependencies().stream()
                .map(d -> new DepTuple(d.name(), d.versionConstraint().orElse(null), d.scope().orElse(null)))
                .toList();

        assertThat(actualTuples)
                .as("dependencies for %s", label)
                .containsExactlyInAnyOrderElementsOf(expectedTuples);
    }

    // --- Specific named package tests ---

    /**
     * Goal: Verify extraction for gin web framework.
     * Rationale: Q1 - popular module with many dependencies, URL-like module path.
     */
    @Test
    void goModule_gin_extractsCorrectly() throws Exception {
        Path zip = GO_CORPUS.resolve("github.com_gin-gonic_gin@v1.9.1.zip");
        assumeThat(Files.exists(zip)).isTrue();

        MetadataResult result = extractFromPackage(zip);

        assertThat(result.name()).hasValue("github.com/gin-gonic/gin");
        assertThat(result.simpleName()).hasValue("gin");
        assertThat(result.version()).hasValue("v1.9.1");
        assertThat(result.description()).isEmpty();
        assertThat(result.license()).isEmpty();
        assertThat(result.publisher()).isEmpty();
        assertThat(result.dependencies()).isNotEmpty();
    }

    /**
     * Goal: Verify extraction for golang.org/x/text module.
     * Rationale: Q1 - golang.org/x modules use non-github URL paths.
     */
    @Test
    void goModule_golangOrgText_extractsCorrectly() throws Exception {
        Path zip = GO_CORPUS.resolve("golang.org_x_text@v0.14.0.zip");
        assumeThat(Files.exists(zip)).isTrue();

        MetadataResult result = extractFromPackage(zip);

        assertThat(result.name()).hasValue("golang.org/x/text");
        assertThat(result.simpleName()).hasValue("text");
        assertThat(result.version()).hasValue("v0.14.0");
    }

    /**
     * Goal: Verify extraction for gopkg.in/yaml.v3 module.
     * Rationale: Q1 - gopkg.in modules use a vanity URL with version suffix in path.
     */
    @Test
    void goModule_gopkgInYamlV3_extractsCorrectly() throws Exception {
        Path zip = GO_CORPUS.resolve("gopkg.in_yaml.v3@v3.0.1.zip");
        assumeThat(Files.exists(zip)).isTrue();

        MetadataResult result = extractFromPackage(zip);

        assertThat(result.name()).hasValue("gopkg.in/yaml.v3");
        assertThat(result.simpleName()).hasValue("yaml.v3");
        assertThat(result.version()).hasValue("v3.0.1");
    }

    /**
     * Goal: Verify extraction for a module with zero dependencies.
     * Rationale: Modules with no require directives should have empty dependency list.
     */
    @Test
    void goModule_uuid_zeroDeps() throws Exception {
        Path zip = GO_CORPUS.resolve("github.com_google_uuid@v1.5.0.zip");
        assumeThat(Files.exists(zip)).isTrue();

        MetadataResult result = extractFromPackage(zip);

        assertThat(result.name()).hasValue("github.com/google/uuid");
        assertThat(result.simpleName()).hasValue("uuid");
        assertThat(result.dependencies()).isEmpty();
    }

    /**
     * Goal: Verify extraction for a /v5 major version module.
     * Rationale: Q5 - major version suffix in path; simple name should be "v5".
     */
    @Test
    void goModule_chiV5_majorVersion() throws Exception {
        Path zip = GO_CORPUS.resolve("github.com_go-chi_chi_v5@v5.0.11.zip");
        assumeThat(Files.exists(zip)).isTrue();

        MetadataResult result = extractFromPackage(zip);

        assertThat(result.name()).hasValue("github.com/go-chi/chi/v5");
        assertThat(result.simpleName()).hasValue("v5");
        assertThat(result.version()).hasValue("v5.0.11");
    }

    /**
     * Goal: Verify extraction for pseudo-version module.
     * Rationale: Q3 - pseudo-versions use v0.0.0-date-hash format.
     */
    @Test
    void goModule_genproto_pseudoVersion() throws Exception {
        Path zip = GO_CORPUS.resolve(
                "google.golang.org_genproto@v0.0.0-20240102182953-50ed04b92917.zip");
        assumeThat(Files.exists(zip)).isTrue();

        MetadataResult result = extractFromPackage(zip);

        assertThat(result.name()).hasValue("google.golang.org/genproto");
        assertThat(result.version()).hasValue("v0.0.0-20240102182953-50ed04b92917");
    }

    // --- Unit tests for extractSimpleName ---

    /**
     * Goal: Verify simple name extraction for a standard module path.
     * Rationale: Q1 - last path segment is the simple name.
     */
    @Test
    void extractSimpleName_standardModule() {
        assertThat(GoMetadataExtractor.extractSimpleName("github.com/gin-gonic/gin")).isEqualTo("gin");
    }

    /**
     * Goal: Verify simple name extraction for golang.org/x modules.
     * Rationale: Q1 - golang.org/x/ modules use short names like "text", "net".
     */
    @Test
    void extractSimpleName_golangOrgX() {
        assertThat(GoMetadataExtractor.extractSimpleName("golang.org/x/text")).isEqualTo("text");
        assertThat(GoMetadataExtractor.extractSimpleName("golang.org/x/net")).isEqualTo("net");
    }

    /**
     * Goal: Verify simple name extraction for /vN major version modules.
     * Rationale: Q5 - for /vN modules, simple name is "vN".
     */
    @Test
    void extractSimpleName_majorVersionModule() {
        assertThat(GoMetadataExtractor.extractSimpleName("github.com/go-chi/chi/v5")).isEqualTo("v5");
        assertThat(GoMetadataExtractor.extractSimpleName("github.com/jackc/pgx/v5")).isEqualTo("v5");
        assertThat(GoMetadataExtractor.extractSimpleName("github.com/go-playground/validator/v10")).isEqualTo("v10");
    }

    /**
     * Goal: Verify simple name extraction for gopkg.in modules.
     * Rationale: Q1 - gopkg.in paths like "gopkg.in/yaml.v3" have "yaml.v3" as last segment.
     */
    @Test
    void extractSimpleName_gopkgIn() {
        assertThat(GoMetadataExtractor.extractSimpleName("gopkg.in/yaml.v3")).isEqualTo("yaml.v3");
        assertThat(GoMetadataExtractor.extractSimpleName("gopkg.in/yaml.v2")).isEqualTo("yaml.v2");
        assertThat(GoMetadataExtractor.extractSimpleName("gopkg.in/check.v1")).isEqualTo("check.v1");
    }

    /**
     * Goal: Verify simple name for a single-segment module path.
     * Rationale: Edge case where module path has no slash.
     */
    @Test
    void extractSimpleName_noSlash() {
        assertThat(GoMetadataExtractor.extractSimpleName("example")).isEqualTo("example");
    }

    // --- Unit tests for extractVersionFromEntryName ---

    /**
     * Goal: Verify version extraction from a standard zip entry name.
     * Rationale: Entry names follow module@version/go.mod format.
     */
    @Test
    void extractVersionFromEntryName_standard() {
        assertThat(GoMetadataExtractor.extractVersionFromEntryName(
                "github.com/gin-gonic/gin@v1.9.1/go.mod")).isEqualTo("v1.9.1");
    }

    /**
     * Goal: Verify version extraction for pseudo-version entries.
     * Rationale: Q3 - pseudo-versions must be preserved exactly.
     */
    @Test
    void extractVersionFromEntryName_pseudoVersion() {
        assertThat(GoMetadataExtractor.extractVersionFromEntryName(
                "google.golang.org/genproto@v0.0.0-20240102182953-50ed04b92917/go.mod"))
                .isEqualTo("v0.0.0-20240102182953-50ed04b92917");
    }

    /**
     * Goal: Verify version extraction for /vN modules.
     * Rationale: Q5 - /vN is part of the module path, not the version.
     */
    @Test
    void extractVersionFromEntryName_majorVersion() {
        assertThat(GoMetadataExtractor.extractVersionFromEntryName(
                "github.com/go-chi/chi/v5@v5.0.11/go.mod")).isEqualTo("v5.0.11");
    }

    // --- Unit tests for extractModulePathFromEntryName ---

    /**
     * Goal: Verify module path extraction from entry name.
     * Rationale: Module path is everything before the last @.
     */
    @Test
    void extractModulePathFromEntryName_standard() {
        assertThat(GoMetadataExtractor.extractModulePathFromEntryName(
                "github.com/gin-gonic/gin@v1.9.1/go.mod")).isEqualTo("github.com/gin-gonic/gin");
    }

    /**
     * Goal: Verify module path extraction for /vN modules.
     * Rationale: Q5 - /vN is part of the module path.
     */
    @Test
    void extractModulePathFromEntryName_majorVersion() {
        assertThat(GoMetadataExtractor.extractModulePathFromEntryName(
                "github.com/go-chi/chi/v5@v5.0.11/go.mod")).isEqualTo("github.com/go-chi/chi/v5");
    }

    // --- Unit tests for isGoMod ---

    /**
     * Goal: Verify standard go.mod entry is recognized.
     * Rationale: Root-level go.mod is the metadata source.
     */
    @Test
    void isGoMod_standardEntry() {
        assertThat(GoMetadataExtractor.isGoMod("github.com/gin-gonic/gin@v1.9.1/go.mod")).isTrue();
    }

    /**
     * Goal: Verify go.mod in subdirectory is NOT recognized.
     * Rationale: Only root-level go.mod should be extracted.
     */
    @Test
    void isGoMod_subdirectoryNotMatched() {
        assertThat(GoMetadataExtractor.isGoMod(
                "github.com/gin-gonic/gin@v1.9.1/internal/testmod/go.mod")).isFalse();
    }

    /**
     * Goal: Verify non-go.mod files are NOT matched.
     * Rationale: Only go.mod entries should match.
     */
    @Test
    void isGoMod_otherFileNotMatched() {
        assertThat(GoMetadataExtractor.isGoMod("github.com/gin-gonic/gin@v1.9.1/go.sum")).isFalse();
        assertThat(GoMetadataExtractor.isGoMod("github.com/gin-gonic/gin@v1.9.1/main.go")).isFalse();
    }

    /**
     * Goal: Verify entries without @ are NOT matched.
     * Rationale: Go module zips always have @version in the path.
     */
    @Test
    void isGoMod_noAtSign_notMatched() {
        assertThat(GoMetadataExtractor.isGoMod("some/path/go.mod")).isFalse();
    }

    // --- Unit tests for parseGoMod ---

    /**
     * Goal: Verify basic go.mod parsing with module, go version, and require block.
     * Rationale: Most common go.mod structure.
     */
    @Test
    void parseGoMod_basicModuleAndRequire() {
        String goMod = """
                module github.com/example/mymod

                go 1.21

                require (
                \tgithub.com/foo/bar v1.2.3
                \tgithub.com/baz/qux v0.1.0 // indirect
                )
                """;
        GoMetadataExtractor.ParsedGoMod parsed = GoMetadataExtractor.parseGoMod(goMod);

        assertThat(parsed.modulePath()).isEqualTo("github.com/example/mymod");
        assertThat(parsed.goVersion()).isEqualTo("1.21");
        assertThat(parsed.requires()).hasSize(2);
        assertThat(parsed.requires().get(0).name()).isEqualTo("github.com/foo/bar");
        assertThat(parsed.requires().get(0).versionConstraint()).hasValue("v1.2.3");
        assertThat(parsed.requires().get(0).scope()).hasValue("runtime");
        assertThat(parsed.requires().get(1).name()).isEqualTo("github.com/baz/qux");
        assertThat(parsed.requires().get(1).scope()).hasValue("indirect");
    }

    /**
     * Goal: Verify single-line require directive parsing.
     * Rationale: Some go.mod files use single require lines instead of blocks.
     */
    @Test
    void parseGoMod_singleLineRequire() {
        String goMod = """
                module example.com/mod

                go 1.20

                require github.com/foo/bar v1.0.0
                """;
        GoMetadataExtractor.ParsedGoMod parsed = GoMetadataExtractor.parseGoMod(goMod);

        assertThat(parsed.requires()).hasSize(1);
        assertThat(parsed.requires().get(0).name()).isEqualTo("github.com/foo/bar");
        assertThat(parsed.requires().get(0).versionConstraint()).hasValue("v1.0.0");
    }

    /**
     * Goal: Verify replace directives are ignored.
     * Rationale: Q4 - replace directives alter resolution but should not appear in dependencies.
     */
    @Test
    void parseGoMod_ignoresReplace() {
        String goMod = """
                module example.com/mod

                go 1.20

                require github.com/foo/bar v1.0.0

                replace github.com/foo/bar => github.com/foo/bar-fork v1.0.1
                """;
        GoMetadataExtractor.ParsedGoMod parsed = GoMetadataExtractor.parseGoMod(goMod);

        assertThat(parsed.requires()).hasSize(1);
        assertThat(parsed.requires().get(0).name()).isEqualTo("github.com/foo/bar");
    }

    /**
     * Goal: Verify replace blocks are ignored.
     * Rationale: Q4 - multi-line replace blocks should not contribute to dependencies.
     */
    @Test
    void parseGoMod_ignoresReplaceBlock() {
        String goMod = """
                module example.com/mod

                go 1.20

                require github.com/foo/bar v1.0.0

                replace (
                \tgithub.com/foo/bar => github.com/foo/bar-fork v1.0.1
                )
                """;
        GoMetadataExtractor.ParsedGoMod parsed = GoMetadataExtractor.parseGoMod(goMod);

        assertThat(parsed.requires()).hasSize(1);
    }

    /**
     * Goal: Verify exclude directives are ignored.
     * Rationale: Q4 - exclude directives should not appear in dependencies.
     */
    @Test
    void parseGoMod_ignoresExclude() {
        String goMod = """
                module example.com/mod

                go 1.20

                require github.com/foo/bar v1.0.0

                exclude github.com/foo/bar v0.9.0
                """;
        GoMetadataExtractor.ParsedGoMod parsed = GoMetadataExtractor.parseGoMod(goMod);

        assertThat(parsed.requires()).hasSize(1);
    }

    /**
     * Goal: Verify retract directives are ignored.
     * Rationale: Q6 - retract directives mark withdrawn versions but shouldn't affect dependency extraction.
     */
    @Test
    void parseGoMod_ignoresRetract() {
        String goMod = """
                module example.com/mod

                go 1.20

                require github.com/foo/bar v1.0.0

                retract v0.1.0
                """;
        GoMetadataExtractor.ParsedGoMod parsed = GoMetadataExtractor.parseGoMod(goMod);

        assertThat(parsed.requires()).hasSize(1);
    }

    /**
     * Goal: Verify retract blocks are ignored.
     * Rationale: Q6 - multi-line retract blocks should not affect extraction.
     */
    @Test
    void parseGoMod_ignoresRetractBlock() {
        String goMod = """
                module example.com/mod

                go 1.20

                require github.com/foo/bar v1.0.0

                retract (
                \tv0.1.0
                \t[v0.2.0, v0.3.0]
                )
                """;
        GoMetadataExtractor.ParsedGoMod parsed = GoMetadataExtractor.parseGoMod(goMod);

        assertThat(parsed.requires()).hasSize(1);
    }

    /**
     * Goal: Verify quoted module path is handled.
     * Rationale: Some go.mod files quote the module path.
     */
    @Test
    void parseGoMod_quotedModulePath() {
        String goMod = """
                module "example.com/mod"

                go 1.20
                """;
        GoMetadataExtractor.ParsedGoMod parsed = GoMetadataExtractor.parseGoMod(goMod);

        assertThat(parsed.modulePath()).isEqualTo("example.com/mod");
    }

    /**
     * Goal: Verify empty go.mod parses without error.
     * Rationale: Graceful handling of minimal/empty files.
     */
    @Test
    void parseGoMod_emptyContent() {
        GoMetadataExtractor.ParsedGoMod parsed = GoMetadataExtractor.parseGoMod("");

        assertThat(parsed.modulePath()).isNull();
        assertThat(parsed.requires()).isEmpty();
    }

    /**
     * Goal: Verify toolchain directive is ignored.
     * Rationale: Go 1.21+ introduced toolchain directive; it should not affect extraction.
     */
    @Test
    void parseGoMod_ignoresToolchain() {
        String goMod = """
                module example.com/mod

                go 1.21

                toolchain go1.21.5

                require github.com/foo/bar v1.0.0
                """;
        GoMetadataExtractor.ParsedGoMod parsed = GoMetadataExtractor.parseGoMod(goMod);

        assertThat(parsed.requires()).hasSize(1);
    }

    /**
     * Goal: Verify indirect dependency scope is correctly set.
     * Rationale: Dependencies marked with // indirect must have scope "indirect".
     */
    @Test
    void parseGoMod_indirectScope() {
        String goMod = """
                module example.com/mod

                go 1.20

                require (
                \tgithub.com/direct/dep v1.0.0
                \tgithub.com/indirect/dep v2.0.0 // indirect
                )
                """;
        GoMetadataExtractor.ParsedGoMod parsed = GoMetadataExtractor.parseGoMod(goMod);

        assertThat(parsed.requires()).hasSize(2);
        ParsedDependency direct = parsed.requires().stream()
                .filter(d -> d.name().equals("github.com/direct/dep")).findFirst().orElseThrow();
        ParsedDependency indirect = parsed.requires().stream()
                .filter(d -> d.name().equals("github.com/indirect/dep")).findFirst().orElseThrow();

        assertThat(direct.scope()).hasValue("runtime");
        assertThat(indirect.scope()).hasValue("indirect");
    }

    // --- Helper methods ---

    private MetadataResult extractFromPackage(Path pkgPath) throws Exception {
        try (FileInputStream fis = new FileInputStream(pkgPath.toFile())) {
            return GoMetadataExtractor.extract(fis, pkgPath.getFileName().toString());
        }
    }

    private record DepTuple(String name, String versionConstraint, String scope) {
    }
}
