/* Copyright 2026 Spice Labs, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License. */

package io.spicelabs.annatto.hex;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import io.spicelabs.annatto.common.MetadataResult;
import io.spicelabs.annatto.common.ParsedDependency;
import io.spicelabs.annatto.testutil.SourceOfTruth;
import io.spicelabs.annatto.testutil.TestCorpusDownloader;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assumptions.assumeThat;

/**
 * Tests for {@link HexMetadataExtractor} using source-of-truth expected JSON files
 * generated by the Docker-based native Elixir extractor.
 */
class HexMetadataExtractorTest {

    private static final Path HEX_CORPUS = TestCorpusDownloader.corpusDir("hex");
    private static final Path HEX_EXPECTED = Path.of("src/test/resources/hex");

    @BeforeAll
    static void ensureTestPackagesExist() {
        assumeThat(Files.isDirectory(HEX_CORPUS))
                .as("hex test corpus directory must exist")
                .isTrue();
    }

    // --- Source-of-truth parameterized tests ---

    static Stream<Arguments> allPackages() throws IOException {
        if (!Files.isDirectory(HEX_CORPUS)) return Stream.empty();
        return Files.list(HEX_CORPUS)
                .filter(p -> p.toString().endsWith(".tar"))
                .sorted()
                .map(p -> Arguments.of(p.getFileName().toString(), p));
    }

    /**
     * Goal: Verify name matches expected for every real package.
     * Rationale: Name must be extracted exactly from metadata.config.
     */
    @ParameterizedTest(name = "name: {0}")
    @MethodSource("allPackages")
    void sot_name(String label, Path pkgPath) throws Exception {
        MetadataResult result = extractResult(pkgPath);
        JsonObject expected = loadExpected(pkgPath);
        assertThat(result.name()).isEqualTo(optStr(expected, "name"));
    }

    /**
     * Goal: Verify simpleName matches expected for every real package.
     * Rationale: Q6 — simpleName equals name for Hex.
     */
    @ParameterizedTest(name = "simpleName: {0}")
    @MethodSource("allPackages")
    void sot_simpleName(String label, Path pkgPath) throws Exception {
        MetadataResult result = extractResult(pkgPath);
        JsonObject expected = loadExpected(pkgPath);
        assertThat(result.simpleName()).isEqualTo(optStr(expected, "simpleName"));
    }

    /**
     * Goal: Verify version matches expected for every real package.
     * Rationale: Version must be extracted exactly.
     */
    @ParameterizedTest(name = "version: {0}")
    @MethodSource("allPackages")
    void sot_version(String label, Path pkgPath) throws Exception {
        MetadataResult result = extractResult(pkgPath);
        JsonObject expected = loadExpected(pkgPath);
        assertThat(result.version()).isEqualTo(optStr(expected, "version"));
    }

    /**
     * Goal: Verify description matches expected for every real package.
     * Rationale: Description must match the native Elixir extraction.
     */
    @ParameterizedTest(name = "description: {0}")
    @MethodSource("allPackages")
    void sot_description(String label, Path pkgPath) throws Exception {
        MetadataResult result = extractResult(pkgPath);
        JsonObject expected = loadExpected(pkgPath);
        assertThat(result.description()).isEqualTo(optStr(expected, "description"));
    }

    /**
     * Goal: Verify license matches expected for every real package.
     * Rationale: Q3 — License list joined with " OR ".
     */
    @ParameterizedTest(name = "license: {0}")
    @MethodSource("allPackages")
    void sot_license(String label, Path pkgPath) throws Exception {
        MetadataResult result = extractResult(pkgPath);
        JsonObject expected = loadExpected(pkgPath);
        assertThat(result.license()).isEqualTo(optStr(expected, "license"));
    }

    /**
     * Goal: Verify publisher is always null.
     * Rationale: Q4 — No publisher field in metadata.config.
     */
    @ParameterizedTest(name = "publisher: {0}")
    @MethodSource("allPackages")
    void sot_publisher(String label, Path pkgPath) throws Exception {
        MetadataResult result = extractResult(pkgPath);
        assertThat(result.publisher()).isEmpty();
    }

    /**
     * Goal: Verify publishedAt is always null.
     * Rationale: Q4 — No timestamp in metadata.config.
     */
    @ParameterizedTest(name = "publishedAt: {0}")
    @MethodSource("allPackages")
    void sot_publishedAt(String label, Path pkgPath) throws Exception {
        MetadataResult result = extractResult(pkgPath);
        assertThat(result.publishedAt()).isEmpty();
    }

    /**
     * Goal: Verify dependency count matches expected for every real package.
     * Rationale: Q5 — Both mix and rebar3 formats must extract all deps.
     */
    @ParameterizedTest(name = "depCount: {0}")
    @MethodSource("allPackages")
    void sot_dependencyCount(String label, Path pkgPath) throws Exception {
        MetadataResult result = extractResult(pkgPath);
        JsonObject expected = loadExpected(pkgPath);
        JsonArray expectedDeps = expected.getAsJsonArray("dependencies");
        assertThat(result.dependencies()).hasSize(expectedDeps.size());
    }

    /**
     * Goal: Verify dependency details match expected for every real package.
     * Rationale: Each dependency name, versionConstraint, scope must match.
     */
    @ParameterizedTest(name = "deps: {0}")
    @MethodSource("allPackages")
    void sot_dependencyDetails(String label, Path pkgPath) throws Exception {
        MetadataResult result = extractResult(pkgPath);
        JsonObject expected = loadExpected(pkgPath);
        JsonArray expectedDeps = expected.getAsJsonArray("dependencies");

        Map<String, JsonObject> expectedMap = new HashMap<>();
        for (JsonElement elem : expectedDeps) {
            JsonObject dep = elem.getAsJsonObject();
            expectedMap.put(dep.get("name").getAsString(), dep);
        }

        for (ParsedDependency dep : result.dependencies()) {
            JsonObject expectedDep = expectedMap.get(dep.name());
            assertThat(expectedDep).as("dep %s not found in expected", dep.name()).isNotNull();
            assertThat(dep.scope()).isEqualTo(optStr(expectedDep, "scope"));
            assertThat(dep.versionConstraint()).isEqualTo(optStr(expectedDep, "versionConstraint"));
        }
    }

    // --- Named package tests ---

    /**
     * Goal: Verify jason (simple Elixir package with one dep).
     * Rationale: Validates basic Elixir mix format parsing.
     */
    @Test
    void package_jason() throws Exception {
        MetadataResult result = extractFromPackage("jason-1.4.1.tar");
        assertThat(result.name()).hasValue("jason");
        assertThat(result.version()).hasValue("1.4.1");
        assertThat(result.license()).hasValue("Apache-2.0");
        assertThat(result.dependencies()).hasSize(1);
        assertThat(result.dependencies().get(0).name()).isEqualTo("decimal");
    }

    /**
     * Goal: Verify phoenix (many deps, popular framework).
     * Rationale: Tests extraction of package with many dependencies.
     */
    @Test
    void package_phoenix() throws Exception {
        MetadataResult result = extractFromPackage("phoenix-1.7.10.tar");
        assertThat(result.name()).hasValue("phoenix");
        assertThat(result.version()).hasValue("1.7.10");
        assertThat(result.license()).hasValue("MIT");
        assertThat(result.dependencies().size()).isGreaterThan(5);
    }

    /**
     * Goal: Verify cowboy (Erlang rebar3 package).
     * Rationale: Q8 — Tests Erlang requirement format (name as outer key).
     */
    @Test
    void package_cowboy_erlangPackage() throws Exception {
        MetadataResult result = extractFromPackage("cowboy-2.12.0.tar");
        assertThat(result.name()).hasValue("cowboy");
        assertThat(result.version()).hasValue("2.12.0");
        assertThat(result.license()).hasValue("ISC");
        assertThat(result.dependencies()).hasSize(2);
        assertThat(result.dependencies().stream().map(ParsedDependency::name))
                .containsExactlyInAnyOrder("cowlib", "ranch");
    }

    /**
     * Goal: Verify telemetry (zero deps).
     * Rationale: Tests package with empty requirements.
     */
    @Test
    void package_telemetry_zeroDeps() throws Exception {
        MetadataResult result = extractFromPackage("telemetry-1.2.1.tar");
        assertThat(result.name()).hasValue("telemetry");
        assertThat(result.dependencies()).isEmpty();
    }

    /**
     * Goal: Verify ranch (zero deps, Erlang package).
     * Rationale: Tests Erlang package with no dependencies.
     */
    @Test
    void package_ranch_erlang() throws Exception {
        MetadataResult result = extractFromPackage("ranch-2.1.0.tar");
        assertThat(result.name()).hasValue("ranch");
        assertThat(result.license()).hasValue("ISC");
        assertThat(result.dependencies()).isEmpty();
    }

    /**
     * Goal: Verify decimal (zero deps, simple Elixir package).
     * Rationale: Tests minimal Elixir package.
     */
    @Test
    void package_decimal() throws Exception {
        MetadataResult result = extractFromPackage("decimal-2.1.1.tar");
        assertThat(result.name()).hasValue("decimal");
        assertThat(result.version()).hasValue("2.1.1");
        assertThat(result.license()).hasValue("Apache-2.0");
        assertThat(result.dependencies()).isEmpty();
    }

    /**
     * Goal: Verify ecto (Elixir database library with many deps).
     * Rationale: Tests a core Elixir package with multiple dependencies.
     */
    @Test
    void package_ecto() throws Exception {
        MetadataResult result = extractFromPackage("ecto-3.11.1.tar");
        assertThat(result.name()).hasValue("ecto");
        assertThat(result.version()).hasValue("3.11.1");
        assertThat(result.license()).hasValue("Apache-2.0");
        assertThat(result.dependencies().size()).isGreaterThan(2);
    }

    /**
     * Goal: Verify hackney (Erlang HTTP client).
     * Rationale: Tests Erlang rebar3 package with deps.
     */
    @Test
    void package_hackney_erlang() throws Exception {
        MetadataResult result = extractFromPackage("hackney-1.20.1.tar");
        assertThat(result.name()).hasValue("hackney");
        assertThat(result.license()).hasValue("Apache-2.0");
        assertThat(result.dependencies().size()).isGreaterThan(0);
    }

    /**
     * Goal: Verify ex_machina (contains /utf8 binary specifier in description).
     * Rationale: Q2 — Tests Erlang binary /utf8 encoding specifier handling.
     */
    @Test
    void package_exMachina_utf8Specifier() throws Exception {
        MetadataResult result = extractFromPackage("ex_machina-2.7.0.tar");
        assertThat(result.name()).hasValue("ex_machina");
        assertThat(result.description()).isPresent();
        assertThat(result.description().get()).contains("FactoryBot");
    }

    /**
     * Goal: Verify poison (simple Elixir JSON library, no deps).
     * Rationale: Tests minimal Elixir package.
     */
    @Test
    void package_poison() throws Exception {
        MetadataResult result = extractFromPackage("poison-5.0.0.tar");
        assertThat(result.name()).hasValue("poison");
        assertThat(result.version()).hasValue("5.0.0");
    }

    // --- Unit tests ---

    /**
     * Goal: Verify license list joined with " OR ".
     * Rationale: Q3 — Multiple licenses must be joined.
     */
    @Test
    void extractLicense_joinedWithOr() {
        Map<String, Object> meta = Map.of("licenses", List.of("MIT", "Apache-2.0"));
        assertThat(HexMetadataExtractor.extractLicense(meta)).hasValue("MIT OR Apache-2.0");
    }

    /**
     * Goal: Verify single license is returned as-is.
     * Rationale: Most packages have a single license.
     */
    @Test
    void extractLicense_single() {
        Map<String, Object> meta = Map.of("licenses", List.of("MIT"));
        assertThat(HexMetadataExtractor.extractLicense(meta)).hasValue("MIT");
    }

    /**
     * Goal: Verify empty license list returns empty.
     * Rationale: Q3 — No licenses → null.
     */
    @Test
    void extractLicense_emptyListReturnsEmpty() {
        Map<String, Object> meta = Map.of("licenses", List.of());
        assertThat(HexMetadataExtractor.extractLicense(meta)).isEmpty();
    }

    /**
     * Goal: Verify missing licenses key returns empty.
     * Rationale: Some packages may omit the licenses field.
     */
    @Test
    void extractLicense_missingKey() {
        Map<String, Object> meta = Map.of("name", "test");
        assertThat(HexMetadataExtractor.extractLicense(meta)).isEmpty();
    }

    /**
     * Goal: Verify all deps are scope "runtime".
     * Rationale: Q5 — Hex has no dev/test dep scoping in metadata.config.
     */
    @Test
    void extractDeps_allRuntime() {
        Map<String, Object> dep = new HashMap<>();
        dep.put("name", "dep1");
        dep.put("requirement", "~> 1.0");
        dep.put("optional", false);
        Map<String, Object> meta = Map.of("requirements", List.of(dep));
        List<ParsedDependency> deps = HexMetadataExtractor.extractDependencies(meta);
        assertThat(deps).hasSize(1);
        assertThat(deps.get(0).scope()).hasValue("runtime");
    }

    /**
     * Goal: Verify Elixir (mix) format requirements.
     * Rationale: Q8 — Mix format has "name" key inside proplist.
     */
    @Test
    void extractDeps_mixFormat() {
        Map<String, Object> dep = new HashMap<>();
        dep.put("name", "phoenix");
        dep.put("requirement", "~> 1.7");
        Map<String, Object> meta = Map.of("requirements", List.of(dep));
        List<ParsedDependency> deps = HexMetadataExtractor.extractDependencies(meta);
        assertThat(deps).hasSize(1);
        assertThat(deps.get(0).name()).isEqualTo("phoenix");
        assertThat(deps.get(0).versionConstraint()).hasValue("~> 1.7");
    }

    /**
     * Goal: Verify Erlang (rebar3) format requirements.
     * Rationale: Q8 — Rebar3 format has dep name as outer map key.
     */
    @Test
    void extractDeps_rebar3Format() {
        Map<String, Object> cowlibAttrs = new HashMap<>();
        cowlibAttrs.put("requirement", "2.13.0");
        Map<String, Object> ranchAttrs = new HashMap<>();
        ranchAttrs.put("requirement", "1.8.0");
        Map<String, Object> reqsMap = new HashMap<>();
        reqsMap.put("cowlib", cowlibAttrs);
        reqsMap.put("ranch", ranchAttrs);
        Map<String, Object> meta = Map.of("requirements", reqsMap);

        List<ParsedDependency> deps = HexMetadataExtractor.extractDependencies(meta);
        assertThat(deps).hasSize(2);
        assertThat(deps.stream().map(ParsedDependency::name))
                .containsExactlyInAnyOrder("cowlib", "ranch");
    }

    /**
     * Goal: Verify empty requirements returns empty list.
     * Rationale: Packages with no deps should produce empty list.
     */
    @Test
    void extractDeps_emptyList() {
        Map<String, Object> meta = Map.of("requirements", List.of());
        assertThat(HexMetadataExtractor.extractDependencies(meta)).isEmpty();
    }

    /**
     * Goal: Verify missing requirements returns empty list.
     * Rationale: Some packages may omit the requirements field entirely.
     */
    @Test
    void extractDeps_missingKey() {
        Map<String, Object> meta = Map.of("name", "test");
        assertThat(HexMetadataExtractor.extractDependencies(meta)).isEmpty();
    }

    /**
     * Goal: Verify deps are sorted by name.
     * Rationale: Deterministic ordering for test comparison.
     */
    @Test
    void extractDeps_sortedByName() {
        Map<String, Object> dep1 = new HashMap<>();
        dep1.put("name", "zebra");
        dep1.put("requirement", "~> 1.0");
        Map<String, Object> dep2 = new HashMap<>();
        dep2.put("name", "alpha");
        dep2.put("requirement", "~> 2.0");
        Map<String, Object> meta = Map.of("requirements", List.of(dep1, dep2));

        List<ParsedDependency> deps = HexMetadataExtractor.extractDependencies(meta);
        assertThat(deps.get(0).name()).isEqualTo("alpha");
        assertThat(deps.get(1).name()).isEqualTo("zebra");
    }

    /**
     * Goal: Verify getOptionalString with present value.
     * Rationale: Helper must return non-empty Optional for present strings.
     */
    @Test
    void getOptionalString_present() {
        Map<String, Object> map = Map.of("key", "value");
        assertThat(HexMetadataExtractor.getOptionalString(map, "key")).hasValue("value");
    }

    /**
     * Goal: Verify getOptionalString with missing key.
     * Rationale: Helper must return empty Optional for missing keys.
     */
    @Test
    void getOptionalString_missingKey() {
        Map<String, Object> map = Map.of("other", "value");
        assertThat(HexMetadataExtractor.getOptionalString(map, "key")).isEmpty();
    }

    /**
     * Goal: Verify getOptionalString with empty string value.
     * Rationale: Empty strings should be treated as absent.
     */
    @Test
    void getOptionalString_emptyString() {
        Map<String, Object> map = new HashMap<>();
        map.put("key", "");
        assertThat(HexMetadataExtractor.getOptionalString(map, "key")).isEmpty();
    }

    /**
     * Goal: Verify getOptionalString with non-string value.
     * Rationale: Non-string values should be treated as absent.
     */
    @Test
    void getOptionalString_nonStringValue() {
        Map<String, Object> map = Map.of("key", 42L);
        assertThat(HexMetadataExtractor.getOptionalString(map, "key")).isEmpty();
    }

    /**
     * Goal: Verify buildMetadataResult from Erlang term input.
     * Rationale: End-to-end test of parsing Erlang term format.
     */
    @Test
    void buildMetadataResult_basicParsing() throws Exception {
        String input = """
                {<<"name">>,<<"test_pkg">>}.
                {<<"version">>,<<"1.0.0">>}.
                {<<"description">>,<<"A test package">>}.
                {<<"licenses">>,[<<"MIT">>]}.
                {<<"requirements">>,[]}.
                """;
        MetadataResult result = HexMetadataExtractor.buildMetadataResult(input);
        assertThat(result.name()).hasValue("test_pkg");
        assertThat(result.version()).hasValue("1.0.0");
        assertThat(result.description()).hasValue("A test package");
        assertThat(result.license()).hasValue("MIT");
        assertThat(result.dependencies()).isEmpty();
        assertThat(result.publisher()).isEmpty();
        assertThat(result.publishedAt()).isEmpty();
    }

    /**
     * Goal: Verify buildMetadataResult with requirements.
     * Rationale: Tests full parsing including mix-format deps.
     */
    @Test
    void buildMetadataResult_withDeps() throws Exception {
        String input = """
                {<<"name">>,<<"my_app">>}.
                {<<"version">>,<<"2.0.0">>}.
                {<<"requirements">>,
                 [[{<<"name">>,<<"phoenix">>},
                   {<<"app">>,<<"phoenix">>},
                   {<<"optional">>,false},
                   {<<"requirement">>,<<"~> 1.7">>},
                   {<<"repository">>,<<"hexpm">>}]]}.
                """;
        MetadataResult result = HexMetadataExtractor.buildMetadataResult(input);
        assertThat(result.name()).hasValue("my_app");
        assertThat(result.dependencies()).hasSize(1);
        assertThat(result.dependencies().get(0).name()).isEqualTo("phoenix");
        assertThat(result.dependencies().get(0).versionConstraint()).hasValue("~> 1.7");
    }

    /**
     * Goal: Verify buildMetadataResult with minimal input.
     * Rationale: Packages with only name/version must parse correctly.
     */
    @Test
    void buildMetadataResult_minimalInput() throws Exception {
        String input = "{<<\"name\">>,<<\"bare\">>}.\n{<<\"version\">>,<<\"0.1.0\">>}.\n";
        MetadataResult result = HexMetadataExtractor.buildMetadataResult(input);
        assertThat(result.name()).hasValue("bare");
        assertThat(result.version()).hasValue("0.1.0");
        assertThat(result.description()).isEmpty();
        assertThat(result.license()).isEmpty();
        assertThat(result.dependencies()).isEmpty();
    }

    // --- Helpers ---

    private MetadataResult extractResult(Path pkgPath) throws Exception {
        try (FileInputStream fis = new FileInputStream(pkgPath.toFile())) {
            String raw = HexMetadataExtractor.extractMetadataConfig(fis,
                    pkgPath.getFileName().toString());
            return HexMetadataExtractor.buildMetadataResult(raw);
        }
    }

    private MetadataResult extractFromPackage(String filename) throws Exception {
        Path pkg = HEX_CORPUS.resolve(filename);
        assumeThat(Files.exists(pkg)).isTrue();
        return extractResult(pkg);
    }

    private JsonObject loadExpected(Path pkgPath) throws Exception {
        Path expectedPath = SourceOfTruth.expectedPathFor(pkgPath, HEX_EXPECTED);
        assumeThat(Files.exists(expectedPath))
                .as("expected JSON for %s must exist", pkgPath.getFileName())
                .isTrue();
        return SourceOfTruth.loadExpected(expectedPath);
    }

    private Optional<String> optStr(JsonObject json, String field) {
        if (json.has(field) && !json.get(field).isJsonNull()) {
            return Optional.of(json.get(field).getAsString());
        }
        return Optional.empty();
    }
}
