/* Copyright 2026 Spice Labs, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License. */

package io.spicelabs.annatto.npm;

import com.google.gson.JsonObject;
import io.spicelabs.annatto.common.MetadataResult;
import io.spicelabs.annatto.common.ParsedDependency;
import io.spicelabs.annatto.testutil.SourceOfTruth;
import io.spicelabs.annatto.testutil.TestCorpusDownloader;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Optional;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assumptions.assumeThat;

/**
 * Tests for {@link NpmMetadataExtractor} comparing extraction results against
 * source-of-truth expected values produced by native Node.js tools in Docker.
 *
 * <p>All test packages are real npm packages downloaded from the npm registry.
 * Expected values were generated by running Docker containers with Node.js
 * that parse the actual package.json from each .tgz archive.</p>
 *
 * <p>Package files (.tgz) are in {@code test-corpus/npm/} (downloaded from
 * public-test-data.spice-labs.dev, gitignored). Source-of-truth expected JSON
 * files are in {@code src/test/resources/npm/} (git-tracked).</p>
 *
 * <p>Covers {@link NpmQuirks} Q1 (scoped packages), Q2 (author formats),
 * Q3 (license formats), Q4 (dependency types), Q5 (registry fields),
 * Q6 (archive structure), Q7 (non-ASCII), Q8 (minimal packages).</p>
 */
class NpmMetadataExtractorTest {

    /** Directory containing real npm .tgz package files (gitignored, downloaded from test data server). */
    private static final Path NPM_CORPUS = TestCorpusDownloader.corpusDir("npm");

    /** Directory containing source-of-truth expected JSON files (git-tracked). */
    private static final Path NPM_EXPECTED = TestCorpusDownloader.expectedDir("npm");

    @BeforeAll
    static void ensureTestPackagesExist() {
        assumeThat(Files.isDirectory(NPM_CORPUS))
                .as("npm test corpus directory must exist with real packages")
                .isTrue();
    }

    // --- Parameterized source-of-truth comparison ---

    /**
     * Provides all .tgz files in the npm corpus directory paired with their expected JSON.
     */
    static Stream<Arguments> realPackages() throws IOException {
        if (!Files.isDirectory(NPM_CORPUS)) {
            return Stream.empty();
        }
        return Files.list(NPM_CORPUS)
                .filter(p -> p.toString().endsWith(".tgz"))
                .sorted()
                .map(tgz -> {
                    Path expected = SourceOfTruth.expectedPathFor(tgz, NPM_EXPECTED);
                    String label = tgz.getFileName().toString();
                    return Arguments.of(label, tgz, expected);
                });
    }

    /**
     * Goal: Verify that the extracted name matches the source-of-truth for every real npm package.
     * Rationale: Name is the most fundamental metadata field; must be exact for all packages.
     */
    @ParameterizedTest(name = "name: {0}")
    @MethodSource("realPackages")
    void extractName_matchesSourceOfTruth(String label, Path tgzPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromTgz(tgzPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.name())
                .isEqualTo(SourceOfTruth.getString(expected, "name"));
    }

    /**
     * Goal: Verify that the extracted simple name matches the source-of-truth.
     * Rationale: Scoped packages (Q1) must have the scope stripped from the simple name.
     */
    @ParameterizedTest(name = "simpleName: {0}")
    @MethodSource("realPackages")
    void extractSimpleName_matchesSourceOfTruth(String label, Path tgzPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromTgz(tgzPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.simpleName())
                .isEqualTo(SourceOfTruth.getString(expected, "simpleName"));
    }

    /**
     * Goal: Verify that the extracted version matches the source-of-truth.
     * Rationale: Version must be extracted as-is from package.json.
     */
    @ParameterizedTest(name = "version: {0}")
    @MethodSource("realPackages")
    void extractVersion_matchesSourceOfTruth(String label, Path tgzPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromTgz(tgzPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.version())
                .isEqualTo(SourceOfTruth.getString(expected, "version"));
    }

    /**
     * Goal: Verify that the extracted description matches the source-of-truth.
     * Rationale: Description is a free-text field that must be preserved verbatim.
     */
    @ParameterizedTest(name = "description: {0}")
    @MethodSource("realPackages")
    void extractDescription_matchesSourceOfTruth(String label, Path tgzPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromTgz(tgzPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.description())
                .isEqualTo(SourceOfTruth.getString(expected, "description"));
    }

    /**
     * Goal: Verify that the extracted license matches the source-of-truth.
     * Rationale: License extraction must handle SPDX strings, object format, and legacy arrays (Q3).
     */
    @ParameterizedTest(name = "license: {0}")
    @MethodSource("realPackages")
    void extractLicense_matchesSourceOfTruth(String label, Path tgzPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromTgz(tgzPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.license())
                .isEqualTo(SourceOfTruth.getString(expected, "license"));
    }

    /**
     * Goal: Verify that the extracted publisher matches the source-of-truth.
     * Rationale: Publisher extraction must handle string format, object format,
     * and maintainers/contributors fallback (Q2).
     */
    @ParameterizedTest(name = "publisher: {0}")
    @MethodSource("realPackages")
    void extractPublisher_matchesSourceOfTruth(String label, Path tgzPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromTgz(tgzPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.publisher())
                .isEqualTo(SourceOfTruth.getString(expected, "publisher"));
    }

    /**
     * Goal: Verify that the extracted dependency count matches the source-of-truth.
     * Rationale: All four dependency types (runtime, dev, peer, optional) must be extracted (Q4).
     */
    @ParameterizedTest(name = "dependencyCount: {0}")
    @MethodSource("realPackages")
    void extractDependencies_countMatchesSourceOfTruth(String label, Path tgzPath, Path expectedPath)
            throws Exception {
        MetadataResult result = extractFromTgz(tgzPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        int expectedCount = expected.getAsJsonArray("dependencies").size();

        assertThat(result.dependencies())
                .hasSize(expectedCount);
    }

    /**
     * Goal: Verify that all extracted dependency names, versions, and scopes match the source-of-truth.
     * Rationale: Dependency extraction must correctly categorize runtime, dev, peer, and optional deps.
     * A package may have the same dependency name in different scopes (e.g., @nestjs/common in both dev and peer),
     * so we use a list-based comparison keyed by (name, scope) tuples.
     */
    @ParameterizedTest(name = "dependencies: {0}")
    @MethodSource("realPackages")
    void extractDependencies_matchSourceOfTruth(String label, Path tgzPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromTgz(tgzPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        var expectedDeps = expected.getAsJsonArray("dependencies");
        // Build list of (name, version, scope) tuples from expected
        List<DepTuple> expectedTuples = new java.util.ArrayList<>();
        for (var elem : expectedDeps) {
            JsonObject depObj = elem.getAsJsonObject();
            String name = depObj.get("name").getAsString();
            String vc = depObj.get("versionConstraint").isJsonNull() ? null
                    : depObj.get("versionConstraint").getAsString();
            String scope = depObj.get("scope").getAsString();
            expectedTuples.add(new DepTuple(name, vc, scope));
        }

        List<DepTuple> actualTuples = result.dependencies().stream()
                .map(d -> new DepTuple(d.name(), d.versionConstraint().orElse(null), d.scope().orElse(null)))
                .toList();

        assertThat(actualTuples)
                .as("dependencies for %s", label)
                .containsExactlyInAnyOrderElementsOf(expectedTuples);
    }

    // --- Specific scoped package tests (Q1) ---

    /**
     * Goal: Verify scoped package @babel/core extracts scope correctly.
     * Rationale: Scoped packages (Q1) must split @scope/name into fullName and simpleName.
     */
    @Test
    void scopedPackage_babelCore_extractsCorrectly() throws Exception {
        Path tgz = NPM_CORPUS.resolve("babel-core-7.24.0.tgz");
        assumeThat(Files.exists(tgz)).isTrue();

        MetadataResult result = extractFromTgz(tgz);

        assertThat(result.name()).hasValue("@babel/core");
        assertThat(result.simpleName()).hasValue("core");
        assertThat(result.version()).hasValue("7.24.0");
    }

    /**
     * Goal: Verify scoped package @angular/core extracts scope correctly.
     * Rationale: Multiple scoped package formats must be handled consistently.
     */
    @Test
    void scopedPackage_angularCore_extractsCorrectly() throws Exception {
        Path tgz = NPM_CORPUS.resolve("angular-core-17.2.0.tgz");
        assumeThat(Files.exists(tgz)).isTrue();

        MetadataResult result = extractFromTgz(tgz);

        assertThat(result.name()).hasValue("@angular/core");
        assertThat(result.simpleName()).hasValue("core");
        assertThat(result.version()).hasValue("17.2.0");
    }

    /**
     * Goal: Verify scoped package @types/node extracts scope correctly.
     * Rationale: @types packages are very common scoped packages on npm.
     */
    @Test
    void scopedPackage_typesNode_extractsCorrectly() throws Exception {
        Path tgz = NPM_CORPUS.resolve("types-node-20.11.16.tgz");
        assumeThat(Files.exists(tgz)).isTrue();

        MetadataResult result = extractFromTgz(tgz);

        assertThat(result.name()).hasValue("@types/node");
        assertThat(result.simpleName()).hasValue("node");
    }

    // --- Unscoped packages ---

    /**
     * Goal: Verify unscoped package lodash extracts correctly.
     * Rationale: Lodash is a minimal-dependency popular package (Q8 aspects).
     */
    @Test
    void unscopedPackage_lodash_extractsCorrectly() throws Exception {
        Path tgz = NPM_CORPUS.resolve("lodash-4.17.21.tgz");
        assumeThat(Files.exists(tgz)).isTrue();

        MetadataResult result = extractFromTgz(tgz);

        assertThat(result.name()).hasValue("lodash");
        assertThat(result.simpleName()).hasValue("lodash");
        assertThat(result.version()).hasValue("4.17.21");
        assertThat(result.license()).hasValue("MIT");
        assertThat(result.publisher()).hasValue("John-David Dalton");
        assertThat(result.dependencies()).isEmpty();
    }

    /**
     * Goal: Verify express extracts with many runtime dependencies.
     * Rationale: Express has 30+ runtime deps - tests large dependency extraction (Q4).
     */
    @Test
    void unscopedPackage_express_hasManyDependencies() throws Exception {
        Path tgz = NPM_CORPUS.resolve("express-4.18.2.tgz");
        assumeThat(Files.exists(tgz)).isTrue();

        MetadataResult result = extractFromTgz(tgz);

        assertThat(result.name()).hasValue("express");
        assertThat(result.publisher()).hasValue("TJ Holowaychuk");

        List<ParsedDependency> runtimeDeps = result.dependencies().stream()
                .filter(d -> d.scope().orElse("").equals("runtime"))
                .toList();
        assertThat(runtimeDeps).hasSizeGreaterThanOrEqualTo(25);
    }

    // --- Author format tests (Q2) ---

    /**
     * Goal: Verify author extraction from string format "Name <email> (url)".
     * Rationale: express has author as string with email and url parts (Q2).
     */
    @Test
    void authorAsString_express_extractsNameOnly() throws Exception {
        Path tgz = NPM_CORPUS.resolve("express-4.18.2.tgz");
        assumeThat(Files.exists(tgz)).isTrue();

        MetadataResult result = extractFromTgz(tgz);

        // TJ Holowaychuk <tj@vision-media.ca> -> "TJ Holowaychuk"
        assertThat(result.publisher()).hasValue("TJ Holowaychuk");
    }

    /**
     * Goal: Verify author extraction when author is absent (null publisher).
     * Rationale: Some packages like chalk 5 have no author field (Q2 fallback).
     */
    @Test
    void authorAbsent_chalk_returnsEmpty() throws Exception {
        Path tgz = NPM_CORPUS.resolve("chalk-5.3.0.tgz");
        assumeThat(Files.exists(tgz)).isTrue();

        MetadataResult result = extractFromTgz(tgz);
        JsonObject expected = SourceOfTruth.loadExpected(SourceOfTruth.expectedPathFor(tgz, NPM_EXPECTED));

        // chalk 5.3.0 has no author, no maintainers in the published package.json
        Optional<String> expectedPublisher = SourceOfTruth.getString(expected, "publisher");
        assertThat(result.publisher()).isEqualTo(expectedPublisher);
    }

    // --- Dependency type tests (Q4) ---

    /**
     * Goal: Verify peer dependencies are extracted from @angular/core.
     * Rationale: Angular uses peerDependencies for rxjs and zone.js (Q4).
     */
    @Test
    void peerDependencies_angularCore_extracted() throws Exception {
        Path tgz = NPM_CORPUS.resolve("angular-core-17.2.0.tgz");
        assumeThat(Files.exists(tgz)).isTrue();

        MetadataResult result = extractFromTgz(tgz);

        List<ParsedDependency> peerDeps = result.dependencies().stream()
                .filter(d -> d.scope().orElse("").equals("peer"))
                .toList();
        assertThat(peerDeps).isNotEmpty();

        List<String> peerNames = peerDeps.stream().map(ParsedDependency::name).toList();
        assertThat(peerNames).contains("rxjs", "zone.js");
    }

    /**
     * Goal: Verify dev-only packages have only dev dependencies.
     * Rationale: minimist has no runtime deps, only devDependencies (Q4).
     */
    @Test
    void devOnlyDeps_minimist_allDev() throws Exception {
        Path tgz = NPM_CORPUS.resolve("minimist-1.2.8.tgz");
        assumeThat(Files.exists(tgz)).isTrue();

        MetadataResult result = extractFromTgz(tgz);

        List<ParsedDependency> runtimeDeps = result.dependencies().stream()
                .filter(d -> d.scope().orElse("").equals("runtime"))
                .toList();
        assertThat(runtimeDeps).isEmpty();

        List<ParsedDependency> devDeps = result.dependencies().stream()
                .filter(d -> d.scope().orElse("").equals("dev"))
                .toList();
        assertThat(devDeps).isNotEmpty();
    }

    // --- extractSimpleName static tests ---

    /**
     * Goal: Verify extractSimpleName handles scoped name.
     * Rationale: Q1 - scoped packages must have scope stripped.
     */
    @Test
    void extractSimpleName_scopedName() {
        assertThat(NpmMetadataExtractor.extractSimpleName("@babel/core")).isEqualTo("core");
        assertThat(NpmMetadataExtractor.extractSimpleName("@angular/core")).isEqualTo("core");
        assertThat(NpmMetadataExtractor.extractSimpleName("@types/node")).isEqualTo("node");
    }

    /**
     * Goal: Verify extractSimpleName returns unscoped names as-is.
     * Rationale: Q1 - unscoped packages are already simple names.
     */
    @Test
    void extractSimpleName_unscopedName() {
        assertThat(NpmMetadataExtractor.extractSimpleName("express")).isEqualTo("express");
        assertThat(NpmMetadataExtractor.extractSimpleName("lodash")).isEqualTo("lodash");
    }

    // --- parsePersonString tests ---

    /**
     * Goal: Verify person string parsing with email and URL.
     * Rationale: Q2 - npm person strings can contain Name <email> (url).
     */
    @Test
    void parsePersonString_fullFormat() {
        assertThat(NpmMetadataExtractor.parsePersonString("Barney Rubble <b@rubble.com> (http://barnyrubble.tumblr.com/)"))
                .hasValue("Barney Rubble");
    }

    /**
     * Goal: Verify person string parsing with email only.
     * Rationale: Q2 - some person strings have only an email.
     */
    @Test
    void parsePersonString_emailOnly() {
        assertThat(NpmMetadataExtractor.parsePersonString("Barney Rubble <b@rubble.com>"))
                .hasValue("Barney Rubble");
    }

    /**
     * Goal: Verify person string parsing with name only.
     * Rationale: Q2 - simplest valid person string.
     */
    @Test
    void parsePersonString_nameOnly() {
        assertThat(NpmMetadataExtractor.parsePersonString("Barney Rubble"))
                .hasValue("Barney Rubble");
    }

    /**
     * Goal: Verify empty person string returns empty.
     * Rationale: Q2 - empty strings should not produce a publisher.
     */
    @Test
    void parsePersonString_empty() {
        assertThat(NpmMetadataExtractor.parsePersonString("")).isEmpty();
        assertThat(NpmMetadataExtractor.parsePersonString("  ")).isEmpty();
    }

    // --- isPackageJson tests (Q6) ---

    /**
     * Goal: Verify standard package/ prefix is recognized.
     * Rationale: Q6 - most npm tarballs use package/ as the root directory.
     */
    @Test
    void isPackageJson_standardPrefix() {
        assertThat(NpmMetadataExtractor.isPackageJson("package/package.json")).isTrue();
    }

    /**
     * Goal: Verify custom directory prefix is recognized.
     * Rationale: Q6 - some packages use the package name as the root directory.
     */
    @Test
    void isPackageJson_customPrefix() {
        assertThat(NpmMetadataExtractor.isPackageJson("my-package/package.json")).isTrue();
    }

    /**
     * Goal: Verify bare package.json at root level is recognized.
     * Rationale: Q6 - edge case where no directory prefix exists.
     */
    @Test
    void isPackageJson_rootLevel() {
        assertThat(NpmMetadataExtractor.isPackageJson("package.json")).isTrue();
    }

    /**
     * Goal: Verify nested package.json files are NOT matched.
     * Rationale: Q6 - only top-level package.json should be used, not node_modules.
     */
    @Test
    void isPackageJson_nestedNotMatched() {
        assertThat(NpmMetadataExtractor.isPackageJson("package/node_modules/foo/package.json")).isFalse();
        assertThat(NpmMetadataExtractor.isPackageJson("package/src/package.json")).isFalse();
    }

    // --- Full extraction pipeline from .tgz (Q6) ---

    /**
     * Goal: Verify full extraction pipeline from .tgz archive works end-to-end.
     * Rationale: Q6 - the full gzip -> tar -> package.json -> parse pipeline must work.
     */
    @Test
    void fullExtraction_lodash_fromTgz() throws Exception {
        Path tgz = NPM_CORPUS.resolve("lodash-4.17.21.tgz");
        assumeThat(Files.exists(tgz)).isTrue();

        try (FileInputStream fis = new FileInputStream(tgz.toFile())) {
            MetadataResult result = NpmMetadataExtractor.extract(fis, "lodash-4.17.21.tgz");
            assertThat(result.name()).hasValue("lodash");
            assertThat(result.version()).hasValue("4.17.21");
        }
    }

    // --- Helper methods ---

    private MetadataResult extractFromTgz(Path tgzPath) throws Exception {
        try (FileInputStream fis = new FileInputStream(tgzPath.toFile())) {
            JsonObject packageJson = NpmMetadataExtractor.extractPackageJson(fis, tgzPath.getFileName().toString());
            return NpmMetadataExtractor.parsePackageJson(packageJson);
        }
    }

    private record DepTuple(String name, String versionConstraint, String scope) {
    }
}
