/* Copyright 2026 Spice Labs, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License. */

package io.spicelabs.annatto.packagist;

import com.google.gson.JsonObject;
import io.spicelabs.annatto.common.MetadataResult;
import io.spicelabs.annatto.common.ParsedDependency;
import io.spicelabs.annatto.testutil.SourceOfTruth;
import io.spicelabs.annatto.testutil.TestCorpusDownloader;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Optional;
import java.util.stream.Stream;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.assertj.core.api.Assumptions.assumeThat;

/**
 * Tests for {@link PackagistMetadataExtractor} comparing extraction results against
 * source-of-truth expected values produced by native PHP tools in Docker.
 *
 * <p>All test packages are real Composer packages downloaded from Packagist dist URLs.
 * Expected values were generated by running Docker containers with PHP that
 * parse the actual composer.json from each archive.</p>
 *
 * <p>Package files (.zip) are in {@code test-corpus/packagist/} (gitignored).
 * Source-of-truth expected JSON files are in {@code src/test/resources/packagist/} (git-tracked).</p>
 *
 * <p>Covers {@link PackagistQuirks} Q1 (version absence), Q2 (vendor/package naming),
 * Q3 (require vs require-dev + platform filtering), Q4 (replace/provide ignored),
 * Q5 (metadata-only registry), Q6 (license formats).</p>
 *
 * <p><b>Floor Comparison:</b> Some tests use a "floor" comparison where the ground truth
 * is the minimum expected value. If the tool extracts more information than the ground truth
 * (e.g., more dependencies), the test passes. However, if the ground truth has more information
 * than what the tool generates, that is a hard test failure. This approach accommodates
 * variations in how different tools extract metadata while ensuring the extractor meets
 * a baseline of correctness.</p>
 */
class PackagistMetadataExtractorTest {

    /** Directory containing real .zip files (gitignored). */
    private static final Path PACKAGIST_CORPUS = TestCorpusDownloader.corpusDir("packagist");

    /** Directory containing source-of-truth expected JSON files (git-tracked). */
    private static final Path PACKAGIST_EXPECTED = TestCorpusDownloader.expectedDir("packagist");

    @BeforeAll
    static void ensureTestPackagesExist() {
        assumeThat(Files.isDirectory(PACKAGIST_CORPUS))
                .as("packagist test corpus directory must exist with real packages")
                .isTrue();
    }

    // --- Parameterized source-of-truth comparison ---

    /**
     * Provides all .zip files in the corpus directory paired with their expected JSON.
     */
    static Stream<Arguments> realPackages() throws IOException {
        if (!Files.isDirectory(PACKAGIST_CORPUS)) {
            return Stream.empty();
        }
        return Files.list(PACKAGIST_CORPUS)
                .filter(p -> p.toString().endsWith(".zip"))
                .sorted()
                .map(pkg -> {
                    Path expected = SourceOfTruth.expectedPathFor(pkg, PACKAGIST_EXPECTED);
                    String label = pkg.getFileName().toString();
                    return Arguments.of(label, pkg, expected);
                });
    }

    /**
     * Goal: Verify that the extracted name matches the source-of-truth for every real package.
     * Rationale: Name is the most fundamental metadata field; must be exact for all packages (Q2).
     */
    @ParameterizedTest(name = "name: {0}")
    @MethodSource("realPackages")
    void extractName_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.name())
                .isEqualTo(SourceOfTruth.getString(expected, "name"));
    }

    /**
     * Goal: Verify that the extracted simple name matches the source-of-truth.
     * Rationale: Q2 — simpleName is the part after / in vendor/package.
     */
    @ParameterizedTest(name = "simpleName: {0}")
    @MethodSource("realPackages")
    void extractSimpleName_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.simpleName())
                .isEqualTo(SourceOfTruth.getString(expected, "simpleName"));
    }

    /**
     * Goal: Verify that the extracted version matches the source-of-truth.
     * Rationale: Q1 — version is usually absent from composer.json; must be null when absent.
     */
    @ParameterizedTest(name = "version: {0}")
    @MethodSource("realPackages")
    void extractVersion_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.version())
                .isEqualTo(SourceOfTruth.getString(expected, "version"));
    }

    /**
     * Goal: Verify that the extracted description matches the source-of-truth.
     * Rationale: Description is optional; some packages have it, some don't.
     */
    @ParameterizedTest(name = "description: {0}")
    @MethodSource("realPackages")
    void extractDescription_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        // Floor test: if ground truth has real value, match it
        Optional<String> expectedDesc = SourceOfTruth.getString(expected, "description");
        if (expectedDesc.isPresent() && !expectedDesc.get().isEmpty()
                && !"unknown".equalsIgnoreCase(expectedDesc.get())) {
            assertThat(result.description()).as("description for %s", label).isEqualTo(expectedDesc);
        }
    }

    /**
     * Goal: Verify that the extracted license matches the source-of-truth.
     * Rationale: Q6 — license can be string, array, or null.
     */
    @ParameterizedTest(name = "license: {0}")
    @MethodSource("realPackages")
    void extractLicense_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        // Floor test: if ground truth has real value, match it
        Optional<String> expectedLicense = SourceOfTruth.getString(expected, "license");
        if (expectedLicense.isPresent() && !expectedLicense.get().isEmpty()
                && !"unknown".equalsIgnoreCase(expectedLicense.get())) {
            assertThat(result.license()).as("license for %s", label).isEqualTo(expectedLicense);
        }
    }

    /**
     * Goal: Verify that the extracted publisher matches the source-of-truth.
     * Rationale: Publisher is first author's name, or null if no authors.
     */
    @ParameterizedTest(name = "publisher: {0}")
    @MethodSource("realPackages")
    void extractPublisher_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        // Floor test: if ground truth has real value, match it
        Optional<String> expectedPublisher = SourceOfTruth.getString(expected, "publisher");
        if (expectedPublisher.isPresent() && !expectedPublisher.get().isEmpty()
                && !"unknown".equalsIgnoreCase(expectedPublisher.get())) {
            assertThat(result.publisher()).as("publisher for %s", label).isEqualTo(expectedPublisher);
        }
    }

    /**
     * Goal: Verify that the extracted dependency count matches the source-of-truth.
     * Rationale: All dependency sections must be parsed correctly, platform deps excluded (Q3).
     */
    @ParameterizedTest(name = "dependencyCount: {0}")
    @MethodSource("realPackages")
    void extractDependencyCount_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath)
            throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        int expectedCount = expected.getAsJsonArray("dependencies").size();

        assertThat(result.dependencies())
                .as("dependency count for %s", label)
                .hasSize(expectedCount);
    }

    /**
     * Goal: Verify that all extracted dependency names, versions, and scopes match the source-of-truth.
     * Rationale: Dependency extraction must correctly parse require/require-dev and filter platform deps (Q3).
     */
    @ParameterizedTest(name = "dependencies: {0}")
    @MethodSource("realPackages")
    void extractDependencies_matchSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        var expectedDeps = expected.getAsJsonArray("dependencies");
        List<DepTuple> expectedTuples = new java.util.ArrayList<>();
        for (var elem : expectedDeps) {
            JsonObject depObj = elem.getAsJsonObject();
            String name = depObj.get("name").getAsString();
            String vc = depObj.get("versionConstraint").isJsonNull() ? null
                    : depObj.get("versionConstraint").getAsString();
            String scope = depObj.get("scope").getAsString();
            expectedTuples.add(new DepTuple(name, vc, scope));
        }

        List<DepTuple> actualTuples = result.dependencies().stream()
                .map(d -> new DepTuple(d.name(), d.versionConstraint().orElse(null), d.scope().orElse(null)))
                .toList();

        assertThat(actualTuples)
                .as("dependencies for %s (must contain all ground truth)", label)
                .containsAll(expectedTuples);
    }

    // --- Named package tests ---

    /**
     * Goal: Verify extraction for monolog (popular, runtime deps).
     * Rationale: monolog has 1 runtime dep (psr/log) and many dev deps; version absent (Q1).
     */
    @Test
    void package_monolog_runtimeDeps() throws Exception {
        Path pkg = PACKAGIST_CORPUS.resolve("monolog-monolog-3.5.0.zip");
        assumeThat(Files.exists(pkg)).isTrue();

        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.name()).hasValue("monolog/monolog");
        assertThat(result.simpleName()).hasValue("monolog");
        assertThat(result.version()).hasValue("3.5.0"); // Extracted from filename (Q1)
        assertThat(result.license()).hasValue("MIT");
        assertThat(result.publisher()).hasValue("Jordi Boggiano");
        assertThat(result.dependencies().stream()
                .filter(d -> d.name().equals("psr/log") && d.scope().orElse("").equals("runtime"))
                .findAny()).isPresent();
    }

    /**
     * Goal: Verify extraction for psr/log (zero dependencies PSR interface).
     * Rationale: Minimal metadata package with zero dependencies.
     */
    @Test
    void package_psr_log_zeroDeps() throws Exception {
        Path pkg = PACKAGIST_CORPUS.resolve("psr-log-3.0.0.zip");
        assumeThat(Files.exists(pkg)).isTrue();

        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.name()).hasValue("psr/log");
        assertThat(result.simpleName()).hasValue("log");
        assertThat(result.dependencies()).isEmpty();
    }

    /**
     * Goal: Verify extraction for phpunit (many runtime deps in require section).
     * Rationale: phpunit has all deps in require (not require-dev), all scope=runtime.
     */
    @Test
    void package_phpunit_runtimeDeps() throws Exception {
        Path pkg = PACKAGIST_CORPUS.resolve("phpunit-phpunit-11.0.4.zip");
        assumeThat(Files.exists(pkg)).isTrue();

        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.name()).hasValue("phpunit/phpunit");
        assertThat(result.publisher()).hasValue("Sebastian Bergmann");
        // All deps should be runtime
        assertThat(result.dependencies().stream()
                .allMatch(d -> d.scope().orElse("").equals("runtime"))).isTrue();
        assertThat(result.dependencies()).hasSizeGreaterThan(10);
    }

    /**
     * Goal: Verify platform deps (php, ext-*) are excluded from symfony/console.
     * Rationale: Q3 — platform requirements must be filtered out.
     */
    @Test
    void package_symfony_console_platformDepsFiltered() throws Exception {
        Path pkg = PACKAGIST_CORPUS.resolve("symfony-console-v7.0.3.zip");
        assumeThat(Files.exists(pkg)).isTrue();

        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.name()).hasValue("symfony/console");
        // Platform deps (php, ext-*) must NOT appear
        assertThat(result.dependencies().stream()
                .noneMatch(d -> PackagistMetadataExtractor.isPlatformDependency(d.name()))).isTrue();
        // But real deps should be present
        assertThat(result.dependencies().stream()
                .filter(d -> d.name().equals("symfony/string") && d.scope().orElse("").equals("runtime"))
                .findAny()).isPresent();
    }

    /**
     * Goal: Verify extraction for guzzle (many runtime deps).
     * Rationale: guzzle has several real runtime deps.
     */
    @Test
    void package_guzzle_manyDeps() throws Exception {
        Path pkg = PACKAGIST_CORPUS.resolve("guzzlehttp-guzzle-7.8.1.zip");
        assumeThat(Files.exists(pkg)).isTrue();

        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.name()).hasValue("guzzlehttp/guzzle");
        assertThat(result.simpleName()).hasValue("guzzle");
        long runtimeCount = result.dependencies().stream()
                .filter(d -> d.scope().orElse("").equals("runtime")).count();
        assertThat(runtimeCount).isGreaterThanOrEqualTo(3);
    }

    /**
     * Goal: Verify extraction for doctrine/orm (complex version constraints).
     * Rationale: doctrine/orm has complex constraints like "^3.6 || ^4".
     */
    @Test
    void package_doctrine_orm_complexConstraints() throws Exception {
        Path pkg = PACKAGIST_CORPUS.resolve("doctrine-orm-3.0.0.zip");
        assumeThat(Files.exists(pkg)).isTrue();

        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.name()).hasValue("doctrine/orm");
        assertThat(result.publisher()).hasValue("Guilherme Blanco");
        // Check a dep with complex constraint
        assertThat(result.dependencies().stream()
                .filter(d -> d.name().equals("doctrine/dbal"))
                .findAny()
                .flatMap(d -> d.versionConstraint())).hasValue("^3.6 || ^4");
    }

    /**
     * Goal: Verify extraction for twig (multiple authors, first taken as publisher).
     * Rationale: Publisher should be the first author in the array.
     */
    @Test
    void package_twig_multipleAuthors() throws Exception {
        Path pkg = PACKAGIST_CORPUS.resolve("twig-twig-v3.8.0.zip");
        assumeThat(Files.exists(pkg)).isTrue();

        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.name()).hasValue("twig/twig");
        assertThat(result.publisher()).hasValue("Fabien Potencier");
    }

    /**
     * Goal: Verify extraction for league/flysystem (license as string).
     * Rationale: Q6 — license can be a plain string.
     */
    @Test
    void package_league_flysystem_licenseString() throws Exception {
        Path pkg = PACKAGIST_CORPUS.resolve("league-flysystem-3.24.0.zip");
        assumeThat(Files.exists(pkg)).isTrue();

        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.name()).hasValue("league/flysystem");
        assertThat(result.license()).hasValue("MIT");
        assertThat(result.publisher()).hasValue("Frank de Jonge");
    }

    /**
     * Goal: Verify extraction for psr/container (minimal metadata).
     * Rationale: PSR packages have minimal metadata and zero deps.
     */
    @Test
    void package_psr_container_minimalMetadata() throws Exception {
        Path pkg = PACKAGIST_CORPUS.resolve("psr-container-2.0.2.zip");
        assumeThat(Files.exists(pkg)).isTrue();

        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.name()).hasValue("psr/container");
        assertThat(result.simpleName()).hasValue("container");
        assertThat(result.version()).hasValue("2.0.2"); // Extracted from filename (Q1)
        assertThat(result.dependencies()).isEmpty();
    }

    /**
     * Goal: Verify extraction for ramsey/uuid (mix of platform and real deps).
     * Rationale: Q3 — ramsey/uuid requires php and ext-* which must be filtered.
     */
    @Test
    void package_ramsey_uuid_platformAndRealDeps() throws Exception {
        Path pkg = PACKAGIST_CORPUS.resolve("ramsey-uuid-4.7.5.zip");
        assumeThat(Files.exists(pkg)).isTrue();

        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.name()).hasValue("ramsey/uuid");
        // Platform deps excluded
        assertThat(result.dependencies().stream()
                .noneMatch(d -> PackagistMetadataExtractor.isPlatformDependency(d.name()))).isTrue();
        // Real runtime dep present
        assertThat(result.dependencies().stream()
                .filter(d -> d.name().equals("brick/math") && d.scope().orElse("").equals("runtime"))
                .findAny()).isPresent();
    }

    /**
     * Goal: Verify that packages without version in composer.json extract version from filename.
     * Rationale: Q1 — most Composer packages omit version; we extract from filename as fallback.
     */
    @Test
    void package_version_extractedFromFilename() throws Exception {
        Path pkg = PACKAGIST_CORPUS.resolve("monolog-monolog-3.5.0.zip");
        assumeThat(Files.exists(pkg)).isTrue();

        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.version()).hasValue("3.5.0");
    }

    /**
     * Goal: Verify no-author package produces empty publisher.
     * Rationale: Some packages have no authors array.
     */
    @Test
    void package_ramsey_uuid_noPublisher() throws Exception {
        Path pkg = PACKAGIST_CORPUS.resolve("ramsey-uuid-4.7.5.zip");
        assumeThat(Files.exists(pkg)).isTrue();

        MetadataResult result = extractFromPackage(pkg);

        // ramsey/uuid's composer.json has authors as contributors, not in authors[]
        assertThat(result.publisher()).isEmpty();
    }

    // --- Unit tests for isComposerJson ---

    /**
     * Goal: Verify root-level composer.json is recognized.
     * Rationale: Some zip archives have composer.json at root level.
     */
    @Test
    void isComposerJson_rootLevel() {
        assertThat(PackagistMetadataExtractor.isComposerJson("composer.json")).isTrue();
    }

    /**
     * Goal: Verify one-level-deep composer.json is recognized.
     * Rationale: GitHub zipballs put files under a directory prefix.
     */
    @Test
    void isComposerJson_oneLevelDeep() {
        assertThat(PackagistMetadataExtractor.isComposerJson("vendor-hash123/composer.json")).isTrue();
    }

    /**
     * Goal: Verify deeply nested composer.json is NOT recognized.
     * Rationale: Only root or one-level-deep should match.
     */
    @Test
    void isComposerJson_tooDeep_rejected() {
        assertThat(PackagistMetadataExtractor.isComposerJson("a/b/composer.json")).isFalse();
        assertThat(PackagistMetadataExtractor.isComposerJson("a/b/c/composer.json")).isFalse();
    }

    /**
     * Goal: Verify path traversal entries are rejected.
     * Rationale: Security — entries with ".." must be rejected.
     */
    @Test
    void isComposerJson_pathTraversal_rejected() {
        assertThat(PackagistMetadataExtractor.isComposerJson("../composer.json")).isFalse();
        assertThat(PackagistMetadataExtractor.isComposerJson("dir/../composer.json")).isFalse();
    }

    /**
     * Goal: Verify backslash normalization.
     * Rationale: Windows-style paths should be handled.
     */
    @Test
    void isComposerJson_backslashNormalization() {
        assertThat(PackagistMetadataExtractor.isComposerJson("dir\\composer.json")).isTrue();
    }

    // --- Unit tests for extractSimpleName ---

    /**
     * Goal: Verify vendor/name produces the name part.
     * Rationale: Q2 — simpleName is the part after /.
     */
    @Test
    void extractSimpleName_vendorSlashName() {
        assertThat(PackagistMetadataExtractor.extractSimpleName("monolog/monolog")).isEqualTo("monolog");
        assertThat(PackagistMetadataExtractor.extractSimpleName("symfony/console")).isEqualTo("console");
    }

    /**
     * Goal: Verify name without / returns as-is.
     * Rationale: Edge case — no vendor prefix.
     */
    @Test
    void extractSimpleName_noSlash() {
        assertThat(PackagistMetadataExtractor.extractSimpleName("justname")).isEqualTo("justname");
    }

    /**
     * Goal: Verify multiple slashes use last segment.
     * Rationale: Edge case with unusual naming.
     */
    @Test
    void extractSimpleName_multipleSlashes() {
        assertThat(PackagistMetadataExtractor.extractSimpleName("a/b/c")).isEqualTo("c");
    }

    // --- Unit tests for extractLicense ---

    /**
     * Goal: Verify license as string.
     * Rationale: Q6 — license can be a plain string.
     */
    @Test
    void extractLicense_string() {
        JsonObject json = new JsonObject();
        json.addProperty("license", "MIT");
        assertThat(PackagistMetadataExtractor.extractLicense(json)).hasValue("MIT");
    }

    /**
     * Goal: Verify license as single-element array.
     * Rationale: Q6 — license can be an array.
     */
    @Test
    void extractLicense_arraySingle() {
        JsonObject json = new JsonObject();
        com.google.gson.JsonArray arr = new com.google.gson.JsonArray();
        arr.add("MIT");
        json.add("license", arr);
        assertThat(PackagistMetadataExtractor.extractLicense(json)).hasValue("MIT");
    }

    /**
     * Goal: Verify license as multi-element array joined with " OR ".
     * Rationale: Q6 — multiple licenses joined.
     */
    @Test
    void extractLicense_arrayMultiple() {
        JsonObject json = new JsonObject();
        com.google.gson.JsonArray arr = new com.google.gson.JsonArray();
        arr.add("MIT");
        arr.add("GPL-3.0");
        json.add("license", arr);
        assertThat(PackagistMetadataExtractor.extractLicense(json)).hasValue("MIT OR GPL-3.0");
    }

    /**
     * Goal: Verify absent license returns empty.
     * Rationale: Q6 — some packages have no license field.
     */
    @Test
    void extractLicense_absent() {
        JsonObject json = new JsonObject();
        assertThat(PackagistMetadataExtractor.extractLicense(json)).isEmpty();
    }

    // --- Unit tests for extractPublisher ---

    /**
     * Goal: Verify single author extracted as publisher.
     * Rationale: Publisher is first author's name.
     */
    @Test
    void extractPublisher_singleAuthor() {
        JsonObject json = buildJsonWithAuthors("Alice");
        assertThat(PackagistMetadataExtractor.extractPublisher(json)).hasValue("Alice");
    }

    /**
     * Goal: Verify multiple authors — first wins.
     * Rationale: Publisher is the first author only.
     */
    @Test
    void extractPublisher_multipleAuthors_usesFirst() {
        String jsonStr = """
                {"authors": [{"name": "Alice"}, {"name": "Bob"}]}
                """;
        JsonObject json = com.google.gson.JsonParser.parseString(jsonStr).getAsJsonObject();
        assertThat(PackagistMetadataExtractor.extractPublisher(json)).hasValue("Alice");
    }

    /**
     * Goal: Verify no authors produces empty.
     * Rationale: Some packages have no authors field.
     */
    @Test
    void extractPublisher_noAuthors() {
        JsonObject json = new JsonObject();
        assertThat(PackagistMetadataExtractor.extractPublisher(json)).isEmpty();
    }

    /**
     * Goal: Verify empty authors array produces empty.
     * Rationale: An empty authors array should be treated as no authors.
     */
    @Test
    void extractPublisher_emptyAuthorsArray() {
        String jsonStr = """
                {"authors": []}
                """;
        JsonObject json = com.google.gson.JsonParser.parseString(jsonStr).getAsJsonObject();
        assertThat(PackagistMetadataExtractor.extractPublisher(json)).isEmpty();
    }

    // --- Unit tests for extractDependencies ---

    /**
     * Goal: Verify require section maps to scope "runtime".
     * Rationale: Q3 — require deps are runtime.
     */
    @Test
    void extractDependencies_requireIsRuntime() {
        String jsonStr = """
                {"require": {"monolog/monolog": "^3.0"}}
                """;
        JsonObject json = com.google.gson.JsonParser.parseString(jsonStr).getAsJsonObject();
        List<ParsedDependency> deps = PackagistMetadataExtractor.extractDependencies(json);

        assertThat(deps).hasSize(1);
        assertThat(deps.get(0).name()).isEqualTo("monolog/monolog");
        assertThat(deps.get(0).versionConstraint()).hasValue("^3.0");
        assertThat(deps.get(0).scope()).hasValue("runtime");
    }

    /**
     * Goal: Verify require-dev section maps to scope "dev".
     * Rationale: Q3 — require-dev deps are dev.
     */
    @Test
    void extractDependencies_requireDevIsDev() {
        String jsonStr = """
                {"require-dev": {"phpunit/phpunit": "^10.0"}}
                """;
        JsonObject json = com.google.gson.JsonParser.parseString(jsonStr).getAsJsonObject();
        List<ParsedDependency> deps = PackagistMetadataExtractor.extractDependencies(json);

        assertThat(deps).hasSize(1);
        assertThat(deps.get(0).name()).isEqualTo("phpunit/phpunit");
        assertThat(deps.get(0).scope()).hasValue("dev");
    }

    /**
     * Goal: Verify platform deps (php) are filtered.
     * Rationale: Q3 — "php" is a platform requirement, not a real package.
     */
    @Test
    void extractDependencies_platformDepsFiltered() {
        String jsonStr = """
                {"require": {"php": ">=8.1", "ext-json": "*", "monolog/monolog": "^3.0"}}
                """;
        JsonObject json = com.google.gson.JsonParser.parseString(jsonStr).getAsJsonObject();
        List<ParsedDependency> deps = PackagistMetadataExtractor.extractDependencies(json);

        assertThat(deps).hasSize(1);
        assertThat(deps.get(0).name()).isEqualTo("monolog/monolog");
    }

    /**
     * Goal: Verify empty require section produces empty list.
     * Rationale: No dependencies should be extracted from empty sections.
     */
    @Test
    void extractDependencies_emptySection() {
        String jsonStr = """
                {"require": {}}
                """;
        JsonObject json = com.google.gson.JsonParser.parseString(jsonStr).getAsJsonObject();
        List<ParsedDependency> deps = PackagistMetadataExtractor.extractDependencies(json);

        assertThat(deps).isEmpty();
    }

    /**
     * Goal: Verify both require and require-dev are combined.
     * Rationale: Dependencies from both sections should appear.
     */
    @Test
    void extractDependencies_bothSections() {
        String jsonStr = """
                {"require": {"psr/log": "^3.0"}, "require-dev": {"phpunit/phpunit": "^10.0"}}
                """;
        JsonObject json = com.google.gson.JsonParser.parseString(jsonStr).getAsJsonObject();
        List<ParsedDependency> deps = PackagistMetadataExtractor.extractDependencies(json);

        assertThat(deps).hasSize(2);
        assertThat(deps.stream().map(ParsedDependency::name).toList())
                .containsExactlyInAnyOrder("psr/log", "phpunit/phpunit");
    }

    /**
     * Goal: Verify wildcard constraint ("*") is preserved.
     * Rationale: Some deps use "*" as version constraint.
     */
    @Test
    void extractDependencies_wildcardConstraintPreserved() {
        String jsonStr = """
                {"require": {"some/package": "*"}}
                """;
        JsonObject json = com.google.gson.JsonParser.parseString(jsonStr).getAsJsonObject();
        List<ParsedDependency> deps = PackagistMetadataExtractor.extractDependencies(json);

        assertThat(deps).hasSize(1);
        assertThat(deps.get(0).versionConstraint()).hasValue("*");
    }

    // --- Unit tests for isPlatformDependency ---

    /**
     * Goal: Verify "php" is a platform dependency.
     * Rationale: Q3 — php runtime is not a real package.
     */
    @Test
    void isPlatformDependency_php() {
        assertThat(PackagistMetadataExtractor.isPlatformDependency("php")).isTrue();
    }

    /**
     * Goal: Verify "ext-*" is a platform dependency.
     * Rationale: Q3 — PHP extensions are not real packages.
     */
    @Test
    void isPlatformDependency_ext() {
        assertThat(PackagistMetadataExtractor.isPlatformDependency("ext-json")).isTrue();
        assertThat(PackagistMetadataExtractor.isPlatformDependency("ext-mbstring")).isTrue();
    }

    /**
     * Goal: Verify "lib-*" is a platform dependency.
     * Rationale: Q3 — lib-* entries reference system libraries.
     */
    @Test
    void isPlatformDependency_lib() {
        assertThat(PackagistMetadataExtractor.isPlatformDependency("lib-libxml")).isTrue();
    }

    /**
     * Goal: Verify "composer-plugin-api" is a platform dependency.
     * Rationale: Q3 — Composer API requirements are not real packages.
     */
    @Test
    void isPlatformDependency_composerPluginApi() {
        assertThat(PackagistMetadataExtractor.isPlatformDependency("composer-plugin-api")).isTrue();
        assertThat(PackagistMetadataExtractor.isPlatformDependency("composer-runtime-api")).isTrue();
    }

    /**
     * Goal: Verify normal package names are NOT platform deps.
     * Rationale: Real packages must not be filtered.
     */
    @Test
    void isPlatformDependency_normalPackage() {
        assertThat(PackagistMetadataExtractor.isPlatformDependency("monolog/monolog")).isFalse();
        assertThat(PackagistMetadataExtractor.isPlatformDependency("psr/log")).isFalse();
    }

    // --- Malformed edge cases ---

    /**
     * Goal: Verify that a zip with no composer.json throws MalformedPackageException.
     * Rationale: Must clearly indicate when the archive has no manifest.
     */
    @Test
    void extractComposerJsonFromZip_noComposerJson_throws() {
        byte[] zipBytes = createZipWithEntry("README.md", "# Hello");
        ByteArrayInputStream bis = new ByteArrayInputStream(zipBytes);

        assertThatThrownBy(() -> PackagistMetadataExtractor.extractComposerJsonFromZip(bis, "test.zip"))
                .isInstanceOf(io.spicelabs.annatto.AnnattoException.MalformedPackageException.class);
    }

    /**
     * Goal: Verify that corrupt JSON throws MetadataExtractionException.
     * Rationale: Must handle invalid JSON gracefully.
     */
    @Test
    void buildMetadataResult_corruptJson_throws() {
        PackagistMetadataExtractor.ComposerJsonData data =
                new PackagistMetadataExtractor.ComposerJsonData("{not valid json");

        assertThatThrownBy(() -> PackagistMetadataExtractor.buildMetadataResult(data, "test.zip"))
                .isInstanceOf(io.spicelabs.annatto.AnnattoException.MetadataExtractionException.class);
    }

    /**
     * Goal: Verify that an empty zip throws MalformedPackageException.
     * Rationale: An empty zip has no entries, so no composer.json.
     */
    @Test
    void extractComposerJsonFromZip_emptyZip_throws() {
        byte[] zipBytes = createEmptyZip();
        ByteArrayInputStream bis = new ByteArrayInputStream(zipBytes);

        assertThatThrownBy(() -> PackagistMetadataExtractor.extractComposerJsonFromZip(bis, "empty.zip"))
                .isInstanceOf(io.spicelabs.annatto.AnnattoException.MalformedPackageException.class);
    }

    // --- Helper methods ---

    private MetadataResult extractFromPackage(Path pkgPath) throws Exception {
        try (FileInputStream fis = new FileInputStream(pkgPath.toFile())) {
            return PackagistMetadataExtractor.extract(fis, pkgPath.getFileName().toString());
        }
    }

    private JsonObject buildJsonWithAuthors(String... names) {
        com.google.gson.JsonArray authors = new com.google.gson.JsonArray();
        for (String name : names) {
            JsonObject author = new JsonObject();
            author.addProperty("name", name);
            authors.add(author);
        }
        JsonObject json = new JsonObject();
        json.add("authors", authors);
        return json;
    }

    private byte[] createZipWithEntry(String entryName, String content) {
        try {
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            try (ZipOutputStream zos = new ZipOutputStream(baos)) {
                zos.putNextEntry(new ZipEntry(entryName));
                zos.write(content.getBytes(StandardCharsets.UTF_8));
                zos.closeEntry();
            }
            return baos.toByteArray();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    private byte[] createEmptyZip() {
        try {
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            try (ZipOutputStream zos = new ZipOutputStream(baos)) {
                // empty zip
            }
            return baos.toByteArray();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    private record DepTuple(String name, String versionConstraint, String scope) {
    }
}
