/* Copyright 2026 Spice Labs, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License. */

package io.spicelabs.annatto.pypi;

import com.google.gson.JsonObject;
import io.spicelabs.annatto.common.MetadataResult;
import io.spicelabs.annatto.common.ParsedDependency;
import io.spicelabs.annatto.testutil.SourceOfTruth;
import io.spicelabs.annatto.testutil.TestCorpusDownloader;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assumptions.assumeThat;

/**
 * Tests for {@link PypiMetadataExtractor} comparing extraction results against
 * source-of-truth expected values produced by native Python tools in Docker.
 *
 * <p>All test packages are real PyPI packages downloaded from the PyPI registry.
 * Expected values were generated by running Docker containers with Python
 * that parse the actual METADATA/PKG-INFO from each archive.</p>
 *
 * <p>Package files (.whl/.tar.gz) are in {@code test-corpus/pypi/} (downloaded from
 * public-test-data.spice-labs.dev, gitignored). Source-of-truth expected JSON
 * files are in {@code src/test/resources/pypi/} (git-tracked).</p>
 *
 * <p>Covers {@link PypiQuirks} Q1 (name normalization), Q2 (sdist vs wheel),
 * Q4 (RFC 822 headers), Q5 (license classifiers), Q6 (author-email format),
 * Q7 (environment markers), Q8 (minimal packages).</p>
 */
class PypiMetadataExtractorTest {

    /** Directory containing real PyPI package files (gitignored, downloaded from test data server). */
    private static final Path PYPI_CORPUS = TestCorpusDownloader.corpusDir("pypi");

    /** Directory containing source-of-truth expected JSON files (git-tracked). */
    private static final Path PYPI_EXPECTED = TestCorpusDownloader.expectedDir("pypi");

    @BeforeAll
    static void ensureTestPackagesExist() {
        assumeThat(Files.isDirectory(PYPI_CORPUS))
                .as("pypi test corpus directory must exist with real packages")
                .isTrue();
    }

    // --- Parameterized source-of-truth comparison ---

    /**
     * Provides all .whl and .tar.gz files in the pypi corpus directory paired with their expected JSON.
     */
    static Stream<Arguments> realPackages() throws IOException {
        if (!Files.isDirectory(PYPI_CORPUS)) {
            return Stream.empty();
        }
        return Files.list(PYPI_CORPUS)
                .filter(p -> p.toString().endsWith(".whl") || p.toString().endsWith(".tar.gz"))
                .sorted()
                .map(pkg -> {
                    Path expected = SourceOfTruth.expectedPathFor(pkg, PYPI_EXPECTED);
                    String label = pkg.getFileName().toString();
                    return Arguments.of(label, pkg, expected);
                });
    }

    /**
     * Goal: Verify that the extracted name matches the source-of-truth for every real PyPI package.
     * Rationale: Name is the most fundamental metadata field; must be exact for all packages.
     */
    @ParameterizedTest(name = "name: {0}")
    @MethodSource("realPackages")
    void extractName_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.name())
                .isEqualTo(SourceOfTruth.getString(expected, "name"));
    }

    /**
     * Goal: Verify that the extracted simple name matches the source-of-truth.
     * Rationale: PyPI has no namespace concept, so simpleName == name.
     */
    @ParameterizedTest(name = "simpleName: {0}")
    @MethodSource("realPackages")
    void extractSimpleName_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.simpleName())
                .isEqualTo(SourceOfTruth.getString(expected, "simpleName"));
    }

    /**
     * Goal: Verify that the extracted version matches the source-of-truth.
     * Rationale: Version must be extracted as-is from the metadata.
     */
    @ParameterizedTest(name = "version: {0}")
    @MethodSource("realPackages")
    void extractVersion_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.version())
                .isEqualTo(SourceOfTruth.getString(expected, "version"));
    }

    /**
     * Goal: Verify that the extracted description matches the source-of-truth.
     * Rationale: Description is taken from the Summary header.
     */
    @ParameterizedTest(name = "description: {0}")
    @MethodSource("realPackages")
    void extractDescription_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.description())
                .isEqualTo(SourceOfTruth.getString(expected, "description"));
    }

    /**
     * Goal: Verify that the extracted license matches the source-of-truth.
     * Rationale: License extraction must handle License-Expression, License header, and classifiers (Q5).
     */
    @ParameterizedTest(name = "license: {0}")
    @MethodSource("realPackages")
    void extractLicense_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.license())
                .isEqualTo(SourceOfTruth.getString(expected, "license"));
    }

    /**
     * Goal: Verify that the extracted publisher matches the source-of-truth.
     * Rationale: Publisher extraction must handle Author, Author-email, Maintainer fallback (Q6).
     */
    @ParameterizedTest(name = "publisher: {0}")
    @MethodSource("realPackages")
    void extractPublisher_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.publisher())
                .isEqualTo(SourceOfTruth.getString(expected, "publisher"));
    }

    /**
     * Goal: Verify that the extracted dependency count matches the source-of-truth.
     * Rationale: All Requires-Dist entries must be parsed (Q7).
     */
    @ParameterizedTest(name = "dependencyCount: {0}")
    @MethodSource("realPackages")
    void extractDependencies_countMatchesSourceOfTruth(String label, Path pkgPath, Path expectedPath)
            throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        int expectedCount = expected.getAsJsonArray("dependencies").size();

        assertThat(result.dependencies())
                .hasSize(expectedCount);
    }

    /**
     * Goal: Verify that all extracted dependency names, versions, and scopes match the source-of-truth.
     * Rationale: Dependency extraction must correctly parse PEP 508 format, stripping env markers (Q7).
     */
    @ParameterizedTest(name = "dependencies: {0}")
    @MethodSource("realPackages")
    void extractDependencies_matchSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        var expectedDeps = expected.getAsJsonArray("dependencies");
        List<DepTuple> expectedTuples = new java.util.ArrayList<>();
        for (var elem : expectedDeps) {
            JsonObject depObj = elem.getAsJsonObject();
            String name = depObj.get("name").getAsString();
            String vc = depObj.get("versionConstraint").isJsonNull() ? null
                    : depObj.get("versionConstraint").getAsString();
            String scope = depObj.get("scope").getAsString();
            expectedTuples.add(new DepTuple(name, vc, scope));
        }

        List<DepTuple> actualTuples = result.dependencies().stream()
                .map(d -> new DepTuple(d.name(), d.versionConstraint().orElse(null), d.scope().orElse(null)))
                .toList();

        assertThat(actualTuples)
                .as("dependencies for %s", label)
                .containsExactlyInAnyOrderElementsOf(expectedTuples);
    }

    // --- Specific wheel tests (Q2) ---

    /**
     * Goal: Verify wheel extraction for requests package.
     * Rationale: Q2 - wheel (.whl) format must extract from .dist-info/METADATA.
     */
    @Test
    void wheelPackage_requests_extractsCorrectly() throws Exception {
        Path whl = PYPI_CORPUS.resolve("requests-2.31.0-py3-none-any.whl");
        assumeThat(Files.exists(whl)).isTrue();

        MetadataResult result = extractFromPackage(whl);

        assertThat(result.name()).hasValue("requests");
        assertThat(result.simpleName()).hasValue("requests");
        assertThat(result.version()).hasValue("2.31.0");
        assertThat(result.license()).hasValue("Apache 2.0");
        assertThat(result.publisher()).hasValue("Kenneth Reitz");
    }

    /**
     * Goal: Verify wheel extraction for flask package.
     * Rationale: Q2 - flask is a popular package with well-defined metadata.
     */
    @Test
    void wheelPackage_flask_extractsCorrectly() throws Exception {
        Path whl = PYPI_CORPUS.resolve("flask-3.0.0-py3-none-any.whl");
        assumeThat(Files.exists(whl)).isTrue();

        MetadataResult result = extractFromPackage(whl);

        assertThat(result.name()).hasValue("Flask");
        assertThat(result.version()).hasValue("3.0.0");
    }

    // --- Specific sdist tests (Q2) ---

    /**
     * Goal: Verify sdist extraction for cffi package.
     * Rationale: Q2 - sdist (.tar.gz) format must extract from PKG-INFO.
     */
    @Test
    void sdistPackage_cffi_extractsCorrectly() throws Exception {
        Path tarGz = PYPI_CORPUS.resolve("cffi-1.16.0.tar.gz");
        assumeThat(Files.exists(tarGz)).isTrue();

        MetadataResult result = extractFromPackage(tarGz);

        assertThat(result.name()).hasValue("cffi");
        assertThat(result.version()).hasValue("1.16.0");
        assertThat(result.license()).hasValue("MIT");
    }

    /**
     * Goal: Verify sdist extraction for pytz package.
     * Rationale: Q2 - pytz is a common sdist-only package.
     */
    @Test
    void sdistPackage_pytz_extractsCorrectly() throws Exception {
        Path tarGz = PYPI_CORPUS.resolve("pytz-2023.3.post1.tar.gz");
        assumeThat(Files.exists(tarGz)).isTrue();

        MetadataResult result = extractFromPackage(tarGz);

        assertThat(result.name()).hasValue("pytz");
        assertThat(result.version()).hasValue("2023.3.post1");
    }

    // --- Name normalization tests (Q1) ---

    /**
     * Goal: Verify PEP 503 name normalization: lowercase and collapse [-_.] to single hyphen.
     * Rationale: Q1 - Flask-SocketIO, python_dateutil, etc. must normalize consistently.
     */
    @Test
    void normalizeName_collapsesSpecialCharacters() {
        assertThat(PypiMetadataExtractor.normalizeName("Flask-SocketIO")).isEqualTo("flask-socketio");
        assertThat(PypiMetadataExtractor.normalizeName("python_dateutil")).isEqualTo("python-dateutil");
        assertThat(PypiMetadataExtractor.normalizeName("Jinja2")).isEqualTo("jinja2");
        assertThat(PypiMetadataExtractor.normalizeName("MarkupSafe")).isEqualTo("markupsafe");
        assertThat(PypiMetadataExtractor.normalizeName("PyYAML")).isEqualTo("pyyaml");
    }

    /**
     * Goal: Verify normalization of names with consecutive special characters.
     * Rationale: Q1 - runs of [-_.] must collapse to a single hyphen.
     */
    @Test
    void normalizeName_collapsesConsecutiveSpecials() {
        assertThat(PypiMetadataExtractor.normalizeName("foo--bar")).isEqualTo("foo-bar");
        assertThat(PypiMetadataExtractor.normalizeName("foo__bar")).isEqualTo("foo-bar");
        assertThat(PypiMetadataExtractor.normalizeName("foo._-bar")).isEqualTo("foo-bar");
    }

    /**
     * Goal: Verify normalization lowercases names.
     * Rationale: Q1 - PyPI names are case-insensitive.
     */
    @Test
    void normalizeName_lowercases() {
        assertThat(PypiMetadataExtractor.normalizeName("Django")).isEqualTo("django");
        assertThat(PypiMetadataExtractor.normalizeName("SQLAlchemy")).isEqualTo("sqlalchemy");
    }

    // --- RFC 822 header parsing tests (Q4) ---

    /**
     * Goal: Verify basic RFC 822 header parsing.
     * Rationale: Q4 - core metadata uses Key: Value format.
     */
    @Test
    void parseRfc822Headers_basicHeaders() {
        String text = "Metadata-Version: 2.1\nName: mypackage\nVersion: 1.0.0\n";
        Map<String, List<String>> headers = PypiMetadataExtractor.parseRfc822Headers(text);

        assertThat(headers.get("Metadata-Version")).containsExactly("2.1");
        assertThat(headers.get("Name")).containsExactly("mypackage");
        assertThat(headers.get("Version")).containsExactly("1.0.0");
    }

    /**
     * Goal: Verify RFC 822 continuation lines are handled.
     * Rationale: Q4 - lines starting with whitespace continue the previous header.
     */
    @Test
    void parseRfc822Headers_continuationLines() {
        String text = "Metadata-Version: 2.1\nDescription: This is\n        a long description\n";
        Map<String, List<String>> headers = PypiMetadataExtractor.parseRfc822Headers(text);

        assertThat(headers.get("Description").get(0)).contains("This is");
        assertThat(headers.get("Description").get(0)).contains("a long description");
    }

    /**
     * Goal: Verify repeated headers are stored as list.
     * Rationale: Q4 - Requires-Dist and Classifier appear multiple times.
     */
    @Test
    void parseRfc822Headers_repeatedHeaders() {
        String text = "Name: test\nRequires-Dist: foo>=1.0\nRequires-Dist: bar<2.0\n";
        Map<String, List<String>> headers = PypiMetadataExtractor.parseRfc822Headers(text);

        assertThat(headers.get("Requires-Dist")).containsExactly("foo>=1.0", "bar<2.0");
    }

    /**
     * Goal: Verify body after blank line is stored under __body__ key.
     * Rationale: Q4 - text after blank line is the description body.
     */
    @Test
    void parseRfc822Headers_bodyAfterBlankLine() {
        String text = "Name: test\n\nThis is the body content.\nSecond line.\n";
        Map<String, List<String>> headers = PypiMetadataExtractor.parseRfc822Headers(text);

        assertThat(headers.get("__body__").get(0)).contains("This is the body content.");
    }

    // --- License extraction tests (Q5) ---

    /**
     * Goal: Verify License-Expression header takes priority.
     * Rationale: Q5 - SPDX License-Expression is the preferred license source.
     */
    @Test
    void extractLicense_licenseExpressionPriority() {
        Map<String, List<String>> headers = Map.of(
                "License-Expression", List.of("MIT"),
                "License", List.of("Some other license"),
                "Classifier", List.of("License :: OSI Approved :: BSD License")
        );
        assertThat(PypiMetadataExtractor.extractLicense(headers)).hasValue("MIT");
    }

    /**
     * Goal: Verify License header is used when License-Expression is absent.
     * Rationale: Q5 - License header is the secondary source.
     */
    @Test
    void extractLicense_licenseHeaderFallback() {
        Map<String, List<String>> headers = Map.of(
                "License", List.of("Apache 2.0")
        );
        assertThat(PypiMetadataExtractor.extractLicense(headers)).hasValue("Apache 2.0");
    }

    /**
     * Goal: Verify UNKNOWN license is skipped.
     * Rationale: Q5 - "UNKNOWN" sentinel means absent.
     */
    @Test
    void extractLicense_unknownSkipped() {
        Map<String, List<String>> headers = Map.of(
                "License", List.of("UNKNOWN"),
                "Classifier", List.of("License :: OSI Approved :: MIT License")
        );
        assertThat(PypiMetadataExtractor.extractLicense(headers)).hasValue("MIT License");
    }

    /**
     * Goal: Verify classifier-based license extraction.
     * Rationale: Q5 - classifiers are the tertiary license source.
     */
    @Test
    void extractLicense_classifierFallback() {
        Map<String, List<String>> headers = Map.of(
                "Classifier", List.of(
                        "Programming Language :: Python :: 3",
                        "License :: OSI Approved :: MIT License",
                        "License :: OSI Approved :: BSD License"
                )
        );
        assertThat(PypiMetadataExtractor.extractLicense(headers)).hasValue("MIT License OR BSD License");
    }

    /**
     * Goal: Verify empty license when no source is available.
     * Rationale: Q5 - some packages have no license information at all.
     */
    @Test
    void extractLicense_noLicenseReturnsEmpty() {
        Map<String, List<String>> headers = Map.of("Name", List.of("test"));
        assertThat(PypiMetadataExtractor.extractLicense(headers)).isEmpty();
    }

    // --- Publisher extraction tests (Q6) ---

    /**
     * Goal: Verify Author header is the primary publisher source.
     * Rationale: Q6 - Author is the most direct publisher field.
     */
    @Test
    void extractPublisher_authorPrimary() {
        Map<String, List<String>> headers = Map.of(
                "Author", List.of("John Doe"),
                "Author-email", List.of("Jane Doe <jane@example.com>")
        );
        assertThat(PypiMetadataExtractor.extractPublisher(headers)).hasValue("John Doe");
    }

    /**
     * Goal: Verify Author-email name extraction as fallback.
     * Rationale: Q6 - Author-email "Name <email>" format.
     */
    @Test
    void extractPublisher_authorEmailFallback() {
        Map<String, List<String>> headers = Map.of(
                "Author", List.of("UNKNOWN"),
                "Author-email", List.of("Jane Doe <jane@example.com>")
        );
        assertThat(PypiMetadataExtractor.extractPublisher(headers)).hasValue("Jane Doe");
    }

    /**
     * Goal: Verify Maintainer as tertiary fallback.
     * Rationale: Q6 - Maintainer is used when Author and Author-email are absent.
     */
    @Test
    void extractPublisher_maintainerFallback() {
        Map<String, List<String>> headers = Map.of(
                "Maintainer", List.of("Bob Smith")
        );
        assertThat(PypiMetadataExtractor.extractPublisher(headers)).hasValue("Bob Smith");
    }

    /**
     * Goal: Verify Maintainer-email as quaternary fallback.
     * Rationale: Q6 - Maintainer-email "Name <email>" is the 4th fallback for publisher.
     */
    @Test
    void extractPublisher_maintainerEmailFallback() {
        Map<String, List<String>> headers = Map.of(
                "Maintainer-email", List.of("Alice Smith <alice@example.com>")
        );
        assertThat(PypiMetadataExtractor.extractPublisher(headers)).hasValue("Alice Smith");
    }

    /**
     * Goal: Verify empty publisher when no source is available.
     * Rationale: Q6 - some packages have no author information.
     */
    @Test
    void extractPublisher_noPublisherReturnsEmpty() {
        Map<String, List<String>> headers = Map.of("Name", List.of("test"));
        assertThat(PypiMetadataExtractor.extractPublisher(headers)).isEmpty();
    }

    // --- extractNameFromEmailField tests (Q6) ---

    /**
     * Goal: Verify name extraction from "Name <email>" format.
     * Rationale: Q6 - common Author-email format.
     */
    @Test
    void extractNameFromEmailField_nameAndEmail() {
        assertThat(PypiMetadataExtractor.extractNameFromEmailField("John Doe <john@example.com>"))
                .hasValue("John Doe");
    }

    /**
     * Goal: Verify quoted name extraction.
     * Rationale: Q6 - some Author-email fields quote the name.
     */
    @Test
    void extractNameFromEmailField_quotedName() {
        assertThat(PypiMetadataExtractor.extractNameFromEmailField("\"John Doe\" <john@example.com>"))
                .hasValue("John Doe");
    }

    /**
     * Goal: Verify bare email returns empty.
     * Rationale: Q6 - an email address alone should not be used as publisher.
     */
    @Test
    void extractNameFromEmailField_bareEmail() {
        assertThat(PypiMetadataExtractor.extractNameFromEmailField("john@example.com")).isEmpty();
    }

    /**
     * Goal: Verify empty string returns empty.
     * Rationale: Q6 - empty field should return empty.
     */
    @Test
    void extractNameFromEmailField_emptyString() {
        assertThat(PypiMetadataExtractor.extractNameFromEmailField("")).isEmpty();
    }

    // --- parseRequiresDist tests (Q7) ---

    /**
     * Goal: Verify basic dependency parsing.
     * Rationale: Q7 - simple name with version constraint.
     */
    @Test
    void parseRequiresDist_simpleNameAndVersion() {
        Optional<ParsedDependency> dep = PypiMetadataExtractor.parseRequiresDist("requests>=2.20.0");
        assertThat(dep).isPresent();
        assertThat(dep.get().name()).isEqualTo("requests");
        assertThat(dep.get().versionConstraint()).hasValue(">=2.20.0");
        assertThat(dep.get().scope()).hasValue("runtime");
    }

    /**
     * Goal: Verify name-only dependency (no version constraint).
     * Rationale: Q7 - some dependencies have no version requirement.
     */
    @Test
    void parseRequiresDist_nameOnly() {
        Optional<ParsedDependency> dep = PypiMetadataExtractor.parseRequiresDist("six");
        assertThat(dep).isPresent();
        assertThat(dep.get().name()).isEqualTo("six");
        assertThat(dep.get().versionConstraint()).isEmpty();
    }

    /**
     * Goal: Verify environment markers are stripped.
     * Rationale: Q7 - markers after ; are environment conditions, not version constraints.
     */
    @Test
    void parseRequiresDist_environmentMarkersStripped() {
        Optional<ParsedDependency> dep = PypiMetadataExtractor.parseRequiresDist(
                "colorama ; os_name == \"nt\"");
        assertThat(dep).isPresent();
        assertThat(dep.get().name()).isEqualTo("colorama");
        assertThat(dep.get().versionConstraint()).isEmpty();
    }

    /**
     * Goal: Verify extras are stripped.
     * Rationale: Q7 - extras in brackets are feature groups, not part of the name.
     */
    @Test
    void parseRequiresDist_extrasStripped() {
        Optional<ParsedDependency> dep = PypiMetadataExtractor.parseRequiresDist(
                "requests[security]>=2.0");
        assertThat(dep).isPresent();
        assertThat(dep.get().name()).isEqualTo("requests");
        assertThat(dep.get().versionConstraint()).hasValue(">=2.0");
    }

    /**
     * Goal: Verify parenthesized version constraints are unwrapped.
     * Rationale: Q7 - some Requires-Dist lines use parentheses around version spec.
     */
    @Test
    void parseRequiresDist_parenthesizedVersion() {
        Optional<ParsedDependency> dep = PypiMetadataExtractor.parseRequiresDist(
                "pycparser (>=1.0)");
        assertThat(dep).isPresent();
        assertThat(dep.get().name()).isEqualTo("pycparser");
        assertThat(dep.get().versionConstraint()).hasValue(">=1.0");
    }

    /**
     * Goal: Verify complex version constraint with environment marker.
     * Rationale: Q7 - realistic PEP 508 line from real packages.
     */
    @Test
    void parseRequiresDist_complexLine() {
        Optional<ParsedDependency> dep = PypiMetadataExtractor.parseRequiresDist(
                "tomli>=1.0.0 ; python_version < \"3.11\"");
        assertThat(dep).isPresent();
        assertThat(dep.get().name()).isEqualTo("tomli");
        assertThat(dep.get().versionConstraint()).hasValue(">=1.0.0");
    }

    /**
     * Goal: Verify empty line returns empty.
     * Rationale: Q7 - empty Requires-Dist should not produce a dependency.
     */
    @Test
    void parseRequiresDist_emptyReturnsEmpty() {
        assertThat(PypiMetadataExtractor.parseRequiresDist("")).isEmpty();
    }

    // --- isDistInfoMetadata tests (Q2) ---

    /**
     * Goal: Verify standard .dist-info/METADATA path is recognized.
     * Rationale: Q2 - wheels store metadata in the dist-info directory.
     */
    @Test
    void isDistInfoMetadata_standardPath() {
        assertThat(PypiMetadataExtractor.isDistInfoMetadata("requests-2.31.0.dist-info/METADATA")).isTrue();
    }

    /**
     * Goal: Verify paths with dashes in dist-info directory name.
     * Rationale: Q2 - dist-info directory name contains package name and version.
     */
    @Test
    void isDistInfoMetadata_pathWithDashes() {
        assertThat(PypiMetadataExtractor.isDistInfoMetadata("Flask_SocketIO-5.3.6.dist-info/METADATA")).isTrue();
    }

    /**
     * Goal: Verify nested paths are NOT matched.
     * Rationale: Q2 - only top-level dist-info should match.
     */
    @Test
    void isDistInfoMetadata_nestedNotMatched() {
        assertThat(PypiMetadataExtractor.isDistInfoMetadata("some/requests-2.31.0.dist-info/METADATA")).isFalse();
    }

    /**
     * Goal: Verify non-METADATA files are NOT matched.
     * Rationale: Q2 - RECORD, WHEEL, etc. in dist-info should not match.
     */
    @Test
    void isDistInfoMetadata_otherFileNotMatched() {
        assertThat(PypiMetadataExtractor.isDistInfoMetadata("requests-2.31.0.dist-info/RECORD")).isFalse();
        assertThat(PypiMetadataExtractor.isDistInfoMetadata("requests-2.31.0.dist-info/WHEEL")).isFalse();
    }

    // --- isPkgInfo tests (Q2) ---

    /**
     * Goal: Verify standard PKG-INFO path is recognized.
     * Rationale: Q2 - sdists store metadata in top-level PKG-INFO.
     */
    @Test
    void isPkgInfo_standardPath() {
        assertThat(PypiMetadataExtractor.isPkgInfo("cffi-1.16.0/PKG-INFO")).isTrue();
    }

    /**
     * Goal: Verify nested PKG-INFO is NOT matched.
     * Rationale: Q2 - only top-level PKG-INFO should match.
     */
    @Test
    void isPkgInfo_nestedNotMatched() {
        assertThat(PypiMetadataExtractor.isPkgInfo("cffi-1.16.0/src/PKG-INFO")).isFalse();
    }

    /**
     * Goal: Verify root-level PKG-INFO without directory is NOT matched.
     * Rationale: Q2 - sdists always have a top-level directory prefix.
     */
    @Test
    void isPkgInfo_rootLevelNotMatched() {
        assertThat(PypiMetadataExtractor.isPkgInfo("PKG-INFO")).isFalse();
    }

    // --- Full extraction pipeline tests ---

    /**
     * Goal: Verify full wheel extraction pipeline end-to-end.
     * Rationale: Q2 - the full zip -> METADATA -> parse pipeline must work.
     */
    @Test
    void fullExtraction_requests_fromWheel() throws Exception {
        Path whl = PYPI_CORPUS.resolve("requests-2.31.0-py3-none-any.whl");
        assumeThat(Files.exists(whl)).isTrue();

        try (FileInputStream fis = new FileInputStream(whl.toFile())) {
            MetadataResult result = PypiMetadataExtractor.extract(fis, whl.getFileName().toString());
            assertThat(result.name()).hasValue("requests");
            assertThat(result.version()).hasValue("2.31.0");
        }
    }

    /**
     * Goal: Verify full sdist extraction pipeline end-to-end.
     * Rationale: Q2 - the full gzip -> tar -> PKG-INFO -> parse pipeline must work.
     */
    @Test
    void fullExtraction_cffi_fromSdist() throws Exception {
        Path tarGz = PYPI_CORPUS.resolve("cffi-1.16.0.tar.gz");
        assumeThat(Files.exists(tarGz)).isTrue();

        try (FileInputStream fis = new FileInputStream(tarGz.toFile())) {
            MetadataResult result = PypiMetadataExtractor.extract(fis, tarGz.getFileName().toString());
            assertThat(result.name()).hasValue("cffi");
            assertThat(result.version()).hasValue("1.16.0");
        }
    }

    // --- Helper methods ---

    private MetadataResult extractFromPackage(Path pkgPath) throws Exception {
        try (FileInputStream fis = new FileInputStream(pkgPath.toFile())) {
            return PypiMetadataExtractor.extract(fis, pkgPath.getFileName().toString());
        }
    }

    private record DepTuple(String name, String versionConstraint, String scope) {
    }
}
