/* Copyright 2026 Spice Labs, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License. */

package io.spicelabs.annatto.cpan;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import io.spicelabs.annatto.common.MetadataResult;
import io.spicelabs.annatto.common.ParsedDependency;
import io.spicelabs.annatto.testutil.SourceOfTruth;
import io.spicelabs.annatto.testutil.TestCorpusDownloader;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.io.ByteArrayInputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Optional;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.assertj.core.api.Assumptions.assumeThat;

/**
 * Tests for {@link CpanMetadataExtractor} comparing extraction results against
 * source-of-truth expected values produced by native Perl tools in Docker.
 *
 * <p>All test packages are real CPAN distributions downloaded from cpan.metacpan.org.
 * Expected values were generated by running Docker containers with CPAN::Meta.</p>
 *
 * <p>Package files (.tar.gz) are in {@code test-corpus/cpan/} (gitignored).
 * Source-of-truth expected JSON files are in {@code src/test/resources/cpan/} (git-tracked).</p>
 *
 * <p>Covers {@link CpanQuirks} Q1-Q8.</p>
 */
class CpanMetadataExtractorTest {

    private static final Path CPAN_CORPUS = TestCorpusDownloader.corpusDir("cpan");
    private static final Path CPAN_EXPECTED = TestCorpusDownloader.expectedDir("cpan");
    private static final Gson GSON = new Gson();

    @BeforeAll
    static void ensureTestPackagesExist() {
        assumeThat(Files.isDirectory(CPAN_CORPUS))
                .as("cpan test corpus directory must exist with real packages")
                .isTrue();
    }

    // --- Parameterized source-of-truth comparison ---

    static Stream<Arguments> realPackages() throws IOException {
        if (!Files.isDirectory(CPAN_CORPUS)) {
            return Stream.empty();
        }
        return Files.list(CPAN_CORPUS)
                .filter(p -> p.toString().endsWith(".tar.gz"))
                .sorted()
                .map(pkg -> {
                    Path expected = SourceOfTruth.expectedPathFor(pkg, CPAN_EXPECTED);
                    String label = pkg.getFileName().toString();
                    return Arguments.of(label, pkg, expected);
                });
    }

    /**
     * Goal: Verify extracted name matches source-of-truth for every real package.
     * Rationale: Name is the distribution name; must be exact (Q2).
     */
    @ParameterizedTest(name = "name: {0}")
    @MethodSource("realPackages")
    void extractName_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        assertThat(result.name()).isEqualTo(SourceOfTruth.getString(expected, "name"));
    }

    /**
     * Goal: Verify extracted simpleName matches source-of-truth.
     * Rationale: For CPAN, simpleName equals name (distribution name, Q2).
     */
    @ParameterizedTest(name = "simpleName: {0}")
    @MethodSource("realPackages")
    void extractSimpleName_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        assertThat(result.simpleName()).isEqualTo(SourceOfTruth.getString(expected, "simpleName"));
    }

    /**
     * Goal: Verify extracted version matches source-of-truth.
     * Rationale: Version must be exact from META.json.
     */
    @ParameterizedTest(name = "version: {0}")
    @MethodSource("realPackages")
    void extractVersion_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        assertThat(result.version()).isEqualTo(SourceOfTruth.getString(expected, "version"));
    }

    /**
     * Goal: Verify extracted description meets or exceeds ground truth (floor test).
     * Rationale: Ground truth is a minimum; extractor may find better descriptions.
     */
    @ParameterizedTest(name = "description: {0}")
    @MethodSource("realPackages")
    void extractDescription_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        Optional<String> expectedDesc = SourceOfTruth.getString(expected, "description");
        Optional<String> actualDesc = result.description();

        // Floor test: if ground truth has a value, we must have at least that value
        // If ground truth is empty/null, having a value is acceptable (exceeds floor)
        if (expectedDesc.isPresent() && !expectedDesc.get().isEmpty()
                && !"unknown".equalsIgnoreCase(expectedDesc.get())) {
            assertThat(actualDesc).as("description for %s", label).isEqualTo(expectedDesc);
        }
        // If expected is empty/null/unknown, actual can be anything (including present) - floor test passes
    }

    /**
     * Goal: Verify extracted license meets or exceeds ground truth (floor test).
     * Rationale: Ground truth is a minimum; extractor may find better license info.
     */
    @ParameterizedTest(name = "license: {0}")
    @MethodSource("realPackages")
    void extractLicense_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        Optional<String> expectedLicense = SourceOfTruth.getString(expected, "license");
        Optional<String> actualLicense = result.license();

        // Floor test: if ground truth has a real value, we must match it
        // If ground truth is empty/null/unknown, having a value is acceptable
        if (expectedLicense.isPresent() && !expectedLicense.get().isEmpty()
                && !"unknown".equalsIgnoreCase(expectedLicense.get())) {
            assertThat(actualLicense).as("license for %s", label).isEqualTo(expectedLicense);
        }
    }

    /**
     * Goal: Verify extracted publisher meets or exceeds ground truth (floor test).
     * Rationale: Ground truth is a minimum; extractor may find better publisher info.
     */
    @ParameterizedTest(name = "publisher: {0}")
    @MethodSource("realPackages")
    void extractPublisher_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        Optional<String> expectedPublisher = SourceOfTruth.getString(expected, "publisher");
        Optional<String> actualPublisher = result.publisher();

        // Floor test: if ground truth has a real value, we must match it
        // If ground truth is empty/null/unknown, having a value is acceptable
        if (expectedPublisher.isPresent() && !expectedPublisher.get().isEmpty()
                && !"unknown".equalsIgnoreCase(expectedPublisher.get())) {
            assertThat(actualPublisher).as("publisher for %s", label).isEqualTo(expectedPublisher);
        }
    }

    /**
     * Goal: Verify publishedAt is always null.
     * Rationale: Q6 — No timestamp in CPAN META files.
     */
    @ParameterizedTest(name = "publishedAt: {0}")
    @MethodSource("realPackages")
    void extractPublishedAt_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        assertThat(result.publishedAt()).isEmpty();
    }

    /**
     * Goal: Verify extracted dependencies meet or exceed ground truth (floor test).
     * Rationale: Ground truth is a minimum; extractor may find more dependencies.
     */
    @ParameterizedTest(name = "depCount: {0}")
    @MethodSource("realPackages")
    void extractDependencyCount_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath)
            throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        int expectedCount = expected.getAsJsonArray("dependencies").size();
        // Floor test: actual count must be >= expected (ground truth is minimum)
        assertThat(result.dependencies().size())
            .as("dependency count for %s (must be >= %d)", label, expectedCount)
            .isGreaterThanOrEqualTo(expectedCount);
    }

    /**
     * Goal: Verify all ground truth dependencies are present in extraction (floor test).
     * Rationale: Ground truth is a minimum; extractor may find more dependencies.
     */
    @ParameterizedTest(name = "deps: {0}")
    @MethodSource("realPackages")
    void extractDependencies_matchSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        JsonArray expectedDeps = expected.getAsJsonArray("dependencies");
        List<DepTuple> expectedTuples = new java.util.ArrayList<>();
        for (var elem : expectedDeps) {
            JsonObject depObj = elem.getAsJsonObject();
            String name = depObj.get("name").getAsString();
            String vc = depObj.get("versionConstraint").isJsonNull() ? null
                    : depObj.get("versionConstraint").getAsString();
            String scope = depObj.get("scope").getAsString();
            expectedTuples.add(new DepTuple(name, vc, scope));
        }

        List<DepTuple> actualTuples = result.dependencies().stream()
                .map(d -> new DepTuple(d.name(), d.versionConstraint().orElse(null), d.scope().orElse(null)))
                .toList();

        // Floor test: all expected dependencies must be present in actual
        assertThat(actualTuples).as("dependencies for %s (must contain all ground truth)", label)
                .containsAll(expectedTuples);
    }

    // --- Named package tests ---

    /**
     * Goal: Verify Moose extraction (many deps, popular OO framework).
     * Rationale: Q4 — Large dependency set across multiple phases.
     */
    @Test
    void package_moose_manyDeps() throws Exception {
        Path pkg = findPackage("Moose-2.2207.tar.gz");
        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.name()).hasValue("Moose");
        assertThat(result.simpleName()).hasValue("Moose");
        assertThat(result.version()).hasValue("2.2207");
        assertThat(result.license()).hasValue("perl_5");
        assertThat(result.publisher()).isPresent();
        assertThat(result.dependencies()).isNotEmpty();
        assertThat(result.dependencies().stream().map(ParsedDependency::name))
                .contains("Carp", "Class::Load");
    }

    /**
     * Goal: Verify Try-Tiny extraction (minimal runtime deps).
     * Rationale: Small package with few runtime deps but many dev deps.
     */
    @Test
    void package_tryTiny_fewRuntimeDeps() throws Exception {
        Path pkg = findPackage("Try-Tiny-0.31.tar.gz");
        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.name()).hasValue("Try-Tiny");
        assertThat(result.version()).hasValue("0.31");
        assertThat(result.license()).hasValue("mit");
        assertThat(result.description()).hasValue("Minimal try/catch with proper preservation of $@");
    }

    /**
     * Goal: Verify namespace-clean (lowercase name, Q8 edge case).
     * Rationale: Q8 — Lowercase CPAN names are ambiguous with PyPI in filter.
     */
    @Test
    void package_namespaceClean_lowercase() throws Exception {
        Path pkg = findPackage("namespace-clean-0.27.tar.gz");
        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.name()).hasValue("namespace-clean");
        assertThat(result.version()).hasValue("0.27");
        assertThat(result.license()).hasValue("perl_5");
    }

    /**
     * Goal: Verify YAML-Tiny extraction (may be META.yml only, Q1).
     * Rationale: Q1 — Tests YAML fallback when META.json might be the only option.
     */
    @Test
    void package_yamlTiny() throws Exception {
        Path pkg = findPackage("YAML-Tiny-1.76.tar.gz");
        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.name()).hasValue("YAML-Tiny");
        assertThat(result.version()).hasValue("1.76");
    }

    /**
     * Goal: Verify Perl-Tidy (YYYYMMDD version format).
     * Rationale: Version edge case — date-based version.
     */
    @Test
    void package_perlTidy_dateVersion() throws Exception {
        Path pkg = findPackage("Perl-Tidy-20240903.tar.gz");
        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.name()).hasValue("Perl-Tidy");
        assertThat(result.version()).hasValue("20240903");
    }

    /**
     * Goal: Verify Class-Accessor (decimal version).
     * Rationale: Version edge case — simple decimal version.
     */
    @Test
    void package_classAccessor_decimalVersion() throws Exception {
        Path pkg = findPackage("Class-Accessor-0.51.tar.gz");
        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.name()).hasValue("Class-Accessor");
        assertThat(result.version()).hasValue("0.51");
    }

    /**
     * Goal: Verify Regexp-Common (date-encoded version, large).
     * Rationale: Q7 — License edge case; large package.
     */
    @Test
    void package_regexpCommon() throws Exception {
        Path pkg = findPackage("Regexp-Common-2024080801.tar.gz");
        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.name()).hasValue("Regexp-Common");
        assertThat(result.version()).isPresent();
    }

    /**
     * Goal: Verify constant (lowercase name, core module).
     * Rationale: Edge case — lowercase distribution name.
     */
    @Test
    void package_constant_lowercase() throws Exception {
        Path pkg = findPackage("constant-1.33.tar.gz");
        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.name()).hasValue("constant");
        assertThat(result.version()).hasValue("1.33");
    }

    /**
     * Goal: Verify Mojolicious (zero runtime deps, single author).
     * Rationale: Framework with no external dependencies.
     */
    @Test
    void package_mojolicious_zeroDeps() throws Exception {
        Path pkg = findPackage("Mojolicious-9.37.tar.gz");
        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.name()).hasValue("Mojolicious");
        assertThat(result.version()).hasValue("9.37");
    }

    /**
     * Goal: Verify Sub-Exporter-Progressive (deep decimal version).
     * Rationale: Version edge case — 0.001013 is a valid Perl version.
     */
    @Test
    void package_subExporterProgressive_deepDecimal() throws Exception {
        Path pkg = findPackage("Sub-Exporter-Progressive-0.001013.tar.gz");
        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.name()).hasValue("Sub-Exporter-Progressive");
        assertThat(result.version()).hasValue("0.001013");
    }

    // --- Unit tests for extractLicense ---

    /**
     * Goal: Verify ["unknown"] license maps to null.
     * Rationale: Q7 — Unknown license must be normalized to absent.
     */
    @Test
    void extractLicense_unknownMapsToNull() {
        JsonObject root = new JsonObject();
        JsonArray arr = new JsonArray();
        arr.add("unknown");
        root.add("license", arr);
        assertThat(CpanMetadataExtractor.extractLicense(root)).isEmpty();
    }

    /**
     * Goal: Verify multiple licenses joined with " OR ".
     * Rationale: Q7 — Multiple license array entries.
     */
    @Test
    void extractLicense_multipleJoined() {
        JsonObject root = new JsonObject();
        JsonArray arr = new JsonArray();
        arr.add("perl_5");
        arr.add("artistic_2");
        root.add("license", arr);
        assertThat(CpanMetadataExtractor.extractLicense(root)).hasValue("perl_5 OR artistic_2");
    }

    /**
     * Goal: Verify single license string.
     * Rationale: Q7 — META v1 uses a single string.
     */
    @Test
    void extractLicense_singleString() {
        JsonObject root = new JsonObject();
        root.addProperty("license", "mit");
        assertThat(CpanMetadataExtractor.extractLicense(root)).hasValue("mit");
    }

    /**
     * Goal: Verify empty license array.
     * Rationale: Q7 — Empty array means no license info.
     */
    @Test
    void extractLicense_emptyArray() {
        JsonObject root = new JsonObject();
        root.add("license", new JsonArray());
        assertThat(CpanMetadataExtractor.extractLicense(root)).isEmpty();
    }

    /**
     * Goal: Verify absent license field.
     * Rationale: Q7 — Missing field means no license info.
     */
    @Test
    void extractLicense_absent() {
        JsonObject root = new JsonObject();
        assertThat(CpanMetadataExtractor.extractLicense(root)).isEmpty();
    }

    // --- Unit tests for extractDescription ---

    /**
     * Goal: Verify "unknown" abstract maps to null.
     * Rationale: Placeholder abstracts should be filtered.
     */
    @Test
    void extractDescription_unknownMapsToNull() {
        JsonObject root = new JsonObject();
        root.addProperty("abstract", "unknown");
        assertThat(CpanMetadataExtractor.extractDescription(root)).isEmpty();
    }

    /**
     * Goal: Verify valid abstract is extracted.
     * Rationale: Normal abstract field.
     */
    @Test
    void extractDescription_validAbstract() {
        JsonObject root = new JsonObject();
        root.addProperty("abstract", "A useful module");
        assertThat(CpanMetadataExtractor.extractDescription(root)).hasValue("A useful module");
    }

    /**
     * Goal: Verify absent abstract.
     * Rationale: Some packages may not have an abstract.
     */
    @Test
    void extractDescription_absent() {
        JsonObject root = new JsonObject();
        assertThat(CpanMetadataExtractor.extractDescription(root)).isEmpty();
    }

    // --- Unit tests for extractPublisher ---

    /**
     * Goal: Verify author array joined.
     * Rationale: Multiple authors joined with ", ".
     */
    @Test
    void extractPublisher_arrayJoined() {
        JsonObject root = new JsonObject();
        JsonArray arr = new JsonArray();
        arr.add("Author One <one@example.com>");
        arr.add("Author Two <two@example.com>");
        root.add("author", arr);
        assertThat(CpanMetadataExtractor.extractPublisher(root))
                .hasValue("Author One <one@example.com>, Author Two <two@example.com>");
    }

    /**
     * Goal: Verify single author string.
     * Rationale: META v1 may use a string.
     */
    @Test
    void extractPublisher_singleString() {
        JsonObject root = new JsonObject();
        root.addProperty("author", "Author <a@example.com>");
        assertThat(CpanMetadataExtractor.extractPublisher(root))
                .hasValue("Author <a@example.com>");
    }

    /**
     * Goal: Verify "unknown" author maps to null.
     * Rationale: Placeholder authors should be filtered.
     */
    @Test
    void extractPublisher_unknownMapsToNull() {
        JsonObject root = new JsonObject();
        root.addProperty("author", "unknown");
        assertThat(CpanMetadataExtractor.extractPublisher(root)).isEmpty();
    }

    // --- Unit tests for extractDependencies ---

    /**
     * Goal: Verify only "requires" relationships are extracted.
     * Rationale: Q4 — recommends/suggests/conflicts must be skipped.
     */
    @Test
    void extractDeps_onlyRequires() {
        JsonObject root = new JsonObject();
        JsonObject prereqs = new JsonObject();
        JsonObject runtime = new JsonObject();
        JsonObject requires = new JsonObject();
        requires.addProperty("Module::Needed", "1.0");
        runtime.add("requires", requires);
        JsonObject recommends = new JsonObject();
        recommends.addProperty("Module::Optional", "2.0");
        runtime.add("recommends", recommends);
        prereqs.add("runtime", runtime);
        root.add("prereqs", prereqs);

        List<ParsedDependency> deps = CpanMetadataExtractor.extractDependencies(root);
        assertThat(deps).hasSize(1);
        assertThat(deps.get(0).name()).isEqualTo("Module::Needed");
    }

    /**
     * Goal: Verify version "0" maps to null constraint.
     * Rationale: Q5 — Version "0" means any version.
     */
    @Test
    void parseVersionConstraint_zeroMapsToNull() {
        JsonObject root = new JsonObject();
        JsonObject prereqs = new JsonObject();
        JsonObject runtime = new JsonObject();
        JsonObject requires = new JsonObject();
        requires.addProperty("Some::Module", "0");
        runtime.add("requires", requires);
        prereqs.add("runtime", runtime);
        root.add("prereqs", prereqs);

        List<ParsedDependency> deps = CpanMetadataExtractor.extractDependencies(root);
        assertThat(deps).hasSize(1);
        assertThat(deps.get(0).versionConstraint()).isEmpty();
    }

    /**
     * Goal: Verify "perl" itself is skipped.
     * Rationale: The perl interpreter is not a CPAN dependency.
     */
    @Test
    void extractDeps_perlSkipped() {
        JsonObject root = new JsonObject();
        JsonObject prereqs = new JsonObject();
        JsonObject runtime = new JsonObject();
        JsonObject requires = new JsonObject();
        requires.addProperty("perl", "5.008001");
        requires.addProperty("Carp", "0");
        runtime.add("requires", requires);
        prereqs.add("runtime", runtime);
        root.add("prereqs", prereqs);

        List<ParsedDependency> deps = CpanMetadataExtractor.extractDependencies(root);
        assertThat(deps).hasSize(1);
        assertThat(deps.get(0).name()).isEqualTo("Carp");
    }

    /**
     * Goal: Verify configure phase maps to "build" scope.
     * Rationale: Q4 — Both configure and build phases map to "build" scope.
     */
    @Test
    void extractDeps_configureMapsToBuild() {
        JsonObject root = new JsonObject();
        JsonObject prereqs = new JsonObject();
        JsonObject configure = new JsonObject();
        JsonObject requires = new JsonObject();
        requires.addProperty("ExtUtils::MakeMaker", "6.30");
        configure.add("requires", requires);
        prereqs.add("configure", configure);
        root.add("prereqs", prereqs);

        List<ParsedDependency> deps = CpanMetadataExtractor.extractDependencies(root);
        assertThat(deps).hasSize(1);
        assertThat(deps.get(0).scope()).hasValue("build");
    }

    /**
     * Goal: Verify develop phase maps to "dev" scope.
     * Rationale: Q4 — Develop dependencies are dev scope.
     */
    @Test
    void extractDeps_developMapsToDev() {
        JsonObject root = new JsonObject();
        JsonObject prereqs = new JsonObject();
        JsonObject develop = new JsonObject();
        JsonObject requires = new JsonObject();
        requires.addProperty("Test::Pod", "1.41");
        develop.add("requires", requires);
        prereqs.add("develop", develop);
        root.add("prereqs", prereqs);

        List<ParsedDependency> deps = CpanMetadataExtractor.extractDependencies(root);
        assertThat(deps).hasSize(1);
        assertThat(deps.get(0).scope()).hasValue("dev");
    }

    // --- Error handling tests ---

    /**
     * Goal: Verify MalformedPackageException for archive without META files.
     * Rationale: META.json/yml is required; its absence must be reported.
     */
    @Test
    void extractFromArchive_noMetaFile_throws() {
        assertThatThrownBy(() ->
                CpanMetadataExtractor.extractFromArchive(
                        new ByteArrayInputStream(new byte[0]), "bad.tar.gz"))
                .isInstanceOf(Exception.class);
    }

    /**
     * Goal: Verify corrupt JSON handling.
     * Rationale: Malformed META.json should throw MetadataExtractionException.
     */
    @Test
    void buildMetadataResult_corruptJson() {
        CpanMetadataExtractor.CpanArchiveData data =
                new CpanMetadataExtractor.CpanArchiveData("{invalid json", CpanMetadataExtractor.MetaFormat.JSON);
        assertThatThrownBy(() -> CpanMetadataExtractor.buildMetadataResult(data))
                .isInstanceOf(Exception.class);
    }

    /**
     * Goal: Verify unknown extra fields don't cause errors.
     * Rationale: META.json may have fields we don't use.
     */
    @Test
    void unknownExtraFields() throws Exception {
        String json = """
                {"name":"test","version":"1.0","unknown_field":"value"}
                """;
        CpanMetadataExtractor.CpanArchiveData data =
                new CpanMetadataExtractor.CpanArchiveData(json, CpanMetadataExtractor.MetaFormat.JSON);
        MetadataResult result = CpanMetadataExtractor.buildMetadataResult(data);
        assertThat(result.name()).hasValue("test");
    }

    /**
     * Goal: Verify empty prereqs produces empty deps.
     * Rationale: No prereqs section should yield no dependencies.
     */
    @Test
    void emptyPrereqs() {
        JsonObject root = new JsonObject();
        assertThat(CpanMetadataExtractor.extractDependencies(root)).isEmpty();
    }

    // --- Archive format preference tests ---

    /**
     * Goal: Verify META.json is preferred over META.yml when both exist in archive.
     * Rationale: Q1 — META.json (v2 spec) is more structured and preferred.
     * Uses Moose (a real package that has both META.json and META.yml).
     */
    @Test
    void extractFromArchive_prefersMetaJson() throws Exception {
        Path pkg = findPackage("Moose-2.2207.tar.gz");
        try (FileInputStream fis = new FileInputStream(pkg.toFile())) {
            CpanMetadataExtractor.CpanArchiveData data =
                    CpanMetadataExtractor.extractFromArchive(fis, "Moose-2.2207.tar.gz");
            // Moose has both META.json and META.yml; must select JSON
            assertThat(data.format()).isEqualTo(CpanMetadataExtractor.MetaFormat.JSON);
        }
    }

    /**
     * Goal: Verify META.yml is used when META.json is absent.
     * Rationale: Q1 — Fallback to META.yml for older distributions.
     * Uses DBIx-Class (a real package that only has META.yml).
     */
    @Test
    void extractFromArchive_fallsBackToMetaYml() throws Exception {
        Path pkg = findPackage("DBIx-Class-0.082843.tar.gz");
        try (FileInputStream fis = new FileInputStream(pkg.toFile())) {
            CpanMetadataExtractor.CpanArchiveData data =
                    CpanMetadataExtractor.extractFromArchive(fis, "DBIx-Class-0.082843.tar.gz");
            // DBIx-Class only has META.yml; must use YAML format
            assertThat(data.format()).isEqualTo(CpanMetadataExtractor.MetaFormat.YAML);
        }
    }

    /**
     * Goal: Verify DBIx-Class (META.yml only, v1 format) has correct deps and license.
     * Rationale: Q1 — Real-world YAML-only case with v1 prereqs structure and license normalization.
     */
    @Test
    void package_yamlTiny_metaYmlOnly() throws Exception {
        Path pkg = findPackage("DBIx-Class-0.082843.tar.gz");
        MetadataResult result = extractFromPackage(pkg);

        assertThat(result.name()).hasValue("DBIx-Class");
        assertThat(result.version()).hasValue("0.082843");
        // License "perl" in v1 META.yml must be normalized to "perl_5"
        assertThat(result.license()).hasValue("perl_5");
        // Must have 27 dependencies from v1 flat requires/build_requires/configure_requires
        assertThat(result.dependencies()).hasSize(27);
    }

    /**
     * Goal: Verify v1 license normalization: "perl" → "perl_5".
     * Rationale: Q7 — META v1 uses short license identifiers that must be normalized to v2.
     */
    @Test
    void extractLicense_v1NormalizesPerl() {
        JsonObject root = new JsonObject();
        root.addProperty("license", "perl");
        assertThat(CpanMetadataExtractor.extractLicense(root)).hasValue("perl_5");
    }

    /**
     * Goal: Verify v1 license normalization: "gpl" → "gpl_1".
     * Rationale: Q7 — v1 short forms are mapped to v2 canonical identifiers.
     */
    @Test
    void extractLicense_v1NormalizesGpl() {
        JsonObject root = new JsonObject();
        root.addProperty("license", "gpl");
        assertThat(CpanMetadataExtractor.extractLicense(root)).hasValue("gpl_1");
    }

    /**
     * Goal: Verify v1 deps extraction from flat keys.
     * Rationale: META v1 uses build_requires/configure_requires/requires at root level.
     */
    @Test
    void extractDeps_v1FlatStructure() {
        JsonObject root = new JsonObject();
        JsonObject requires = new JsonObject();
        requires.addProperty("Carp", "0");
        root.add("requires", requires);
        JsonObject buildRequires = new JsonObject();
        buildRequires.addProperty("Test::More", "0.88");
        root.add("build_requires", buildRequires);

        List<ParsedDependency> deps = CpanMetadataExtractor.extractDependencies(root);
        assertThat(deps).hasSize(2);
        assertThat(deps.stream().filter(d -> d.name().equals("Carp")).findFirst())
                .hasValueSatisfying(d -> assertThat(d.scope()).hasValue("runtime"));
        assertThat(deps.stream().filter(d -> d.name().equals("Test::More")).findFirst())
                .hasValueSatisfying(d -> {
                    assertThat(d.scope()).hasValue("build");
                    assertThat(d.versionConstraint()).hasValue("0.88");
                });
    }

    // --- Helper methods ---

    private MetadataResult extractFromPackage(Path pkgPath) throws Exception {
        try (FileInputStream fis = new FileInputStream(pkgPath.toFile())) {
            return CpanMetadataExtractor.extract(fis, pkgPath.getFileName().toString());
        }
    }

    private Path findPackage(String filename) {
        Path pkg = CPAN_CORPUS.resolve(filename);
        assumeThat(Files.exists(pkg)).isTrue();
        return pkg;
    }

    private record DepTuple(String name, String versionConstraint, String scope) {
    }
}
