/* Copyright 2026 Spice Labs, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License. */

package io.spicelabs.annatto.crates;

import com.google.gson.JsonObject;
import io.spicelabs.annatto.common.MetadataResult;
import io.spicelabs.annatto.common.ParsedDependency;
import io.spicelabs.annatto.testutil.SourceOfTruth;
import io.spicelabs.annatto.testutil.TestCorpusDownloader;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.tomlj.Toml;
import org.tomlj.TomlParseResult;

import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Optional;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assumptions.assumeThat;

/**
 * Tests for {@link CratesMetadataExtractor} comparing extraction results against
 * source-of-truth expected values produced by native Rust tools in Docker.
 *
 * <p>All test packages are real crates downloaded from crates.io.
 * Expected values were generated by running Docker containers with cargo and jq
 * that parse the actual Cargo.toml from each archive.</p>
 *
 * <p>Package files (.crate) are in {@code test-corpus/crates/} (gitignored).
 * Source-of-truth expected JSON files are in {@code src/test/resources/crates/} (git-tracked).</p>
 *
 * <p>Covers {@link CratesQuirks} Q1 (TOML format), Q2 (feature flags / optional deps),
 * Q3 (build-dependencies), Q4 (renamed dependencies), Q5 (edition field),
 * Q6 (no Cargo.lock).</p>
 */
class CratesMetadataExtractorTest {

    /** Directory containing real .crate files (gitignored). */
    private static final Path CRATES_CORPUS = TestCorpusDownloader.corpusDir("crates");

    /** Directory containing source-of-truth expected JSON files (git-tracked). */
    private static final Path CRATES_EXPECTED = TestCorpusDownloader.expectedDir("crates");

    @BeforeAll
    static void ensureTestPackagesExist() {
        assumeThat(Files.isDirectory(CRATES_CORPUS))
                .as("crates test corpus directory must exist with real packages")
                .isTrue();
    }

    // --- Parameterized source-of-truth comparison ---

    /**
     * Provides all .crate files in the corpus directory paired with their expected JSON.
     */
    static Stream<Arguments> realPackages() throws IOException {
        if (!Files.isDirectory(CRATES_CORPUS)) {
            return Stream.empty();
        }
        return Files.list(CRATES_CORPUS)
                .filter(p -> p.toString().endsWith(".crate"))
                .sorted()
                .map(pkg -> {
                    Path expected = SourceOfTruth.expectedPathFor(pkg, CRATES_EXPECTED);
                    String label = pkg.getFileName().toString();
                    return Arguments.of(label, pkg, expected);
                });
    }

    /**
     * Goal: Verify that the extracted name matches the source-of-truth for every real crate.
     * Rationale: Name is the most fundamental metadata field; must be exact for all packages (Q1).
     */
    @ParameterizedTest(name = "name: {0}")
    @MethodSource("realPackages")
    void extractName_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.name())
                .isEqualTo(SourceOfTruth.getString(expected, "name"));
    }

    /**
     * Goal: Verify that the extracted simple name matches the source-of-truth.
     * Rationale: For crates, simpleName equals name (no namespace concept).
     */
    @ParameterizedTest(name = "simpleName: {0}")
    @MethodSource("realPackages")
    void extractSimpleName_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.simpleName())
                .isEqualTo(SourceOfTruth.getString(expected, "simpleName"));
    }

    /**
     * Goal: Verify that the extracted version matches the source-of-truth.
     * Rationale: Version must match exactly from Cargo.toml [package] section.
     */
    @ParameterizedTest(name = "version: {0}")
    @MethodSource("realPackages")
    void extractVersion_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.version())
                .isEqualTo(SourceOfTruth.getString(expected, "version"));
    }

    /**
     * Goal: Verify that the extracted description matches the source-of-truth.
     * Rationale: Description is optional; some crates have it, some don't.
     */
    @ParameterizedTest(name = "description: {0}")
    @MethodSource("realPackages")
    void extractDescription_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.description())
                .isEqualTo(SourceOfTruth.getString(expected, "description"));
    }

    /**
     * Goal: Verify that the extracted license matches the source-of-truth.
     * Rationale: License can be null (e.g., ring) or SPDX expression (e.g., "MIT OR Apache-2.0").
     */
    @ParameterizedTest(name = "license: {0}")
    @MethodSource("realPackages")
    void extractLicense_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.license())
                .isEqualTo(SourceOfTruth.getString(expected, "license"));
    }

    /**
     * Goal: Verify that the extracted publisher matches the source-of-truth.
     * Rationale: Publisher is first author with email stripped.
     */
    @ParameterizedTest(name = "publisher: {0}")
    @MethodSource("realPackages")
    void extractPublisher_matchesSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        assertThat(result.publisher())
                .isEqualTo(SourceOfTruth.getString(expected, "publisher"));
    }

    /**
     * Goal: Verify that the extracted dependency count matches the source-of-truth.
     * Rationale: All dependency sections must be parsed correctly.
     */
    @ParameterizedTest(name = "dependencyCount: {0}")
    @MethodSource("realPackages")
    void extractDependencies_countMatchesSourceOfTruth(String label, Path pkgPath, Path expectedPath)
            throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        int expectedCount = expected.getAsJsonArray("dependencies").size();

        assertThat(result.dependencies())
                .as("dependency count for %s", label)
                .hasSize(expectedCount);
    }

    /**
     * Goal: Verify that all extracted dependency names, versions, and scopes match the source-of-truth.
     * Rationale: Dependency extraction must correctly parse all TOML dep formats, scopes, and renames.
     */
    @ParameterizedTest(name = "dependencies: {0}")
    @MethodSource("realPackages")
    void extractDependencies_matchSourceOfTruth(String label, Path pkgPath, Path expectedPath) throws Exception {
        MetadataResult result = extractFromPackage(pkgPath);
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);

        var expectedDeps = expected.getAsJsonArray("dependencies");
        List<DepTuple> expectedTuples = new java.util.ArrayList<>();
        for (var elem : expectedDeps) {
            JsonObject depObj = elem.getAsJsonObject();
            String name = depObj.get("name").getAsString();
            String vc = depObj.get("versionConstraint").isJsonNull() ? null
                    : depObj.get("versionConstraint").getAsString();
            String scope = depObj.get("scope").getAsString();
            expectedTuples.add(new DepTuple(name, vc, scope));
        }

        List<DepTuple> actualTuples = result.dependencies().stream()
                .map(d -> new DepTuple(d.name(), d.versionConstraint().orElse(null), d.scope().orElse(null)))
                .toList();

        assertThat(actualTuples)
                .as("dependencies for %s", label)
                .containsExactlyInAnyOrderElementsOf(expectedTuples);
    }

    // --- Named package tests ---

    /**
     * Goal: Verify extraction for serde (most popular Rust crate, optional deps).
     * Rationale: Q2 - serde_derive is optional; scope should be "runtime".
     */
    @Test
    void crate_serde_optionalDependency() throws Exception {
        Path crate = CRATES_CORPUS.resolve("serde-1.0.195.crate");
        assumeThat(Files.exists(crate)).isTrue();

        MetadataResult result = extractFromPackage(crate);

        assertThat(result.name()).hasValue("serde");
        assertThat(result.simpleName()).hasValue("serde");
        assertThat(result.version()).hasValue("1.0.195");
        assertThat(result.license()).hasValue("MIT OR Apache-2.0");
        assertThat(result.publisher()).hasValue("Erick Tryzelaar");
        // serde_derive is optional but still scope=runtime
        assertThat(result.dependencies().stream()
                .filter(d -> d.name().equals("serde_derive") && d.scope().orElse("").equals("runtime"))
                .findAny()).isPresent();
    }

    /**
     * Goal: Verify extraction for libc (zero or minimal dependencies).
     * Rationale: Edge case with very few deps; tests minimal crate handling.
     */
    @Test
    void crate_libc_minimalDeps() throws Exception {
        Path crate = CRATES_CORPUS.resolve("libc-0.2.153.crate");
        assumeThat(Files.exists(crate)).isTrue();

        MetadataResult result = extractFromPackage(crate);

        assertThat(result.name()).hasValue("libc");
        assertThat(result.version()).hasValue("0.2.153");
        assertThat(result.license()).hasValue("MIT OR Apache-2.0");
        assertThat(result.publisher()).hasValue("The Rust Project Developers");
    }

    /**
     * Goal: Verify extraction for openssl-sys (build-dependencies).
     * Rationale: Q3 - build-dependencies must have scope "build".
     */
    @Test
    void crate_openssl_sys_buildDeps() throws Exception {
        Path crate = CRATES_CORPUS.resolve("openssl-sys-0.9.99.crate");
        assumeThat(Files.exists(crate)).isTrue();

        MetadataResult result = extractFromPackage(crate);

        assertThat(result.name()).hasValue("openssl-sys");
        assertThat(result.version()).hasValue("0.9.99");
        // Verify build deps exist with scope "build"
        assertThat(result.dependencies().stream()
                .filter(d -> d.scope().orElse("").equals("build"))
                .toList()).isNotEmpty();
        // cc is a known build dependency of openssl-sys
        assertThat(result.dependencies().stream()
                .filter(d -> d.name().equals("cc") && d.scope().orElse("").equals("build"))
                .findAny()).isPresent();
    }

    /**
     * Goal: Verify extraction for reqwest (renamed dependencies).
     * Rationale: Q4 - cookie_crate alias should resolve to real name "cookie".
     */
    @Test
    void crate_reqwest_renamedDependencies() throws Exception {
        Path crate = CRATES_CORPUS.resolve("reqwest-0.11.24.crate");
        assumeThat(Files.exists(crate)).isTrue();

        MetadataResult result = extractFromPackage(crate);

        assertThat(result.name()).hasValue("reqwest");
        assertThat(result.version()).hasValue("0.11.24");
        // cookie_crate alias → real name "cookie" (Q4)
        assertThat(result.dependencies().stream()
                .filter(d -> d.name().equals("cookie"))
                .findAny()).isPresent();
        // native-tls-crate alias → real name "native-tls" (Q4)
        assertThat(result.dependencies().stream()
                .filter(d -> d.name().equals("native-tls"))
                .findAny()).isPresent();
    }

    /**
     * Goal: Verify extraction for void (minimal crate, zero dependencies).
     * Rationale: Boundary case; simplest possible crate.
     */
    @Test
    void crate_void_zeroDeps() throws Exception {
        Path crate = CRATES_CORPUS.resolve("void-1.0.2.crate");
        assumeThat(Files.exists(crate)).isTrue();

        MetadataResult result = extractFromPackage(crate);

        assertThat(result.name()).hasValue("void");
        assertThat(result.version()).hasValue("1.0.2");
        assertThat(result.license()).hasValue("MIT");
        assertThat(result.publisher()).hasValue("Jonathan Reem");
        assertThat(result.dependencies()).isEmpty();
    }

    /**
     * Goal: Verify extraction for nom (multiple authors).
     * Rationale: Publisher should be the first author only.
     */
    @Test
    void crate_nom_multipleAuthors() throws Exception {
        Path crate = CRATES_CORPUS.resolve("nom-7.1.3.crate");
        assumeThat(Files.exists(crate)).isTrue();

        MetadataResult result = extractFromPackage(crate);

        assertThat(result.name()).hasValue("nom");
        assertThat(result.version()).hasValue("7.1.3");
        assertThat(result.publisher()).isPresent();
    }

    /**
     * Goal: Verify extraction for ring (non-standard license).
     * Rationale: ring uses a license-file, so license field is null.
     */
    @Test
    void crate_ring_nullLicense() throws Exception {
        Path crate = CRATES_CORPUS.resolve("ring-0.17.7.crate");
        assumeThat(Files.exists(crate)).isTrue();

        MetadataResult result = extractFromPackage(crate);

        assertThat(result.name()).hasValue("ring");
        assertThat(result.version()).hasValue("0.17.7");
        assertThat(result.license()).isEmpty();
    }

    /**
     * Goal: Verify extraction for tokio (feature-gated deps, many optional deps).
     * Rationale: Q2 - tokio has many optional/feature-gated dependencies.
     */
    @Test
    void crate_tokio_featureGatedDeps() throws Exception {
        Path crate = CRATES_CORPUS.resolve("tokio-1.35.1.crate");
        assumeThat(Files.exists(crate)).isTrue();

        MetadataResult result = extractFromPackage(crate);

        assertThat(result.name()).hasValue("tokio");
        assertThat(result.version()).hasValue("1.35.1");
        assertThat(result.dependencies()).isNotEmpty();
    }

    // --- Unit tests for isCargoToml ---

    /**
     * Goal: Verify standard Cargo.toml entry is recognized.
     * Rationale: Published crates have entries like name-version/Cargo.toml.
     */
    @Test
    void isCargoToml_standardEntry() {
        assertThat(CratesMetadataExtractor.isCargoToml("serde-1.0.195/Cargo.toml")).isTrue();
    }

    /**
     * Goal: Verify Cargo.toml at wrong depth is NOT recognized.
     * Rationale: Only root-level Cargo.toml should match (depth 2).
     */
    @Test
    void isCargoToml_tooDeep_notMatched() {
        assertThat(CratesMetadataExtractor.isCargoToml("serde-1.0.195/src/Cargo.toml")).isFalse();
    }

    /**
     * Goal: Verify root-level non-Cargo.toml files are NOT matched.
     * Rationale: Only Cargo.toml should match, not Cargo.lock, build.rs, etc.
     */
    @Test
    void isCargoToml_otherFile_notMatched() {
        assertThat(CratesMetadataExtractor.isCargoToml("serde-1.0.195/Cargo.lock")).isFalse();
        assertThat(CratesMetadataExtractor.isCargoToml("serde-1.0.195/build.rs")).isFalse();
    }

    /**
     * Goal: Verify bare Cargo.toml (no directory) is NOT matched.
     * Rationale: Published crates always have a directory prefix.
     */
    @Test
    void isCargoToml_bareFile_notMatched() {
        assertThat(CratesMetadataExtractor.isCargoToml("Cargo.toml")).isFalse();
    }

    /**
     * Goal: Verify path traversal entries are rejected.
     * Rationale: Security — entries with ".." must be rejected.
     */
    @Test
    void isCargoToml_pathTraversal_rejected() {
        assertThat(CratesMetadataExtractor.isCargoToml("../etc/Cargo.toml")).isFalse();
        assertThat(CratesMetadataExtractor.isCargoToml("serde-1.0.195/../../Cargo.toml")).isFalse();
    }

    // --- Unit tests for TOML dependency parsing ---

    /**
     * Goal: Verify simple string version dep parsing.
     * Rationale: Q1 - "dep = version" is the most basic TOML dep format.
     */
    @Test
    void parseDependencies_simpleVersionString() throws Exception {
        String toml = """
                [package]
                name = "test"
                version = "0.1.0"

                [dependencies]
                serde = "1.0"
                """;
        TomlParseResult parsed = Toml.parse(toml);
        List<ParsedDependency> deps = CratesMetadataExtractor.parseDependencies(parsed);

        assertThat(deps).hasSize(1);
        assertThat(deps.get(0).name()).isEqualTo("serde");
        assertThat(deps.get(0).versionConstraint()).hasValue("^1.0");
        assertThat(deps.get(0).scope()).hasValue("runtime");
    }

    /**
     * Goal: Verify table-format dep parsing.
     * Rationale: Q1 - "dep = { version = ... }" is the table dep format.
     */
    @Test
    void parseDependencies_tableFormat() throws Exception {
        String toml = """
                [package]
                name = "test"
                version = "0.1.0"

                [dependencies]
                serde = { version = "1.0", features = ["derive"] }
                """;
        TomlParseResult parsed = Toml.parse(toml);
        List<ParsedDependency> deps = CratesMetadataExtractor.parseDependencies(parsed);

        assertThat(deps).hasSize(1);
        assertThat(deps.get(0).name()).isEqualTo("serde");
        assertThat(deps.get(0).versionConstraint()).hasValue("^1.0");
        assertThat(deps.get(0).scope()).hasValue("runtime");
    }

    /**
     * Goal: Verify optional dep scope is "runtime".
     * Rationale: Q2 - optional dependencies retain scope "runtime".
     */
    @Test
    void parseDependencies_optionalScopeIsRuntime() throws Exception {
        String toml = """
                [package]
                name = "test"
                version = "0.1.0"

                [dependencies]
                serde_derive = { version = "1.0", optional = true }
                """;
        TomlParseResult parsed = Toml.parse(toml);
        List<ParsedDependency> deps = CratesMetadataExtractor.parseDependencies(parsed);

        assertThat(deps).hasSize(1);
        assertThat(deps.get(0).name()).isEqualTo("serde_derive");
        assertThat(deps.get(0).scope()).hasValue("runtime");
    }

    /**
     * Goal: Verify build-dependencies have scope "build".
     * Rationale: Q3 - [build-dependencies] section maps to scope "build".
     */
    @Test
    void parseDependencies_buildDeps() throws Exception {
        String toml = """
                [package]
                name = "test"
                version = "0.1.0"

                [build-dependencies]
                cc = "1.0"
                """;
        TomlParseResult parsed = Toml.parse(toml);
        List<ParsedDependency> deps = CratesMetadataExtractor.parseDependencies(parsed);

        assertThat(deps).hasSize(1);
        assertThat(deps.get(0).name()).isEqualTo("cc");
        assertThat(deps.get(0).scope()).hasValue("build");
    }

    /**
     * Goal: Verify dev-dependencies have scope "dev".
     * Rationale: [dev-dependencies] section maps to scope "dev".
     */
    @Test
    void parseDependencies_devDeps() throws Exception {
        String toml = """
                [package]
                name = "test"
                version = "0.1.0"

                [dev-dependencies]
                tokio-test = "0.4"
                """;
        TomlParseResult parsed = Toml.parse(toml);
        List<ParsedDependency> deps = CratesMetadataExtractor.parseDependencies(parsed);

        assertThat(deps).hasSize(1);
        assertThat(deps.get(0).name()).isEqualTo("tokio-test");
        assertThat(deps.get(0).scope()).hasValue("dev");
    }

    /**
     * Goal: Verify renamed dep uses real package name.
     * Rationale: Q4 - "alias = { version = ..., package = 'real-name' }" → name=real-name.
     */
    @Test
    void parseDependencies_renamedPackage() throws Exception {
        String toml = """
                [package]
                name = "test"
                version = "0.1.0"

                [dependencies]
                my_serde = { version = "1.0", package = "serde" }
                """;
        TomlParseResult parsed = Toml.parse(toml);
        List<ParsedDependency> deps = CratesMetadataExtractor.parseDependencies(parsed);

        assertThat(deps).hasSize(1);
        assertThat(deps.get(0).name()).isEqualTo("serde");
        assertThat(deps.get(0).versionConstraint()).hasValue("^1.0");
    }

    /**
     * Goal: Verify path-only dep has empty version constraint.
     * Rationale: Path deps like "dep = { path = '../local' }" have no version.
     */
    @Test
    void parseDependencies_pathOnly() throws Exception {
        String toml = """
                [package]
                name = "test"
                version = "0.1.0"

                [dependencies]
                local-crate = { path = "../local" }
                """;
        TomlParseResult parsed = Toml.parse(toml);
        List<ParsedDependency> deps = CratesMetadataExtractor.parseDependencies(parsed);

        assertThat(deps).hasSize(1);
        assertThat(deps.get(0).name()).isEqualTo("local-crate");
        assertThat(deps.get(0).versionConstraint()).isEmpty();
    }

    /**
     * Goal: Verify git-only dep has empty version constraint.
     * Rationale: Git deps like "dep = { git = '...' }" have no version.
     */
    @Test
    void parseDependencies_gitOnly() throws Exception {
        String toml = """
                [package]
                name = "test"
                version = "0.1.0"

                [dependencies]
                my-lib = { git = "https://github.com/user/repo" }
                """;
        TomlParseResult parsed = Toml.parse(toml);
        List<ParsedDependency> deps = CratesMetadataExtractor.parseDependencies(parsed);

        assertThat(deps).hasSize(1);
        assertThat(deps.get(0).name()).isEqualTo("my-lib");
        assertThat(deps.get(0).versionConstraint()).isEmpty();
    }

    /**
     * Goal: Verify empty dependencies section produces empty list.
     * Rationale: No dependencies should be extracted from empty sections.
     */
    @Test
    void parseDependencies_emptySections() throws Exception {
        String toml = """
                [package]
                name = "test"
                version = "0.1.0"
                """;
        TomlParseResult parsed = Toml.parse(toml);
        List<ParsedDependency> deps = CratesMetadataExtractor.parseDependencies(parsed);

        assertThat(deps).isEmpty();
    }

    /**
     * Goal: Verify target-specific deps are included.
     * Rationale: Dependencies under [target.*.dependencies] must be parsed.
     */
    @Test
    void parseDependencies_targetSpecific() throws Exception {
        String toml = """
                [package]
                name = "test"
                version = "0.1.0"

                [target.'cfg(unix)'.dependencies]
                libc = "0.2"
                """;
        TomlParseResult parsed = Toml.parse(toml);
        List<ParsedDependency> deps = CratesMetadataExtractor.parseDependencies(parsed);

        assertThat(deps).hasSize(1);
        assertThat(deps.get(0).name()).isEqualTo("libc");
        assertThat(deps.get(0).scope()).hasValue("runtime");
    }

    // --- Unit tests for publisher extraction ---

    /**
     * Goal: Verify email stripping from author.
     * Rationale: "Name <email>" → "Name".
     */
    @Test
    void extractPublisher_stripsEmail() throws Exception {
        String toml = """
                [package]
                name = "test"
                version = "0.1.0"
                authors = ["Alice Bob <alice@example.com>"]
                """;
        TomlParseResult parsed = Toml.parse(toml);
        String publisher = CratesMetadataExtractor.extractPublisher(parsed);

        assertThat(publisher).isEqualTo("Alice Bob");
    }

    /**
     * Goal: Verify no-email author is returned as-is.
     * Rationale: Authors without email should be returned verbatim.
     */
    @Test
    void extractPublisher_noEmail() throws Exception {
        String toml = """
                [package]
                name = "test"
                version = "0.1.0"
                authors = ["Alice Bob"]
                """;
        TomlParseResult parsed = Toml.parse(toml);
        String publisher = CratesMetadataExtractor.extractPublisher(parsed);

        assertThat(publisher).isEqualTo("Alice Bob");
    }

    /**
     * Goal: Verify multiple authors → first author only.
     * Rationale: Publisher is the first author in the array.
     */
    @Test
    void extractPublisher_multipleAuthors_usesFirst() throws Exception {
        String toml = """
                [package]
                name = "test"
                version = "0.1.0"
                authors = ["Alice <alice@x.com>", "Bob <bob@x.com>"]
                """;
        TomlParseResult parsed = Toml.parse(toml);
        String publisher = CratesMetadataExtractor.extractPublisher(parsed);

        assertThat(publisher).isEqualTo("Alice");
    }

    /**
     * Goal: Verify no authors → null publisher.
     * Rationale: Some crates have no authors field.
     */
    @Test
    void extractPublisher_noAuthors_returnsNull() throws Exception {
        String toml = """
                [package]
                name = "test"
                version = "0.1.0"
                """;
        TomlParseResult parsed = Toml.parse(toml);
        String publisher = CratesMetadataExtractor.extractPublisher(parsed);

        assertThat(publisher).isNull();
    }

    /**
     * Goal: Verify empty authors array → null publisher.
     * Rationale: An empty authors array should be treated as no authors.
     */
    @Test
    void extractPublisher_emptyAuthorsArray_returnsNull() throws Exception {
        String toml = """
                [package]
                name = "test"
                version = "0.1.0"
                authors = []
                """;
        TomlParseResult parsed = Toml.parse(toml);
        String publisher = CratesMetadataExtractor.extractPublisher(parsed);

        assertThat(publisher).isNull();
    }

    // --- Malformed/empty Cargo.toml tests ---

    /**
     * Goal: Verify that empty Cargo.toml produces result with empty fields.
     * Rationale: Graceful handling of minimal TOML.
     */
    @Test
    void buildMetadataResult_emptyCargoToml() throws Exception {
        CratesMetadataExtractor.CargoTomlData data = new CratesMetadataExtractor.CargoTomlData("");
        MetadataResult result = CratesMetadataExtractor.buildMetadataResult(data);

        assertThat(result.name()).isEmpty();
        assertThat(result.version()).isEmpty();
        assertThat(result.dependencies()).isEmpty();
    }

    /**
     * Goal: Verify that Cargo.toml with only [package] section works.
     * Rationale: Minimal valid Cargo.toml has only name and version.
     */
    @Test
    void buildMetadataResult_minimalCargoToml() throws Exception {
        CratesMetadataExtractor.CargoTomlData data = new CratesMetadataExtractor.CargoTomlData("""
                [package]
                name = "minimal"
                version = "0.1.0"
                """);
        MetadataResult result = CratesMetadataExtractor.buildMetadataResult(data);

        assertThat(result.name()).hasValue("minimal");
        assertThat(result.version()).hasValue("0.1.0");
        assertThat(result.description()).isEmpty();
        assertThat(result.license()).isEmpty();
        assertThat(result.publisher()).isEmpty();
        assertThat(result.dependencies()).isEmpty();
    }

    // --- Normalized (dotted table header) format ---

    /**
     * Goal: Verify dotted table header format for dependencies.
     * Rationale: Q1 - Published crates use [dependencies.name] format, not inline.
     */
    @Test
    void parseDependencies_dottedTableHeaders() throws Exception {
        String toml = """
                [package]
                name = "test"
                version = "0.1.0"

                [dependencies.serde]
                version = "1.0"

                [dependencies.tokio]
                version = "1.0"
                optional = true
                """;
        TomlParseResult parsed = Toml.parse(toml);
        List<ParsedDependency> deps = CratesMetadataExtractor.parseDependencies(parsed);

        assertThat(deps).hasSize(2);
        assertThat(deps.stream().map(ParsedDependency::name).toList())
                .containsExactlyInAnyOrder("serde", "tokio");
    }

    // --- Helper methods ---

    private MetadataResult extractFromPackage(Path pkgPath) throws Exception {
        try (FileInputStream fis = new FileInputStream(pkgPath.toFile())) {
            return CratesMetadataExtractor.extract(fis, pkgPath.getFileName().toString());
        }
    }

    private record DepTuple(String name, String versionConstraint, String scope) {
    }
}
