/* Copyright 2026 Spice Labs, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License. */

package io.spicelabs.annatto;

import com.google.gson.JsonObject;
import io.spicelabs.annatto.testutil.SourceOfTruth;
import io.spicelabs.annatto.testutil.TestCorpusDownloader;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Parity between the {@link LanguagePackage} API and the source-of-truth expected JSON
 * (issue #14).
 *
 * <p>Goat Rodeo consumes {@link LanguagePackageReader#read}, while the expected JSON files
 * are generated by native tools and checked against the {@code MetadataExtractor}s. This
 * test reads every corpus package for which an expected file exists through the reader and
 * asserts that name, version, description, license and publisher agree exactly, so the two
 * paths cannot drift apart again.
 */
class LanguagePackageParityTest {

    private static final List<String> ECOSYSTEMS = List.of(
        "cocoapods", "conda", "cpan", "crates", "go", "hex",
        "luarocks", "npm", "packagist", "pypi", "rubygems");

    @BeforeAll
    static void ensureCorpus() throws IOException {
        TestCorpusDownloader.ensureCorpusAvailable();
    }

    static Stream<Arguments> packages() throws IOException {
        List<Arguments> args = new ArrayList<>();
        for (String ecosystem : ECOSYSTEMS) {
            Path corpus = TestCorpusDownloader.corpusDir(ecosystem);
            Path expectedDir = TestCorpusDownloader.expectedDir(ecosystem);
            if (!Files.isDirectory(corpus)) {
                continue;
            }
            try (Stream<Path> files = Files.list(corpus)) {
                files.filter(Files::isRegularFile)
                    .sorted()
                    .forEach(file -> {
                        Path expected = SourceOfTruth.expectedPathFor(file, expectedDir);
                        if (Files.exists(expected)) {
                            args.add(Arguments.of(ecosystem + "/" + file.getFileName(), file, expected));
                        }
                    });
            }
        }
        return args.stream();
    }

    @ParameterizedTest(name = "{0}")
    @MethodSource("packages")
    void languagePackageMatchesSourceOfTruth(String id, Path packagePath, Path expectedPath)
            throws Exception {
        JsonObject expected = SourceOfTruth.loadExpected(expectedPath);
        LanguagePackage pkg = LanguagePackageReader.read(packagePath);
        try {
            PackageMetadata metadata = pkg.metadata();
            assertThat(Optional.of(metadata.name()).filter(s -> !s.isEmpty()))
                .as("%s name", id).isEqualTo(SourceOfTruth.getString(expected, "name"));
            assertThat(Optional.of(metadata.version()).filter(s -> !s.isEmpty()))
                .as("%s version", id).isEqualTo(SourceOfTruth.getString(expected, "version"));
            assertThat(metadata.description())
                .as("%s description", id).isEqualTo(SourceOfTruth.getString(expected, "description"));
            assertThat(metadata.license())
                .as("%s license", id).isEqualTo(SourceOfTruth.getString(expected, "license"));
            assertThat(metadata.publisher())
                .as("%s publisher", id).isEqualTo(SourceOfTruth.getString(expected, "publisher"));
        } finally {
            pkg.close();
        }
    }
}
